### ISSUE TITLE
No tests showing up

### ISSUE THREAD

**Issue by bassie1995** [DannyDainton/newman-reporter-htmlextra#1]
Hi, great work on this template! I've been trying it out for the last day, but have noticed no tests showing up.

The counter is always at 0 tests and 0% pass percentage.
I'm using the default template, and the ```htmlfull``` reporter shows the tests.

What direction should I be looking in to fix this? I haven't found anything so far.

**Comment by DannyDainton** [comment]
Hey,



Which version of Newman version of the `htmlextra` reporter are you using?

Do you have an example collection that will help reproduce the problem so that I can have a look what's going on?

It's tricky to know what the problem might be without any additional information. 😁

**Comment by bassie1995** [comment]
Didn't quite know what to include, but here goes:

Running Newman 4.2.2, apparently, but it doesn't want to update. Figured I had the newest still (not too long since I've been working on this, I thought).

I'll try to get it fixed and update :)

**Comment by bassie1995** [comment]
Alright, well, it's working now. Read about the requirement but didn't check which version I had. My bad and thanks for the help!

**Comment by DannyDainton** [comment]
My bad for not including a issue template 😔

Version 4.2.3 of Newman has a specific change in there which exposes the `Skipped Tests` - Something that is not currently exposed by the other HTML reporters.

This change allowed me to change the logic in the reporter to determine if the test was skipped based of a certain flag, my guess is that with the lower version of Newman installed, all the tests are not being totalled up correctly. 

`htmlfull` is a similar reporter but it doesn't current have the same behaviour to know if the tests are skipped or not.
