### ISSUE TITLE
Parameter to change few data to log

### ISSUE THREAD

**Issue by RuggeriLuca** [DannyDainton/newman-reporter-htmlextra#10]
To be able to reduce size of the report is it possible to add a parameter that will log the 
REQUEST BODY
RESPONSE HEADERS
RESPONSE BODY
only for the fails Requests ?

**Comment by DannyDainton** [comment]
You can achieve anything you like by creating a new template and restricting the data that is displayed in the report.

The default templates used are in the `templates` dir so those could be used and edited. 

All of those things could be removed from the current template too.

**Comment by DannyDainton** [comment]
I've created a task to try and add this feature - Going to close the issue for now.

**Comment by DannyDainton** [comment]
@RuggeriLuca I've added a `showOnlyFails` option to the reporter - This is a first attempt at it so it will work with the default `light` template at the moment.
