### ISSUE TITLE
I18n support

### ISSUE THREAD

**Issue by jacktan1991** [DannyDainton/newman-reporter-htmlextra#104]
As described in title, need I18n support

**Comment by DannyDainton** [comment]
You're going to need to add more details to that request. By just referencing the title, I don't know what you mean.

Please expand on this, what you would like to see, why you feel its important and then I can make a decision based on that information. 

Failing that, I'm going to have to close this as there is nothing I can do with the details given.

**Comment by DannyDainton** [comment]
I don't think that I will be adding any specific language support for the reporter. 

As the reporter gives everyone the ability to create their own custom templates, this is something that can be handled by the user.
