### ISSUE TITLE
Can I add my own Custom Helper?

### ISSUE THREAD

**Issue by jnfsmile** [DannyDainton/newman-reporter-htmlextra#105]
I want to do some reformatting, can I define helpers of my own?

**Comment by DannyDainton** [comment]
Without expanding more on that single statement about something you have in your mind - I'm not sure how I can answer that question. :)

**Comment by jnfsmile** [comment]
Eg. I would like to parse the response body (should be json) and expose one of the fields earlier on.

**Comment by DannyDainton** [comment]
Can you give me a mock up or an example image of what you're aiming for?

I still don't really understand the use case?

You have the code locally so you could, technically, add anything you want
and just run this on your own machine.

**Comment by jnfsmile** [comment]
I want _trace_ to be more visible, i.e. print it on a separate card

Response body:
`{
  "code": "402000000",
  "reason": "key: 4111-455a failed.",
  "status": "422",
  "trace": "2b07",
}`

I'm assuming I'll need a helper of my own for this (am I wrong?)
I guess the question is if I need to change the package in order to add such a helper or can this be done by importing it from elsewhere?

**Comment by DannyDainton** [comment]
What does this currently look like on the final report?

What do you want to see happening? Show what you would like the end result to be. 

The default template will display all the information from the Newman collection run in the same way each time. To add a new card for _something_ the template will need to change and you would need to tell it want you want to put in there.

**Comment by jnfsmile** [comment]
Currently I get the response body as a json string

I want a new card, like this: 
![image](https://user-images.githubusercontent.com/2847469/61037909-a9e0ff80-a3d4-11e9-8d68-e7a954397fe9.png)

**Comment by DannyDainton** [comment]
It's a `response body`, from what I can see so I would expect it to be there in that section. 😁

I think you could either create a custom template with that in there and possibly add a helper to the `index.js` file to get that data and use handlebars to display it in your new panel.

You could also `console.log()` than value in the request and then use the `logs` flag to display it on the report.

That's a bit rubbish as it's currently located away from the actual request - I plan to bring these into the requests but I don't have time yet.

**Comment by DannyDainton** [comment]
@jnfsmile

Which approach did you go for in the end?

**Comment by DannyDainton** [comment]
I'm going to close this for now, it's not something that I'm going to be adding to the reporter.

Be interested to see what you come up with though.
