### ISSUE TITLE
Requests in folder are marked with green color if all tests skipped - misleading 

### ISSUE THREAD

**Issue by schwarcu** [DannyDainton/newman-reporter-htmlextra#115]
**Describe The Problem**
If we have some dependencies in our test cases it's preferable to set them ask "Skipped" if precondition/preconditions failed. These are shown in the "Skipped" tab of the report.
However requests in folders are marked with green color instead of yellow. Which is misleading because it looks the same as when all test have passed. 

**Steps To Reproduce**
Have requests with test cases set to skip.

1. Run the collection '...'
2. Open the report '....'
3. Select the `Request` view '....'
4. Check the color of the request

**What Are You Seeing**
It's green instead of yellow (which would clearly indicate that tests for request were skipped)

**Collection and Environment Files**
I am not able to share sorry.

**Version and Platform Information:**
 - `newman` Version - 6.7.0
 - `newman-reporter-htmlextra` Package Version - 6.7.0
 - OS [Ubuntu server 18.04]

**Additional Context**
Add any other context about the problem not mentioned, the more information that can be provided the better. 

- Are you using the reporter from the command line or with a script? - yes
- Are you using the default template or a custom version? - default
- Have you made any local changes to the `index.js` file? - no

**Comment by DannyDainton** [comment]
Hey @schwarcu 

Thanks for raising that - It's a very crude way to determine what's going on, to be honest. It was added as a 'quick view' to know which folders have failed tests. I added the green icon in for consistency.

I guess a similar confusion would come if there were skipped and passed tests as the logic there is basic and done solely using the handlebar syntax. It only really says "If there are any failed tests in this request show a red icon, if not, show a green icon".

I'm happy for you to submit a PR if you want to change this and add the behaviour that should be there or you could create a new template and remove those icons?

**Comment by DannyDainton** [comment]
@schwarcu 

Would something like this be helpful or is this too far down for a 'quick glance' ?

<img width="1233" alt="Screenshot 2019-07-17 at 08 04 48" src="https://user-images.githubusercontent.com/17089546/61354287-bbf5ee80-a869-11e9-9544-0c763fdc4625.png">

I don't really want to remove the icon from the folder level as that's more about seeing which folders contain `Failed` tests and the red/green is like a yes/no.

**Comment by DannyDainton** [comment]
I published a new version of the reporter that has this change. Let me know what you think.

**Comment by DannyDainton** [comment]
Going to close this one, the new feature to make `skipped tests` more visible has been added to the new version.

If you require something else, could you create a new issue please.

**Comment by schwarcu** [comment]
Looks awesome I will update my jobs and check results!
