### ISSUE TITLE
newman: "htmlextra" reporter could not be loaded

### ISSUE THREAD

**Issue by suggers-7F** [DannyDainton/newman-reporter-htmlextra#117]
why -r html success, -r htmllextra fail
I ordery install htmlextra

D:\nodejs>newman run https://www.getpostman.com/collections/631643-f695cab7-6878-eb55-7943-ad88e1ccfd65-JsLv -r html

D:\nodejs>newman run https://www.getpostman.com/collections/631643-f695cab7-6878-eb55-7943-ad88e1ccfd65-JsLv -r htmlextra
newman: "htmlextra" reporter could not be loaded.
  please install reporter using npm

**Comment by DannyDainton** [comment]
This is an environmental issue, the reporter or any reporter needs to be installed at the same level as Newman. So if you have globally installed Newman, then you need to globally install the reporter.

Have you tried doing `npm i -g newman-reporter-htmlextra` ?

**Comment by YiIsMee** [comment]
first step
npm i -g newman-reporter-htmlextra

**Comment by suggers-7F** [comment]
thanks
not htmlextra question
is newman question 
it's success when I reinstall newman
