### ISSUE TITLE
URL encoded POST request missing request body on report

### ISSUE THREAD

**Issue by suggers-7F** [DannyDainton/newman-reporter-htmlextra#119]
I have a request and request mesthod is post
i see report discover have no body 
i want to see body
how to do ?

**Comment by DannyDainton** [comment]
If this is a bug, please create a new issue, filling in all the details in the template. 

Without this information, I simply cannot do anything about this problem.

**Describe The Problem**
A high-level description explaining the issue that you're facing. 

**Steps To Reproduce**
Steps to reproduce the behaviour:

1. Run the collection '...'
2. Open the report '....'
3. Select the `Request` view '....'
4. See the error in `X` section

The command that you're using to run the collection, would be a real help or the `newman` script, if you're using one.

**What Are You Seeing**
A clear and concise description of what you see happening. '_It doesn't work_' or '_Something fails_' doesn't really help anyone so please be as descriptive as possible. If you see an error message, please do include this in the issue report.

**Screenshots and Gifs**
Add `screenshots` or a `.gif` to help explain your problem better. These things help bring the problem to life _A picture paints a thousand words..._

**Collection and Environment Files**
If applicable, provide some sample files - Please mask or remove any sensitive information. These files will help to reproduce the issue locally and lead to a quick fix.

**Version and Platform Information:**
 - `newman` Version [e.g. 4.2.3]
 - `newman-reporter-htmlextra` Package Version [e.g. 1.6.0]
 - OS [Windows 10]

**Additional Context**
Add any other context about the problem not mentioned, the more information that can be provided the better. 

- Are you using the reporter from the command line or with a script? 
- Are you using the default template or a custom version?
- If you are using a custom `.hbs` file, please include this on the report.
- Have you made any local changes to the `index.js` file?

**Label**
Please add a label that best describes the issue.

**Comment by suggers-7F** [comment]
now i only see request headers

Is there a request body showing the report?

**Comment by DannyDainton** [comment]
Please read my comment and edit for issue report - If this isn't done, I can't help you and I will be closing the issue.

**Comment by suggers-7F** [comment]
sorry ，my english is so poor , Didn't make you understand what you said.I apologize

Describe The Problem
i discover report have'nt requests body when method is POST


Steps To Reproduce
Steps to reproduce the behaviour:
   The referenced document json  contains  some requests 
   some requests request Method is POST
   but i only see report have request headers no request body
   i wish report have request body

**Comment by DannyDainton** [comment]
Can you update to the latest version and try again please.

I still require more information on the POST request, what type of data are you sending. 

If you're English is poor, that's OK, you can send the information in images instead.

It's difficult to help with any problem if I can't see what you're seeing - without more details, I'm just guessing.

**Comment by suggers-7F** [comment]
![微信图片_20190717203157](https://user-images.githubusercontent.com/39897104/61376728-496e2880-a8d4-11e9-8d6c-c603aac7d9a0.png)
it's my request's  
method is post 
it's have a body


![微信图片_20190717205038](https://user-images.githubusercontent.com/39897104/61376846-96ea9580-a8d4-11e9-8d5f-52a92a84d478.png)
it's use htmlextra get report
only have REQUEST HEADERS
i wish add REQUEST BODY
how to do?

**Comment by DannyDainton** [comment]
Try this again with the latest version 1.8.3

**Comment by suggers-7F** [comment]
can you understand chinese? 
if you understand i can use chinese  Description problem

**Comment by DannyDainton** [comment]
请使用最新版本1.8.3再试一次

**Comment by suggers-7F** [comment]
thanks, it's succeed
