### ISSUE TITLE
Report not generating right output 

### ISSUE THREAD

**Issue by lucas937** [DannyDainton/newman-reporter-htmlextra#13]
If a testcase is in a loop and running 10 times. 4/10 test case fail then all 10 test are shown as failed. Why is this? In postman the correct output is shown, eg. 4 failed test cases and 6 passed. 

Postman V. 6.7.4

**Comment by DannyDainton** [comment]
Without more details/examples/images/videos/anything about what you're doing and seeing - It's impossible to get you an answer.

Please use the Issue Template provided to add more context and information to the problem.

**Comment by lucas937** [comment]
Hi, 
I understand, my bad. 

Here is the code im running to verify a substring of a filename. It loops through the response as there are multiple files attached. ( I can not show the response body due to company policy)
In the below images we can see that all testcases passed in postman but they failed in the reporter. Why i think the reporter is wrong is because i used another reporter before and that showed each assertion with passed/failed. 
Im using the latest version of Newman Postman and Htmlextra

![htmlreporterpng](https://user-images.githubusercontent.com/48093059/53622939-bfab1080-3bfb-11e9-93ec-a66cb875ea82.PNG)
![postman](https://user-images.githubusercontent.com/48093059/53622940-bfab1080-3bfb-11e9-8797-7588d4dc3c22.PNG)

`jsonData.Drawing.File.forEach(function(file){
pm.test("Verify file name starts with: " + drawingno, function(){
    pm.expect(file.FileName.substring(0,7)).eql(drawingno); 
 }); 
}`

**Comment by DannyDainton** [comment]
What does the Failed Test tab show? 

This prints out the assertion error for those test. It will be helpful to know that reasons for the fails.

**Comment by lucas937** [comment]
Sure, here is the fail tab of the reporter. 
![failtab](https://user-images.githubusercontent.com/48093059/53627225-33531a80-3c08-11e9-8285-05ea14bfda07.PNG)

**Comment by DannyDainton** [comment]
That looks like it's failing because it's trying to deeply equal a `string` to an `integer` - That's nothing to do with the reporter, that's the test within the collection that's failing. The reporter is just telling you what Newman is telling it. 

Have you ran the test independently? If it's failing there it will be failing within the reporter. Have you tried running the collection with just the CLI output from Newman?

**Comment by lucas937** [comment]
Yes i have tried testing it independently, and then it workes fine. Only the failed cases is shown. 

I tried this with the default reporter and that seemed to work fine. But ill try to make some changes in the code as well.

**Comment by DannyDainton** [comment]
By default reporter, do you mean the CLI output or the other HTML reporter? Which version of Newman do you have?

I don't really know what to suggest to be honest, the reporter literally just outputs what Newman is telling it based on the collection file that it's given. It should be failing in the same way if you run it without `htmlextra`.

It the most basic form, this will run it and output the result to the command line.
`newman run <collection.json>`

**Comment by lucas937** [comment]
Booth the CLI and the HTML. Newman version 4.3.1 

But ill try with some code changes and try again.

**Comment by DannyDainton** [comment]
Sorry for not being able to provide a solution, I'm not ruling out an issue in the reporter but it's its outputting that there were test failures, it points more at the collection file and what's within that.

I'm going to close this for now but happy to reopen it if you can get me some more info to repo it on my side so I can look at it closer.

**Comment by lucas937** [comment]
Hello Danny, 

I did some changes in the code and now it seems to work. 

the problem was that i had .eql which should be .contains instead. Sorry for the "non-bug"  thanks for the input. Sometimes you need anothe point of view. 
pm.expect(file.FileName.substring(0,7)).eql(drawingno);

**Comment by DannyDainton** [comment]
Awesome! Glad it works now. 

Always happy to help and it's always good to talk through a problem with someone else. 

Thank you for using the reporter, if you do come across any other issues, please do raise them.
