### ISSUE TITLE
Passed and skipped tests are still shown with showOnlyFails option

### ISSUE THREAD

**Issue by gdekeuster** [DannyDainton/newman-reporter-htmlextra#131]
I run my newman tests in TeamCity with following options
-r htmlextra --reporter-htmlextra-showOnlyFails --reporter-htmlextra-title NewmanTests --reporter-htmlextra-export newmanReport/newmantests.html --reporter-htmlextra-logs --reporter-htmlextra-darkTheme

It looks like the showOnlyFails option is not taken into account. The generated report still contains the passed and skipped tests.

![image](https://user-images.githubusercontent.com/17447083/63029781-6f75f100-beb1-11e9-9a39-c384463f407b.png)

**Comment by DannyDainton** [comment]
Hey,

Thanks for submitting the issue.

Can you use the template for the bug report as this has sections with the information that I require to actually investigate the issue.

Without this, it's just a series of back and forth questions to understand what you mean 😁

It's hard to tell what you mean just from that cropped image, that report didn't have any failed tests. 

Do you mean that you can see those numbers in the Summary view? 

It's going to still create a report but it just won't show any requests in the Total Request view.

**Comment by gdekeuster** [comment]
Hey,
My apologies. This issue can be closed.
I misunderstood the purpose of the showOnlyFails option.
I see now it has an effect on the Total requests page were only failed requests are shown.
Thanks for creating this reporter.

**Comment by DannyDainton** [comment]
No worries, I should probably make that statement clearer. :(

Thanks you using the reporter, all feedback/enhancements are very welcomed.
