### ISSUE TITLE
Not generate htmlextra using –bail folder in error cannot read property

### ISSUE THREAD

**Issue by pabloart** [DannyDainton/newman-reporter-htmlextra#132]
Hello,

npm version: 6.9.0 and 6.10.3
newman version: 4.5.1

I am running newman and sending the following parameters:
**-e**
**-g**
**-d**
**--folder**
**-r** **_htmlextra,cli_**
**--reporter-htmlextra-browserTitle
--reporter-htmlextra-title
--reporter-htmlextra-titleSize
--reporter-htmlextra-export
--bail** **_folder_**
**--insecure
--verbose
--reporter-htmlextra-logs
--ignore-redirects**

As I put --bail folder, if it cannot find a property (error: "Cannot read property 'length' of undefined"), the htmlextra is not generated.

  #  failure                detail

 1.  AssertionError         Status code is 201
                            expected response to have status code 201 but got 503
                            at assertion:0 in test-script
                            inside "XXXXXXXXXXX"

 2.  TypeError              Cannot read property 'substring' of undefined
                            at test-script
                            inside "XXXXXXXXXXX"
error: Cannot read property 'substring' of undefined

If I send only --bail, if it is generated:
![image](https://user-images.githubusercontent.com/22056630/63053429-178eb880-beb8-11e9-8c24-5d362732b1b5.png)

Please, could you check it out?

Thanks and regards.

Pablo.

**Comment by DannyDainton** [comment]
Hey,

I'll take a look in the morning, getting a bit late here :)

Have you tried the same thing with other reporters? The CSV or Standard HTML reporter?

This is a Newman command and independent of the external reporters so if it's not doing it in this one, I would suspect its not doing it there either. 

I would also take a long at your script and understand what that's not defined and that point. That might be something that the community site can help with. 😁

**Comment by pabloart** [comment]
Hi,

Try the -r html report and the same thing happens.

Where it fails is when it does:
if (jsonData.PaymentMethods.length! == null) {

Since the json that it returns does not contain the PaymentMethods, it cannot calculate the length and fails.

Thanks and regards.

Pablo.

**Comment by DannyDainton** [comment]
So this isn't really an issue with this specific reporter and more of a way that Newman functions. I'm going to close this issue as there isn't anything that I can do about it. 

Drop me a message on the community site and I will take a look at the script for you. Send the full script rather that a small piece of it as that doesn't really show that whole picture.

**Comment by pabloart** [comment]
Should I raise the defect in newman?

Thanks and regards.

Pablo

**Comment by DannyDainton** [comment]
I'm not sure what the behaviour of that command is, to even call it a `defect` - It might be worth posting what you're seeing as a question on the community site and gathering information about the expected outcome first. 

Once you have more knowledge around it, then you can maybe raise an issue on the Newman repo.
