### ISSUE TITLE
Beautify option for XML

### ISSUE THREAD

**Issue by ldz-w** [DannyDainton/newman-reporter-htmlextra#137]
Hello!

First of all, thank you for the reporter.

We're testing an API that responds with single-line XML, which is difficult to read (the alternative being copy and paste to a beautifier/editor which is tedious).

Would it be possible to run XML/JSON bodies through a beautifier before adding them to the report (maybe with the option to switch it on/off via command line flags) or add a "Beautify" button right below the request/response body?

Thank you in advance!

**Comment by ldz-w** [comment]
Upon further investigation it seems like this is done for JSON.
I guess the issue only applies to XML then.

**Comment by DannyDainton** [comment]
Hey @ldz-w 

I've not really looked at adding a button but I can look at adding something that will beautify the XML. 

All the XML responses I've been working with have already been formatted that way before so I've not had that issue but I can see how it would be annoying.

If you wanted to submit a PR for a fix that would be cool or you could wait for me to have a look, just unsure on a timeline though. :(

**Comment by ldz-w** [comment]
I understand you can't give me a timeline, I appreciate you taking the time to respond so quickly :)

> 
> All the XML responses I've been working with have already been formatted that way before so I've not had that issue but I can see how it would be annoying.
> 
That'd be the best case scenario, but sadly that's not an option for us.

If I find the time to fix it myself I'll open Pull Request.
I just wanted to open an issue, maybe somebody else who is more familiar with Postman reporters needs the same feature.

I'd appreciate it if you leave the issue open, I'll discuss it with my team to allocate time towards adding this feature.

**Comment by DannyDainton** [comment]
It's more about the JS than Postman, The template that's used is something that I've created and added code to format the JSON response but for XML or Plain Text it just displays it as it receives it.

If I was a pro dev, I would just knock that fix up now but I'd need a bit of time to work out how to do that :)  I'm sure it would be easy for someone else :)

The hacky script in the template looks like this:

```
<script>
function isJSON(data)
{
    var ret = true;
    try {
            JSON.parse(data);
    }
    catch(e) {
            ret = false;
    }
    return ret;
}

$(".prettyPrint").each(function () {
        var data = $(this).text();
        // Verify whether data is JSON
        if(isJSON(data))
        {
                obj = JSON.parse(data);
                data = JSON.stringify(obj, null, 2);
        }
        $(this).text(data);
});
</script>
```
Ugly I know but it's been that way from the start and I've not really changed it as I just _most_ folks would be dealing with JSON. I'd like to change this though!! The code is as good as the person writing it... :)

Any help would be awesome! 👍

**Comment by DannyDainton** [comment]
Hey @ldz-w,

I accepted the PR and made the change to the CHANGELOG file, I wanted to add something else so I thought I would do it at the same time. :)

I think this XML formatting is a good option for the short term but I'm not sure it's going to cover _all_ use cases so I will be looking at changing the way this is done in the future.

Really appreciate you added this feature to the project 🏆

**Comment by ldz-w** [comment]
Hey @DannyDainton !

Thank you for accepting and doing the CHANGELOG changes yourself (only on this account Mo-Fri, it's a work account).
I agree that it should be refactored, but it's good enough for me right now *until* it gets rewritten 😄 

If I think of something else or actually rewrite it myself, I'll open another PR.
