### ISSUE TITLE
no such file or directory, open '/path/to/.html'

### ISSUE THREAD

**Issue by adamcunnington** [DannyDainton/newman-reporter-htmlextra#141]
I have installed newman-reporter-htmlextra and when I run newman with -r htmlextra, I get an error:

error: ENOENT: no such file or directory, open '_path/to_/.html'

It looks like newman is unable to write the HTML report file?

**Comment by DannyDainton** [comment]
Hey Adam,

As you've gone through the process of raising a bug, can you use the template please and fill in the details.

You should see this template when you select `Bug Report` from the new issue flow.

It's just really difficult to actually do anything about problems raised, without the basic details.

**Comment by adamcunnington** [comment]
Ah, whilst filling this out, I have figured your bug out for you :).

My guess is you generate the report name based on the name of the collection - but you don't pass the collection name through a character check func. My collection contains the pipe character which is an illegal character for a name in a file on windows (and UNIX based platforms I believe).

**Comment by DannyDainton** [comment]
That's just the default name that the reporter produces, users tend to create their own file names and save locations by using the `--reporter-htmlextra-export <filename>` CLI flag, when using Newman.

As I don't have control over the names that users give to their Collections, it's difficult to mitigate against these things from happening :)

**Comment by adamcunnington** [comment]
I think this is pretty standard practice; you don't need to know how the
users name their collections - you just need to use a regex sub.

I don't know JS but the python equivalent would semantically be:
valid_file_name = re.sub(r"\W", "_", collection_name, flags=[re.ASCII])

**Comment by DannyDainton** [comment]
Honestly, I'm probably not going to be doing that anytime soon as there is
a valid workaround so it's not blocking anyone from using that reporter.

Adding the export flag to your cli command or in a JS file, if using Newman
as a library, will allow you to create the file.

If I added some knarly regex into that part of the reporter it's going to
log out that your filename is invalid and you would need to change that
anyway.

I could just give it a permanent valid default name, this is what gets sent
through in the standard HTML reporter but contextually, it's doesn't really
mean anything.

**Comment by adamcunnington** [comment]
I disagree but hey - it's your project.

Great template, thanks for sharing.

**Comment by DannyDainton** [comment]
That's cool, no one is always going to agree with everything that people do. 😁 I really appreciate you bringing it to my attention, like I said, it's not something I actually thought about before I made that change. 😔

It will get done at some point but for now, as there is a valid method for exporting the file, I'll be adding that to my backlog.

Always open to PRs so if you find a working solution, please commit the code to the project. I'm only 1 person, there is only so many hours in the day 😁

**Comment by DannyDainton** [comment]
I've added this as an Issue on my backlog, I do want to fix it but I didn't have the time for a full fix now.

I don't want to just give it a generic valid default filename again, that would be a quick solution that I could do now but it's not what I want to go for long term.

I'm going to close this for now and then track the issue elsewhere.
