### ISSUE TITLE
Console Logs are attached to report by default

### ISSUE THREAD

**Issue by ggpai** [DannyDainton/newman-reporter-htmlextra#144]
**Describe The Problem**
Console logs are attached to report by default

**Steps To Reproduce**
1. Run the collection '...'
newman run DataSet_Nimbus.postman_collection.json -e Template.postman_environment.json --env-var URL=%APIURLvalue% -k --export-environment env_update.json --reporter-htmlextra-browserTitle "APIDataSet" -r htmlextra --reporter-htmlextra-export ./TestResult_DataSets

**What Are You Seeing**
issue 1: When report is generated its contains **console logs** by default. I have not mentioned --reporter-htmlextra-logs that means by default its false and console logs should not be attached. 

Issue 2: I see that html reported generated is around ~20 MB, Any idea how to get report with reduced size?

**Screenshots and Gifs**
![image](https://user-images.githubusercontent.com/35941785/64499474-f4181d00-d26d-11e9-9484-cee909b782a9.png)

**Version and Platform Information:**
 - `newman` Version 4.4.0
 - `newman-reporter-htmlextra` Package Version 1.0.3
 - OS Windows 10

**Comment by DannyDainton** [comment]
Hey @ggpai,

Can you delete the parts of that issue template that are unchanged and also explain what that actual problem in that you're seeing, please.

**Comment by DannyDainton** [comment]
Your Newman and reporter version is massively out of date - That flag to change the log visibility came in at v1.7.0 and you're using v1.0.3

Can you update both and check again.

**Comment by DannyDainton** [comment]
Hey @ggpai,

Did the upgrade help with the issue?
