### ISSUE TITLE
Reporter not generating file when error in test-scripts (CLI does)

### ISSUE THREAD

**Issue by samesfahani** [DannyDainton/newman-reporter-htmlextra#146]
**Describe The Problem**
There is no file generated by the reporter if the error being thrown is in test-scripts. By comparison, the CLI does report on that error.

**Steps To Reproduce**
Steps to reproduce the behaviour:

1. Create a test that fails in a script exec (e.g. try to reference undefined)
2. Run tests with CLI and htmlextra as reporters
3. Observe that the CLI reports on it but not htmlextra

**Screenshots and Gifs**
![image](https://user-images.githubusercontent.com/27975019/64569502-a6fa8080-d32b-11e9-97ba-6d67ed0d3da6.png)

**Version and Platform Information:**
 - `newman` Version [e.g. 4.5.3]
 - `newman-reporter-htmlextra` Package Version [e.g. 1.8.8]
 - Mac mojave

Hopefully this is clear enough.

**Comment by DannyDainton** [comment]
What command are you using with the reporter?

What's the name of your collection? 

Do you have a Newman directory created with the file in?

If it's a test failure, there is no reason why it wouldn't create that file, did it throw any sort of error?

**Comment by samesfahani** [comment]
Hmm, it seems to be related to the `abortOnError` and `abortOnFailure` flags. If I set them to false, the report generates fine. Not sure if this is expected.

**Comment by DannyDainton** [comment]
Those flags are part of Newman and independent to any of the reporters, the internal code of Newman would have something in there that blocks the report being created using any of those flags when using the CLI reporter. 

This reporter can only output what Newman tells it, in the Summary object, if the processing of that is blocked when using those flags, there isn't a lot that I can do from my side.

I'm going to close this issue for now but feel free open it back up again.
