### ISSUE TITLE
API data is not found in newman html-extra report for request which initiated through pm.sendrequest

### ISSUE THREAD

**Issue by spoloju** [DannyDainton/newman-reporter-htmlextra#147]
create an async call via pm.sendrequest in the pre-request script of the main request & run through Newman. 
HTML extra report will be generated once the request is completed.
Open the HTML report. 
Issue - you will not find pm.sendrequest call data in Total request's tab & Failed Test tab.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DannyDainton** [comment]
This is an issue with Newman, you get the same thing happening on any reporter.

https://github.com/postmanlabs/newman/issues/1303

It's not something I can do anything about without a change to Newman.
