### ISSUE TITLE
Support naming report file when using collection.item

### ISSUE THREAD

**Issue by neillindberg** [DannyDainton/newman-reporter-htmlextra#148]
I found that I could run a single test out of a collection:
https://github.com/postmanlabs/newman/issues/337

That's great. I use jsonpath, grab the single item:
```
const collection = require('path_to.postman_collection');
const mySingleItem = jsonpath.query(collection, '$.item[0].item[?(@.name == \'Some Folder\')].item[?(@.name == \'Single Item Name\')]');
newman.run({
    collection: {
        item: mySingleItem
    }
    reporters: ['htmlextra']
}, function (err) {
    if (err) { throw err; }
    console.log('collection run complete!');
});
```
That's great! However, it seems this package uses the name of the base collection to name the resultant html file. So, when I run the above I get: undefined-\<datetime\>.html
I've verified that running the full collection results in: \<collection name\>-\<datetime\>.html

So, I'm asking that there is either:
- A property used to name the resulting file?
- Consideration for the single "item" having been run and name the file after it?

**Comment by DannyDainton** [comment]
Hey @neillindberg, 

You _could_ use the `export` key from the `reporter` options, in your file, to name the file whatever you like.

If this isn't used, it will use the default. That currently is the Collection name which is becoming a pain actually for a number of reasons but this just adds fire to that argument. 

As you've used the library version of Newman, you could use the same variable name for the single request in the filename. 

```javascript
reporter: {
        htmlextra: {
            export: `${mySingleItem}_${new Date().toISOString()}.html`
        }
    }
```

Just added that timestamp for an example but you can use anything that's going to result in a valid filename.

**Comment by DannyDainton** [comment]
@neillindberg Did this help you out, don't really want to leave an open issue sitting here getting stale.

**Comment by DannyDainton** [comment]
I've provided a workaround to your specific issue so I'm closing this issue now but feel free to open it again if you require more information.
