### ISSUE TITLE
Go to top button into the "Console Logs" section

### ISSUE THREAD

**Issue by Kriz1881** [DannyDainton/newman-reporter-htmlextra#152]
**Is your feature request related to a problem? Please describe.**
When there are a lot of console log messages and the user scroll to the bottom of the page, there is no option to go to the top of the report as in "Total Requests".

**Describe the solution you'd like**
"Go to top" button into the "Console Logs" section

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by DannyDainton** [comment]
That's a good idea - I did plan on doing that but I think I held off because I wanted to move the console logs into the individual requests, rather than have them in a separate area.

I'll take a look at doing this for sure.

**Comment by Kriz1881** [comment]
I would love to see the console logs into individual requests!

Keep up the good work, the reporter is really great :)

**Comment by DannyDainton** [comment]
I have something that I can add to the templates that will add this in for the Console Logs but I'm not 100% happy with it, it will work but it's only really going to be a short term thing until I can get the logs into the requests.

**Comment by Kriz1881** [comment]
@DannyDainton  Thank you!
Looking great, I`m updating asap :)

**Comment by DannyDainton** [comment]
I updated the styling _slightly_ to be more consistent so it might look different than the gif posted.

Let me know if it's rubbish though :)

**Comment by Kriz1881** [comment]
Hi @DannyDainton,
I have tested the "Go to top" button and it is not visible (at least with my tests) when thare are no "skipped" requests (please see the attached gif).

![gif](https://photos.app.goo.gl/EPaC3KTTrWE7SgbN6)

Also there is an error into the console on page scroll:
backToTop.html:12496 Uncaught TypeError: Cannot read property 'style' of null
    at scrollFunction (backToTop.html:12496)
    at window.onscroll (backToTop.html:12490)

**Comment by DannyDainton** [comment]
Let me have a look, I did see that when I added it in a different place but thought I fixed it.

My bad, leave it with me. 😔

**Comment by DannyDainton** [comment]
Do you use the default theme or the Dark theme?

**Comment by Kriz1881** [comment]
I`m using the default theme

**Comment by DannyDainton** [comment]
Yeah, I can see the issue. I'll fix that as soon as I can.

**Comment by DannyDainton** [comment]
Ok, I pushed a fix.

Can you to the latest version and give it another go please?

**Comment by Kriz1881** [comment]
On it :)

**Comment by Kriz1881** [comment]
@DannyDainton  🥇 
Working great now!

**Comment by DannyDainton** [comment]
Going to close this issue.....again!

Sorry for not getting it right the first time, basically didn't test it properly and saw the problem straight away. Doh!

Oh well, there is a lesson learnt here. :)

Thanks for flagging that!! 🏆

**Comment by Kriz1881** [comment]
@DannyDainton Thank you for the implementation and the fast response :)

Looking forward for the future console logs improvements!

**Comment by DannyDainton** [comment]
@Kriz1881 The logs should now be part of the requests, with the new release.

**Comment by Kriz1881** [comment]
@DannyDainton I just checked, the logs are looking great! 
Thank you and keep up the good work :)
