### ISSUE TITLE
Html Report - Docker Image - Delay in report and calculate total runtime 

### ISSUE THREAD

**Issue by josephthanaraja** [DannyDainton/newman-reporter-htmlextra#154]
I AM SUCCESSFULLY using the htmlextra report with Newman docker images but facing an issue form Jenkin pipeline. The issue is, reports are taking more time with more than 500 test cases but my jenkin pipeline is not waiting for the reports and to solve this issue, I have added some seconds in my pipeline (Sleep(seconds)) but that is not the actual work around. Since tomorrow we may add another 100 test cases so again I need to increase the seconds and deliver my jenkins file. Do we have any fix for this?

**Comment by DannyDainton** [comment]
That's not really a specific issue with this reporter or even an enhancment that I can make. 

It's basically a dynamic HTML file that will get bigger and bigger the more you add to it. There are some cli flags that chop down parts of the final report that you could try. 

Do you _need_ everything in the report? Who's the report for? What do they _need_ to see?

**Comment by DannyDainton** [comment]
I'm going to close this issue as you've asked the same question on the Newman repo.

I don't feel this is an issue with this reporter or at least something that I can change to help your environment setup.

**Comment by josephthanaraja** [comment]
But is there any way (flag or any attribute) to find the REPORT completion status?

**Comment by josephthanaraja** [comment]
Got the solution by removing docket run "-t" and added added run "-x" in newman
