### ISSUE TITLE
newman reporter with other frameworks

### ISSUE THREAD

**Issue by tceu-mihirmehta** [DannyDainton/newman-reporter-htmlextra#156]
Hi Danny,

This is not an issue but a general piece of information which may be useful to many in the community.

I use Karate DSL framework to run my API tests and I am very happy with the framework. Newman html reports are perhaps the best reports that I have seen amongst the other reporting tools and I would love to integrate these with my current Karate framework. Is it possible to add the reporter as a third party plugin and still reap the benefits of such wonderful reports? If so, can you suggest the best way forward in using them please?

**Comment by DannyDainton** [comment]
Hey @tceu-mihirmehta,

Thanks for the question!

Karate DSL is not something that I'm familiar with, having never used it. I'm not really sure what the output format of that would be. The output of Newman is JSON, in a particular format. 

This reporter would only work with Newman as the final reports are all created from the data coming from that Parent project, as it is, it couldn't be run independently.  

The actual templates alone _could_ be opened in a browser but the details wouldn't be there and it's also created dynamically based on the number of Folders, Requests, Tests etc.

Not really sure that's the answer you wanted, I just have zero knowledge of Karate to even begin to offer the best way forward.

**Comment by DannyDainton** [comment]
I'm going to close this issue out as it has nothing specifically to do with this reporter or anything that I can _fix_ 😁
