### ISSUE TITLE
Failed tests show very limited information

### ISSUE THREAD

**Issue by sumanthmattapalli** [DannyDainton/newman-reporter-htmlextra#159]
Hi,

First of all thanks for such a great template. I want to suggest a small improvement to the template.

On total requests, In iteration view, we show a lot of information about each request but when it's on failed tests it just shows about the Assertions. 

Is there any way can we show the same information about the request in failed test request as we are showing under Total test requests?

Thanks
Sumanth

**Comment by DannyDainton** [comment]
Hey @sumanthmattapalli 

Are you able to give me a visual example of what you mean, please?

**Comment by sumanthmattapalli** [comment]
Thanks for you reply @DannyDainton .

When i click on Failed tests, it is redirect me the below image with just assertions.

<img width="1343" alt="Screenshot 2019-11-27 at 12 33 34 a m" src="https://user-images.githubusercontent.com/17916407/69683736-ca70d400-10ad-11ea-8584-8ab0f88f72b3.png">

When I go thru Total requests for the same request , I can detailed information like request and response information.

<img width="1361" alt="Screenshot 2019-11-27 at 12 33 59 a m" src="https://user-images.githubusercontent.com/17916407/69683738-cba20100-10ad-11ea-8ec4-6c88113d1b16.png">
<img width="1274" alt="Screenshot 2019-11-27 at 12 34 04 a m" src="https://user-images.githubusercontent.com/17916407/69683741-cd6bc480-10ad-11ea-9d34-df77d4f0ba23.png">


Is there anyway, I can integrate the request and response information for Failed tests ?

Thanks,
Sumanth

**Comment by DannyDainton** [comment]
I don't plan on putting those things together. Those are different contexts and the failed test would lead to the extra info on the single request side

**Comment by DannyDainton** [comment]
The request details are already with the failures reasons in the main request view. I don't see a reason to duplicate all the information in 2 places.

This isn't something I'm going to be working on so I'm going to close this issue. If you want to have a go at doing and sent me a PR, I will be happy to take a look.
