### ISSUE TITLE
Question about the reporter 

### ISSUE THREAD

**Issue by lucas937** [DannyDainton/newman-reporter-htmlextra#16]
Hi Danny, 
This is not an issue. But i was wondering if its possible to add colors on the Total Request Page. For example i have about 1800 request and i want to see directly if any test cases failed in any request. 

See my example( sorry for the bad coloring hehe). 
![capture](https://user-images.githubusercontent.com/48093059/53717779-81ab2800-3e59-11e9-9a3e-7e2ad0b111da.PNG)

**Comment by DannyDainton** [comment]
First of all - I apologise for it looking like that when you have multiple iteration. I really need to look at pagination to make that look and feel a lot better - I was aware that it was going to do that after a certain number (21?). :(

As per your request, it's a custom template giving you the power to do that on your side - You can change anything you like on it. :) 

If you want to add that into the template that you're using, go for it. If you get a working copy that might be useful to others, send me a PR. :)

**Comment by lucas937** [comment]
No worries, thats okey by me. 

Okey, ill give it a try. Im not that familiar with HTML code, but ill try to figure it out. 

Yeah, i saw the Failed Tests tab, but it so many request iterations and its a bit hard to jumping around. Like I mention i have around 1800 request x 2 basically, which generates  ruffly 65.000 asserts. 

But thanks for the help! You can close this issue if you want.

**Comment by DannyDainton** [comment]
I'm just about the added an option to show only the requests with failed tests, this won't solve/help with the issue but at least the iteration tabs will show only the failures, when you click them. :) This is a trial so it's only for the `light` version of the dashboard.

I have lots of things I want to try and add but I'm only able to do these things if I have enough time. :(

**Comment by lucas937** [comment]
Okey perfect! That will help its fine with the light version.

**Comment by DannyDainton** [comment]
@lucas937 That's been added to the 1.6.0 version. Use the `showOnlyFails` option to use this feature. Any issues with it, give me a shout.

**Comment by lucas937** [comment]
Thanks man! will do!

**Comment by DannyDainton** [comment]
@lucas937 This is now on the dark version too - Just use the `showOnlyFails` and `darkTheme` together.

**Comment by azgo** [comment]
Hi Danny!
Is there a way to make this showOnlyFails feature switchable, e.g. with a button that filters the report tabs and then shows them all again?
Brgds,
Gergő

**Comment by DannyDainton** [comment]
Hey,

Yeah probably, you would need to create a new custom template if you wanted to though. 

You could just add a toggle in the report and filters out the two different items in the UI. 

Not something I'm looking to do myself but that's the beauty of being able to create your own template 😁

**Comment by azgo** [comment]
True, true :)
You know how comfy is when wishes materialize from thin air ;) Had to try :)))
Brgds

**Comment by DannyDainton** [comment]
You could give it a go and submit a PR, everyone gets the benefits then 😉
