### ISSUE TITLE
HTML report slow to open

### ISSUE THREAD

**Issue by sodongit** [DannyDainton/newman-reporter-htmlextra#160]
After creating a report, opening the html report page is VERY slow.
The page will load then hang for 7 seconds for just 1 iteration of a test
In chrome it is saying that 

```javascript
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.13.1/highlight.min.js"></script>
<script>hljs.initHighlightingOnLoad();</script>
```

is the blocking script and after removing the lines the page returns to a normal loading time.

**Comment by DannyDainton** [comment]
Hey @sodongit,

That issue is lacking any detail for me to really do anything about it - please ensure that you follow the headings in the issue template to provide the relevant information.

One of the main causes for slow loading would be the size of the report - It's a dynamically created HTML page so the bigger the Collection or the number of Iterations you have running will create a larger static file.

There are a number of flags available to you to reduce the amount of data returned in the report, is it all needed? 

Are you or anyone else looking at every single request, in every folder, on every iteration?

**Comment by sodongit** [comment]
Hi Danny 

Thanks for the quick reply.

Actually I found the cause of the slow page is the running of highlight.js. When I removed the method call for running it the page ran at an acceptable load time of < 300ms of a large run 272 total requests.

It is causing such a big delay because it needs to create a whole load of html just to highlight different colours in the Json response. 
Can it be turned off by default and turn it on by a parameter like the title is?

I know its a nicety but is it a worth having from the get go if its slowing it down this much?

**Comment by DannyDainton** [comment]
I'll add it to the back log of things I need to do, just need more time.

You could just created a custom template in the meantime and remove what you don't need. That custom template can be then used with the reporter.

**Comment by sodongit** [comment]
And time is what I wont be given to do a custom template which is why Im looking for one

**Comment by DannyDainton** [comment]
You have the reporter code locally after installing it, in the `lib`
directory of the reporter you'll see the default handlerbars template used
by the reporter.

Copy that, remove the lines, use that as the new template using the `-
-reporter-htmlextra-template <path to template>`

That's literally the least amount of time needed for any of the solutions 😁

**Comment by sodongit** [comment]
Thanks I hadnt really investigated how the templates worked.
I'll give it a go!

**Comment by DannyDainton** [comment]
An even easier way would be just to grab it from here:

https://github.com/DannyDainton/newman-reporter-htmlextra/blob/master/lib/dashboard-template.hbs

**Comment by DannyDainton** [comment]
@sodongit Did you manage to create and use a template?

**Comment by DannyDainton** [comment]
Closing this issue for now, not currently working on this but I do plan to look at the size of the reports.

**Comment by DannyDainton** [comment]
Hey @sodongit - In the latest version I included a `noSyntaxHighlighting` flag. I haven't documented it anywhere but I thought let you know. 

It's on by default so you would add the `--reporter-htmlextra-noSyntaxHightlighting` flag to the command if you're running it globally.

Would be cool if you could try it out.

**Comment by half-eaten-apple** [comment]
@DannyDainton  After using  `--reporter-htmlextra-noSyntaxHightlighting` flag also i see lot of slowness in opening the html report. I have total 94requests in my collection and 200+ assertions. html file size = 22342 kb.
Using htmlextra version 1.22.3
