### ISSUE TITLE
Not able to see all the request and response in the reporter

### ISSUE THREAD

**Issue by SPKannan** [DannyDainton/newman-reporter-htmlextra#161]
**Describe The Problem**
Newman reporter is not showing the all the request and response.

**Steps To Reproduce**

1) Create Collection Folder in Postman
2) Add a request For it
3) Click on the (...) in collection Folder and Click On Edit
4) Click On test Tab and a Request Programmatically(use Pm.Sendrequest)
5) Run the Collection in newman

**Expected Report**
when i open the newman reporter i should two request and two response

Request 1 should be the request body that present under the collection
Response 1: Response from request1
Request 2: Request that we added in the Test Tab present in Collections Folder
Response 2: Response to the Request 2

**Actual Report**

- Not able to see the Request Body and its response which is created in step2
- Able to see the request and response that we used in Test Tab present in Collections Folder
- Able to see Request Name which we created under Collections folder

**Comment by DannyDainton** [comment]
Which version of the reporter are you using?

**Comment by DannyDainton** [comment]
You mentioned using `pm.sendRequest()` - There is a known issue, open for a long time around using that function with the reporters. It impacts all the reporters, not solely this one.

https://github.com/postmanlabs/newman/issues/1303

**Comment by DannyDainton** [comment]
@SPKannan Any updates from your side, you raised the issue and I need the extra information to be able to do something to help.

**Comment by SPKannan** [comment]
Yes i would like to help you. Post your list.. will try to accommodate but guaranteed  with all the information

**Comment by DannyDainton** [comment]
> Hey @SPKannan
> 
> Which version of Newman and the htmlextra reporter are you using?

Read the other message regarding Newman and the `sendRequest()` - if that relates to your issue, there is nothing that I can do and I will be closing this issue.

**Comment by SPKannan** [comment]
i just mentioned i'm i'm using  pm.sendRequest(Request1, function(err, res) {
}
Request1 = {
    url: pm.environment.get('URI'),
    method: "GET",
    header: {
        "Content-Type": "application/json",
        "Accept": "application/json",
        "Authorization": "Bearer " + pm.environment.get("api_Bearertoken")
    }
};

**Comment by SPKannan** [comment]
+-- cheerio@1.0.0-rc.3  
+-- newman@4.5.4
+-- newman-reporter-htmlextra@1.8.6  
+-- newman-reporter-junitxray@1.0.2

**Comment by DannyDainton** [comment]
This is a Newman issue, there is nothing I can do about this and it impacts every single reporter.

Closing issue.
