### ISSUE TITLE
Option to format response to be pretty print xml with line breaks

### ISSUE THREAD

**Issue by angmas** [DannyDainton/newman-reporter-htmlextra#165]
**Is your feature request related to a problem? Please describe.**
Hi, we've been using postman to verify soap services. The response is returned as linearized xml. It would be awesome if there were a way to include an option to format the response as pretty print xml with line breaks.

**Describe the solution you'd like**
Maybe add a -rxml option or something that can call out the formatting option to be applied.

**Describe alternatives you've considered**
I haven't considered any other alternatives.

**Additional context**
n/a

**Comment by DannyDainton** [comment]
Hey @angmas,

Would you be able to give me some environment details please? Which versions are you using?

Could you also attach a screenshot of what you're seeing and how you would like to see this look. 

Cheers.

**Comment by DannyDainton** [comment]
Formatting for XML responses was added to the reporter in veraion 1.8.7

https://github.com/DannyDainton/newman-reporter-htmlextra/pull/139

Are you using the latest version or do you require something different?

**Comment by angmas** [comment]
My bad. I updated to the newest version and see that it is formatted. Great work!
