### ISSUE TITLE
Combined html report for multiple postman collections

### ISSUE THREAD

**Issue by MahatmaFatalError** [DannyDainton/newman-reporter-htmlextra#167]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when I run my approx. 100 postman collections in a sh script and get 100 corresponding html reports.

**Describe the solution you'd like**
Functionality to combine all newman runs into a single html report so that I have a clear overview, especially of the failed ones.

**Comment by DannyDainton** [comment]
Hey @MahatmaFatalError 

Thanks for raising this issue - Unfortunately, there is nothing I can actually do to help here. This isn't a specific reporter issue, it's a Postman/Newman functionality issue.

You would get the same result, no matter what reporter you use. It's a one Collection run at a time type thing in the app and with Newman so until that gets added, you're not going to get what you require.

There are packages out there that combine collections to make a single one, which could be used with the reporter but that would also come with a bunch of different problems. 

https://www.npmjs.com/package/postman-combine-collections

I'm going to close this as I can't really do anything about the current Postman functionality.
