### ISSUE TITLE
[UI/UX] Generated report when multiple iterations are run

### ISSUE THREAD

**Issue by wmedali** [DannyDainton/newman-reporter-htmlextra#174]
When generating report with multiple iterations (+150) and each iteration contains multiple requests (+5) the report file become so large (like 30 Mb for the html). Then the rendering of the iterations number **doesn't help to navigate between iterations and it's a not easy to know which iteration is clicked as it is not highlighted**

**Steps To Reproduce**

1. Run the collection Postman Echo with parameter ''n 150"
2. Open the report 
3. Click the Total Requests button 

newman run https://www.getpostman.com/collections/161a23965791d263a3e6 -r cli,htmlextra -n 150 

![image](https://user-images.githubusercontent.com/23320355/73594359-1d339580-450e-11ea-8bed-1c6f64c7456e.png)

**Version and Platform Information:**
 - `newman` Version 4.5.5
 - `newman-reporter-htmlextra` Package Version1.9.2
 - Windows 10

**Additional Context**
Add any other context about the problem not mentioned, the more information that can be provided the better. 

- Using the reporter from command-line
- Using the default template
- No local changes done

**Comment by DannyDainton** [comment]
@wmedali Not tackled the rendering of all the tabs or the performance but I did try and make the selected tab more visible in the UI to at least make it a little easier to see which one is selected.

**Comment by wmedali** [comment]
@DannyDainton I confirm, it is more visible now. I tested it for the default and dark theme templates.

**Comment by DannyDainton** [comment]
@wmedali I've also added, to 1.10.1, a couple of buttons to expand and collapse all the requests. I think that's what you were asking for.

**Comment by DannyDainton** [comment]
Hey @wmedali, 

I've been messing about with the UI, not sure if I'm 100% happy yet but this is what I did.

Let me know what you think?

![Iterations](https://user-images.githubusercontent.com/17089546/73976178-a9cfc080-491f-11ea-9c10-d258040c0d40.gif)

**Comment by wmedali** [comment]
Hey @DannyDainton 
It is so cool what you did. 
I suggest that you color the iterations with failed tests in red (in my daily usage of the report I always go to failed tests to get the iteration number and then go back and look for iteration then check the failed test .. so I think it's much easier if the iterations with failed tests could be found easily in the total requests view )
Big 👍 on the filter and the text indicating with iteration is selected.
For the scroll, I don't know if it's really great in a UX point of view, I'll need to test it to give feedback.

Goog job 👏

**Comment by DannyDainton** [comment]
I had a go at previously adding color, to the tabs, it was more of an experiment that I didn't end up saving so I will need to revisit that to see how I did it before.

The scroll is based on the width of the container and auto does that when it goes over 22 iterations. 

I wanted something quick in there instead of the wall of numbers. Didn't spend more than 2 mins doing that so I need to take another look.

**Comment by DannyDainton** [comment]
This is how I had it before. 

https://github.com/DannyDainton/newman-reporter-htmlextra/projects/1#card-18894857

**Comment by wmedali** [comment]
that's exactly what I am proposing. can't wait to see it in my reports :)

**Comment by DannyDainton** [comment]
I don't promise that you will see that in there soon. I will take a look when I get some more time 😁

**Comment by wmedali** [comment]
That's not really urgent. Take your time and thanks again for your reactivity  🙏

**Comment by DannyDainton** [comment]
Made an attempt to get this into the report again, not there but it won't be too long. :)

![Screenshot 2020-02-10 at 13 45 23](https://user-images.githubusercontent.com/17089546/74155016-ada75f80-4c0b-11ea-8e58-d82f2c3010cf.png)

**Comment by DannyDainton** [comment]
@wmedali I think I'm nearly there now, what do you think?

![Iterations_Update](https://user-images.githubusercontent.com/17089546/74174287-924c4c80-4c2b-11ea-9786-920ca1209648.gif)

**Comment by wmedali** [comment]
I think it's good. YOU ARE THERE 
I remarked something @DannyDainton, that 4 buttons to Expand/Collapse are too much and make it complicated for a simple consulting the report. It might be changed to only two.
Expand folders, once clicked it changes to Collapse folders. Same thing for requests.
Stills the problem is maybe when user changes iteration what is the expected behavior 🤔 
 It's just a suggestion to enhance UX, maybe you have another opinion. What fo you think ?

**Comment by DannyDainton** [comment]
Yeah I'll change the buttons, I didn't want 4 there anyway. You could also give it a go yourself and raise a PR 😁

The buttons will open all folders/requests, they are not for opening individual iterations.

**Comment by wmedali** [comment]
I'd really would have liked to do that that but I'm hell of a newbie in node/js programming. promise I'll give it a try next days to clone the repo and miss a little bit with the reports ^_^

**Comment by DannyDainton** [comment]
I've pushed the changes and you can see these in V1.11.0

I'm going to do the buttons in a different commit, I want to think about it a little more first.

**Comment by wmedali** [comment]
Working like a charm 👍
