### ISSUE TITLE
[enhancement] hide all headers without providing a list

### ISSUE THREAD

**Issue by wmedali** [DannyDainton/newman-reporter-htmlextra#175]
**Is your feature request related to a problem? Please describe.**
There are multiple options related to headers of requests/responses : 
- skipHeaders : hide a list of headers in report
- skipSensitiveData : hide all headers and payloads of requests and responses
My problem is that I actually call many APIs in my collection and for each of them there is differents type of headers in requests and responss. So I find it frustrating to give a list of headers to hide. In the other hand I don't want to use **skipSensitiveData** because it's important to have ability to read payloads.

**The solution you'd like**

- A third parameter that makes it possible to hide all headers and display only payloads
OR
- when not giving a list for 'skipHeaders' then the reporter automatically hides all headers

**Comment by DannyDainton** [comment]
This is quite a simple change so I will get this done as soon as I can. I will probably end up having another argument like `omitHeaders` or something and if it's set to `true`, it will exclude them from the final report.

**Comment by DannyDainton** [comment]
@wmedali I've pushed a new version (1.10.0) with this change in it, could you give this a go for me, please?

**Comment by wmedali** [comment]
@DannyDainton the new parameter is working like a charm 👍
