### ISSUE TITLE
Is it possible to capture all requests involved in particular request in HTML report 

### ISSUE THREAD

**Issue by Sathish787** [DannyDainton/newman-reporter-htmlextra#176]
In a Request, I have one pm.sendRequest in pre-request script section , main request and one pm.sendRequest in Test section in POSTMAN.

When I generated HTML report for this request, report displays info about last request executed from Test section instead of Main request.

It would be good if we capture all requests info. Could you try on this if possible.

My scenario is : Before creating a user, I get a valid role using role endpoint, then I append request body of actual request and after firing actual request, in test section, I fire get user endpoint to get all users and validate newly added user exist or not.

It would be great help we get this info.

**Comment by DannyDainton** [comment]
This is a known issue with Newman and not this reporter, I can only report on what is coming from there. Unfortunately, the same thing will happen with every reporter. 😢

I would encourage you to submit an issue on the Newman project about exposing the details of the `sendRequest()` functions.
