### ISSUE TITLE
Summary total assertions wrapping value when total assertions over 1000

### ISSUE THREAD

**Issue by kenpulak** [DannyDainton/newman-reporter-htmlextra#179]
**Describe The Problem**
On the summary page, when the collection has over 1000 assertions the total assertion value is wrapping. I was unable to see how I can fix this locally since it appears the css is pulled from another site. Need to change the font-size from 6rem to 5.

**Steps To Reproduce**
Steps to reproduce the behaviour:

1. Run a collection with over 1000 successful assertions.

**What Are You Seeing**
![image](https://user-images.githubusercontent.com/52513242/74397204-1e07d980-4de2-11ea-9244-f37dda27dd63.png)

Changing the value in this screenshot in devtools from 6rem to 5 fixes the problem in the browser, I need to know how to make that change happen when report is built.
![image](https://user-images.githubusercontent.com/52513242/74398321-34636480-4de5-11ea-8ab3-005c0132775a.png)

**Version and Platform Information:**
 - newman --version  4.5.5
 - newman-reporter-htmlextra@1.11.1
 - OS Mac OS Catalina 10.15.3

**Additional Context**
Running the reporter from command line and from a script. Both produce the issue. I have seen times when some number combination over 1000 will fit with out wrapping, for example 1111. 

Sample command line:
newman run regression.json -e local.json -r cli,htmlextra --reporter-htmlextra-export "report.xml" --reporter-htmlextra-logs true

**Label**

**Comment by DannyDainton** [comment]
Thanks for reporting that @kenpulak - I did recently change the behaviour of those boxes when using large numbers and thought I'd fixed it 🤔

I'll get that sorted ASAP.

**Comment by DannyDainton** [comment]
Hey @kenpulak,

Totally my fault for not testing multiple scenarios when I adding my change 😢  

I pushed a fix for this issue - can you install v1.11.2 and confirm, please?

**Comment by kenpulak** [comment]
Wow, @DannyDainton thanks for the quick response. I installed 1.11.2 this morning and ran all of my collections that have over 1000 assertions. The all worked. Below are a couple of examples. Thanks again for the quick turnaround!

![image](https://user-images.githubusercontent.com/52513242/74430036-10764200-4e2a-11ea-99f1-5995d04dc427.png)

![image](https://user-images.githubusercontent.com/52513242/74430083-2d127a00-4e2a-11ea-997d-4123847c6dcd.png)

**Comment by DannyDainton** [comment]
@kenpulak You're welcome. 

It was my mistake in the first place, added something and didn't test it correctly :( There _should_ be room for 1 million now :) 

If you find anything else, please do raise an issue for it!! Thanks again!!
