### ISSUE TITLE
pagination :help on feature

### ISSUE THREAD

**Issue by kthulsidoss** [DannyDainton/newman-reporter-htmlextra#18]
Would you have an image of the test paging feature ? how to use them in the tests  -r htmlextra --reporter-htmlextra-export "$htmlfiledir\SIA_MFD_IntegrationTest_Report1.html"

Will this work

-r --reporter-htmlextra-testPaging`  "$htmlfiledir\SIA_MFD_IntegrationTest_Report1.html" meaning using paging and exporting the html file

**Comment by DannyDainton** [comment]
The command is the same as if you used the `darkTheme` or any other flag.

For example:

`newman run https://www.getpostman.com/collections/631643-f695cab7-6878-eb55-7943-ad88e1ccfd65-JsLv -r htmlextra --reporter-htmlextra-testPaging --reporter-htmlextra-export ./someExportFile.html`

**Comment by DannyDainton** [comment]
Closing this as it's not an issue with the reporter - more of an misunderstanding of the Newman commands.
