### ISSUE TITLE
Why undefined-* name is used by default?

### ISSUE THREAD

**Issue by ThePlenkov** [DannyDainton/newman-reporter-htmlextra#186]
Hi!

It's not like bug or feature. I just wanted to ask why undefined is used a default file name? Do you have any parameter for it? Thank you!

![image](https://user-images.githubusercontent.com/6381507/75364324-d8581000-58bb-11ea-9979-0b1d7f530577.png)

Thank you!

**Comment by DannyDainton** [comment]
Hey @ThePlenkov,

That's interesting, that would create that file if you don't specify an export location. It shouldn't be undefined though...that's strange.

Could you give me some more information about the `Newman` and `htmlextra` version's you're using, please? 

You can use `--reporter-htmlextra-export <filepath/filename.html>` in the command to create the report in the non-default location.

**Comment by ThePlenkov** [comment]
Now it explains)) I generate the collection myself with my module on top of SDK. https://github.com/ThePlenkov/newman-collection I might didn’t pass some name in the info I guess . Thanks

**Comment by DannyDainton** [comment]
Ah right, I will be adding something in place as a fallback though, this has the potential to happen again 😁
