### ISSUE TITLE
SUMMARY ITEM as per folder in Postman

### ISSUE THREAD

**Issue by ggpai** [DannyDainton/newman-reporter-htmlextra#189]
**Is your feature request related to a problem? Please describe.**
As of now when we get report, SUMMARY ITEM section contains overall Summary. Is that possible to get detail summary as per folder structure?

**Describe the solution you'd like**
 Is that possible to get detail summary as per folder structure? We are running collection with multiple folders in it. would like to know data w.r.t folder level. 

**Describe alternatives you've considered**

**Additional context**

**Comment by DannyDainton** [comment]
Hey @ggpai,

Could you give me an example of what you feel that might look like?

You're also able to use Custom Templates with the reporter so if the data is there from the Newman object, you could show anything you like :)

**Comment by ggpai** [comment]
![image](https://user-images.githubusercontent.com/35941785/77453374-6be60900-6db4-11ea-8bbf-11fdcf3cdf52.png)

We have collection divided in folders.Is that possible to get details in below table?

![image](https://user-images.githubusercontent.com/35941785/77453548-a2bc1f00-6db4-11ea-95b9-596a9b42ee56.png)

**Comment by DannyDainton** [comment]
It's not something that I'm planning to look at or into as I want to default template to be as generic as possible. 

The details you see on the Summary are coming straight from the Newman Object as will always be the overall summary for the Collection. An example of that can be seen below:

```
"run": {
      "stats": {
        "iterations": {
          "total": 1,
          "pending": 0,
          "failed": 0
        },
        "items": {
          "total": 1,
          "pending": 0,
          "failed": 0
        },
        "scripts": {
          "total": 1,
          "pending": 0,
          "failed": 0
        },
        "prerequests": {
          "total": 1,
          "pending": 0,
          "failed": 0
        },
        "requests": {
          "total": 1,
          "pending": 0,
          "failed": 0
        },
        "tests": {
          "total": 1,
          "pending": 0,
          "failed": 0
        },
        "assertions": {
          "total": 2,
          "pending": 0,
          "failed": 0
        },
        "testScripts": {
          "total": 1,
          "pending": 0,
          "failed": 0
        },
        "prerequestScripts": {
          "total": 0,
          "pending": 0,
          "failed": 0
        }
      }
```

The Total Requests view shows the details of the folders - That's created when looping through the data that comes from the Newman Object, there isn't a lot of logic behind that as it would make the template code harder to maintain.

A full example of what the Newman Object looks like can be found here:

https://gist.github.com/DannyDainton/8d673fd164d9040fed11b6026f5aa300

You could create your own template and look into this yourself to see what information is available, that can be displayed in any way you like. :)

**Comment by DannyDainton** [comment]
I'm going to close this as it's not something that I'm going to be doing and can be achieved (kind of) with a custom template. It's just finding the right details to aggregate from the folder level, they don't come through like the overall summary details so some level of logic will need to be added to expose that in the final report.
