### ISSUE TITLE
Show the console logs as a single non collapsing section

### ISSUE THREAD

**Issue by gstrantor** [DannyDainton/newman-reporter-htmlextra#190]
When I am viewing the console logs, each line cones as a separate collapsed section.
This make it tedious to go over all the logs. Therefore requesting that the logs appear as a single section with all log entries visible.

**Comment by DannyDainton** [comment]
Hey,

Pull Requests are welcome if you want to have a go at tackling this issue you're facing 😁

**Comment by DannyDainton** [comment]
This is a change that can be made in a custom template locally so I'm not going to be adding this at the moment, I will open up the issue again if I get round to tidying that up.

**Comment by DannyDainton** [comment]
@gstrantor The log message should now be part of the main request view. Update to v1.14.0 to see this.
