### ISSUE TITLE
Case-insensitive header skip

### ISSUE THREAD

**Issue by hakand** [DannyDainton/newman-reporter-htmlextra#192]
Hello,
Since HTTP headers are case-insensitive [(HTTP RFC)](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2), I believe `skipHeaders` feature should work in the same fashion. Current feature is case-sensitive.

**Comment by DannyDainton** [comment]
Hey @hakand,

Could you provide an example of where this is failing for you or has been causing you a problem please?

**Comment by hakand** [comment]
Hey @DannyDainton,

I might have 2 requests in a collection each has an `authorization` header. However, let's say in one of them it is `authorization`, and in the other one it is `Authorization`. Those are treated as different headers when it comes to `skipHeaders` feature, because of the case-sensitivity.

**Comment by DannyDainton** [comment]
That's fair but are you looking to solve the inconsistencies in the requests, with an output report though? 

If you wanted to get a PR together for this, I would be happy to have a look at it. It's either that or I'll be getting to this when I had some time. :)

**Comment by DannyDainton** [comment]
Added this to v1.13.0

**Comment by DannyDainton** [comment]
Reopening this as the version I pushed wasn't tested enough and a blocking bug fell out of it - I will add this back in very soon.

Added tests to alert me of any issues with this in the future.

**Comment by DannyDainton** [comment]
Fix and Tests added to v1.13.2.
