### ISSUE TITLE
Strange style with default dashboard

### ISSUE THREAD

**Issue by pingwin4ik** [DannyDainton/newman-reporter-htmlextra#199]
**Describe The Problem**
Strange style with default dashboard in Jenkins!

**Screenshots and Gifs**
![image](https://user-images.githubusercontent.com/25619978/80609162-75f8c880-8a40-11ea-94d0-7f47c554b6df.png)

**Version and Platform Information:**
pstauffer/newman-htmlextra:latest

**Comment by DannyDainton** [comment]
Hey @pingwin4ik,

I believe this is a Jenkins configuration issue rather than an issue with the reporter. I've seen similar people report similar things in the past, I would need to check through the issue to see how this was resolved.

**Comment by DannyDainton** [comment]
@pingwin4ik This was the issue I was talking about - Are you able to take a look through the thread and see if that works for you too.

https://github.com/DannyDainton/newman-reporter-htmlextra/issues/45

**Comment by DannyDainton** [comment]
@pingwin4ik Did this solve the issue for you?

**Comment by pingwin4ik** [comment]
not yet checked
If we make the CSP changes it can perhaps crash our Jenkins

**Comment by DannyDainton** [comment]
I'm going to close this issue as it doesn't really have anything to do with the functionality of the reporter.
