### ISSUE TITLE
DataTables warning displayed when viewing reports

### ISSUE THREAD

**Issue by meekkaal** [DannyDainton/newman-reporter-htmlextra#20]
**Describe the bug** 

When viewing a report, a DataTables warning is displayed for each 'table id'

**Steps to reproduce**

1. Execute Collection with htmlextra as the reporter
2. View the generated report in a web browser
* Notice consecutive warnings are displayed:
> DataTables warning: table id={table id}- Cannot reinitialise DataTable. For more information about this error, please see http://datatables.net/tn/3

**Screenshots**

![image](https://user-images.githubusercontent.com/23304838/54387711-74204a00-4672-11e9-820e-cf738d220709.png)

**Version and Platform Information:**

    newman Version 4.4.0
    newman-reporter-htmlextra Package Version 1.6.6
    OS Windows 10 1803

**Additional context**

- Running from the command line
- Running a Collection with multiple iterations based on a data file

**Label** Bug

**Comment by DannyDainton** [comment]
Thank you for submitting this, I will take a look and get back to you with some further information.

**Comment by meekkaal** [comment]
I'm going to dig a bit further into it when I get a chance as well.

Thanks for making this great reporter!

**Comment by DannyDainton** [comment]
You're welcome.

I had a similar problem locally I think and I didn't commit a potential fix. 😔

I'm away from my laptop at the moment but I can get a new version out tomorrow that will hopefully stop this issue. 

It's basically adding in another property to the Datatables object in the .hbs file. 

Check out the `retrieve` option for. More details. 

https://datatables.net/manual/tech-notes/3

Will fix this as soon as I can. 😁

**Comment by DannyDainton** [comment]
@meekkaal I've published a new version, would you be able to update and check to see if it's still doing the same thing please.

The tests that I ran locally, after reproducing the problem, are looking good but it would be great to have your feedback :)

**Comment by meekkaal** [comment]
I updated and tested this on two machines and the issue seems to be resolved. Thanks for the quick turnaround and all your work on this!

**Comment by DannyDainton** [comment]
Cool - That's good news. It was something that I was aware of and had a `fix` locally but didn't actually commit this change. :(

Thank you so much for bringing it to my attention. My bad for putting it in there in the first place :(

Appreciate you raising the issue and thank you for using the reporter!! ❤️
