### ISSUE TITLE
Hide Response for specific named request

### ISSUE THREAD

**Issue by PeterSulcs** [DannyDainton/newman-reporter-htmlextra#210]
**Is your feature request related to a problem? Please describe.**
I have a postman collection of requests, the first request gets a bearer token which comes back in the response body and is saved to the environment for later API requests. I want to show the request and response for every request **except** this one since the bearer token is sensitive.

**Describe the solution you'd like**
`newman run postman_collection.json -e postman_environment.json --reporters cli,htmlextra --reporter-htmlextra-export ./newman/roundtrip/index.html --reporter-htmlextra-omitHeaders --reporter-htmlextra-hide-response "OAuth2 login"` where

`--report-htmlextra-hide-response` is the proposed additional argument. and "OAuth2 login" is the name of my request where I want to hide the response.

**Describe alternatives you've considered**
Perhaps there is some label that can be added to the test information within the Postman collection (either in Postman or directly in the JSON). That the reporter can honour.

**Additional context**
I'm really hoping this already exists, but I haven't been able to find it anywhere in the issues or through Googling. I did find this non-answer here, which was closed for being private, but obviously is not private since I found it using Google. :) 

https://community.postman.com/t/how-to-hide-response-body-while-running-collection-in-newman-report/9126

**Comment by DannyDainton** [comment]
The non-answer was from me 😁 - we had a chat via direct message but there wasn't really a solution. 

I've played around with trying to hide specific responses and various levels of success. Might need to revisit that again.

I'm accepting PRs so if you have a proposed coded solution you can send it over 😁

**Comment by DannyDainton** [comment]
When you say `test`, you mean request right?

The `test` wouldn't have a response body, it would have a pass, skipped or failed state.

**Comment by PeterSulcs** [comment]
Yeah, I meant `request`. The way my collection is arranged it is one to one `request` to `test` but realize that isn't the correct nomenclature. Thanks for the prompt response, as far as making a PR, I'll take a look this weekend.

I think I can probably hide the call to get the token in a Pre-request script, so I'll plan to do that as an immediate workaround.

**Comment by DannyDainton** [comment]
@PeterSulcs - I've found that I can hide a specific folder(s) or hide _all_ the response bodies but not a specific one....yet.

I just need to clear some time and think about it a bit more - I'm sure there is an easy way to do it but I can't get my head around it just yet. 😢  

I'm on the case though - I did want to add more flexibility for doing things like this in the reporter but I didn't plan on doing it right now 😄

**Comment by DannyDainton** [comment]
Hey @PeterSulcs,

I've added in a new flag `--reporter-htmlextra-hideResponse` that should hopefully help you to hide that response.

`newman run postman_collection.json -e postman_environment.json --reporters cli,htmlextra --reporter-htmlextra-export ./newman/roundtrip/index.html --reporter-htmlextra-omitHeaders --reporter-htmlextra-hideResponse "OAuth2 login"`

Let me know if that works 😄

**Comment by PeterSulcs** [comment]
Wow! I will test this out. Thank you!

**Comment by DannyDainton** [comment]
You're welcome 😁
