### ISSUE TITLE
[Feature Request] Render links from the test title or assertion

### ISSUE THREAD

**Issue by vdespa** [DannyDainton/newman-reporter-htmlextra#233]
**Is your feature request related to a problem? Please describe.**
For failing tests, it would be nice to link an existing bug report (URL). 

**Describe the solution you'd like**
The possibility of rendering links in the report: 

```
pm.test("Status code is 201", () => {
    pm.expect(1).to.eql(2, "[This link](http://example.com/) lorem ipsum.");
});
```

**Additional context**

The link is not clickable.
![image](https://user-images.githubusercontent.com/1197635/84092982-38c81480-a9b6-11ea-9a32-0ce4ea0f1d8d.png)

**Comment by DannyDainton** [comment]
Hey @vdespa,
That's a great suggestion and I'm sure it would be useful for lots of folks. On the face of it, I think it would be easy to do as I already use remarkable to render the Markdown from Collections and Request descriptions.

The Markdown in the test failures would look like this in the report:

![Screenshot 2020-06-09 at 07 30 59](https://user-images.githubusercontent.com/17089546/84115619-41583380-aa26-11ea-9bc7-ab5499168670.png)

<img width="978" alt="Screenshot 2020-06-09 at 07 53 49" src="https://user-images.githubusercontent.com/17089546/84115693-62b91f80-aa26-11ea-893b-8fc7336a62d3.png">

The things that I'm concerned about at the moment is that it has the potential to unintentionally changing other parts of that failure string to Markdown. I need to have a think about some sort of parser to only transform just the link syntax. Or maybe put it behind a flag, to not be such a wide change to the output report.

**Comment by DannyDainton** [comment]
I've created a new version and added a `--reporter-htmlextra-showMarkdownLinks` that will render the URLs added to the test names or in the `pm.expect()` statements.

![Screenshot 2020-06-09 at 09 45 31](https://user-images.githubusercontent.com/17089546/84137027-0238db00-aa44-11ea-878d-0087bd554286.png)

Let me know if that's what you're after. :)

**Comment by vdespa** [comment]
Looks fantastic, @DannyDainton 
Yes, not making that default may be a good idea, at least in the beginning.

**Comment by DannyDainton** [comment]
I'm going to close this one now by let me know if you get any issues. 😁
