### ISSUE TITLE
[Feature Request] Add Expand-all button to the Failed-tests and Skipped-tests panes

### ISSUE THREAD

**Issue by BubuFS** [DannyDainton/newman-reporter-htmlextra#235]
Add Expand-all button to the Failed-tests and Skipped-tests panes, to expand everything on the pane at once. Similar to what is on the Total-requests pane, top-right. And thanks, luv this tool!

**Comment by DannyDainton** [comment]
Hey @BubuFS,

I had been meaning to do this for a while but no one asked so I let it fall down in the list of things to do....but now you have asked.... :D 

How about this...

![Expand_All_The_Things](https://user-images.githubusercontent.com/17089546/85546475-d6595000-b614-11ea-8819-f85ce617c670.gif)

**Comment by DannyDainton** [comment]
Added the changes to the v1.16.1 version, let me know if that's what you mean 😄
