### ISSUE TITLE
[Feature Request] Would it be possible to have a docker file for this

### ISSUE THREAD

**Issue by cmwaura** [DannyDainton/newman-reporter-htmlextra#237]
**Is your feature request related to a problem? Please describe.**
Having a dockerfile will literally less ramp up time for a developer to test this product and pitch it to the team. 

**Describe the solution you'd like**
A dockerfile that i can build and run locally

**Describe alternatives you've considered**
the current build process. Just dont like building it with npm.

**Comment by DannyDainton** [comment]
Hey @cmwaura,

I purposely didn't create one after seeing that @pstauffer had already made this one:

https://github.com/pstauffer/docker-newman-htmlextra

Would this work for you?

**Comment by DannyDainton** [comment]
I've also created a docker image - https://hub.docker.com/repository/docker/dannydainton/htmlextra

Let me know if this helps.

**Comment by DannyDainton** [comment]
Closing this and the Docker image has been created and published.
