### ISSUE TITLE
[Question] How can I run Newman from the command line?

### ISSUE THREAD

**Issue by svarshney2311** [DannyDainton/newman-reporter-htmlextra#238]
Good day. 
I am new to run Newman. 
COuld you please tell the steps to execute below command:
like if this code has to update anywhere than run command line or ??

```
const newman = require('newman'); // require newman in your project

// call newman.run to pass options object and wait for callback
newman.run({
collection: require('./sample-collection.json'),
reporters: 'cli'
}, function (err) {
if (err) { throw err; }
console.log('collection run complete!');
});
```

I have this code but don't know what to do next?

**Comment by DannyDainton** [comment]
Hey @svarshney2311 ,

This isn't the repo for Newman, that would be https://github.com/postmanlabs/newman

I'm not sure what you're trying to do - Are you just trying to run a Postman collection with Newman from the CLI?

- https://github.com/postmanlabs/newman#getting-started

Once you have installed Newman on your machine, the command would be something like this:

`newman run https://www.getpostman.com/collections/631643-f695cab7-6878-eb55-7943-ad88e1ccfd65-JsLv`

**Comment by svarshney2311** [comment]
Could you please share the **steps** to execute Newman as Library in a Nodejs script.

const newman = require('newman'); // require newman in your project

// call newman.run to pass options object and wait for callback
newman.run({
collection: require('./sample-collection.json'),
reporters: 'cli'
}, function (err) {
if (err) { throw err; }
console.log('collection run complete!');
});

**Comment by DannyDainton** [comment]
Something like that I just:

- Create a new dir
- `cd` to the new dir
- Run `npm init`
- Install Newman using `npm i -S newman`
- Create a new js file and add that script
- Run the js file using `node <filename>.js`

**Comment by DannyDainton** [comment]
This isn't really a specific question about the htmlextra reporter, more of a general how do a create a node project.

I'm going to close this issue.
