### ISSUE TITLE
Question about approach

### ISSUE THREAD

**Issue by wonboyn** [DannyDainton/newman-reporter-htmlextra#24]
Hi there,
 Apologies in advance, as this is more of a generic Postman/Newman question rather than regarding your reporter...

I have a requirement to distinguish three different outcomes for a request:
- success => all tests have been successful
- warning => all tests have been successful **AND** a specific value has been returned (eg header ABC is provided in the response)
- fail => a test fails

Do you have any recommendations on how I could tackle this?

Thanks in advance.

Tim

**Comment by DannyDainton** [comment]
Hey @wonboyn 

Thanks for reaching out - I'm not entirely sure what you're after though. That requirement can be met but it all depends how you would like to present that data.

All 3 of those things can be exposed in a number of different ways, I'm going to need more information to help you further though.

If you want to send me this information via email to dannydainton@gmail.com, that would be cool. I can then close out the issue as it's not really a `htmlextra` reporter specific.  

Danny
