### ISSUE TITLE
Option to record request and response body only for fail cases

### ISSUE THREAD

**Issue by vhrsh** [DannyDainton/newman-reporter-htmlextra#242]
**Is your feature request related to a problem? Please describe.**
I run a collection which has around 10k test cases. A HTMLExtra Report for this would be a huge size and would not be possible and feasible

**Describe the solution you'd like**
option to record pass and failure cases individually. here, we can record only the failure cases specifically

**Describe alternatives you've considered**

**Additional context**

**Comment by DannyDainton** [comment]
Hey @vhrsh

Would the `showOnlyFails` flag work for you or are you after something different?

**Comment by vhrsh** [comment]
> Hey @vhrsh
> 
> Would the `showOnlyFails` flag work for you or are you after something different?

Hey @DannyDainton 
i presume the showOnlyFails will not show any pass results. This would be detrimental as we may not know the total size of the run right?

Example:
Suite: 10000 test cases
Passed: 9995 tests
Failed: 5 Tests

Ideally, what i was exploring was
1. If Pass, only the status would be enough (no request and response body and headers captured)
2. If Fail, capture all details (request body and headers, response body and headers)

I apologize, i have not yet used the showOnlyFails. If you can suggest if it indeed works as i want, then i can try and revert.

**Comment by DannyDainton** [comment]
That flag will still run all the requests in your collection but only display the information for the requests that failed during the run.

The requests that passed wouldn't be shown. It's worth trying it out to see if that suits your need.

**Comment by DannyDainton** [comment]
Hey @vhrsh,

Did that work for you?

**Comment by vhrsh** [comment]
> Hey @vhrsh,
> 
> Did that work for you?

Danny, I haven't tried it out. However, the use case would be my some technical staff who would want to check the reason for failures. the showOnlyFails would work to show only 5 failed but not the overall test runs.

To put things in perspective, i ran a test with 106 iterations with ~6500 test cases. I used the --reporter-htmlextra-skipSensitiveData. The resulting file was 23MB. In the long run of running this on github actions, the reports would take up a large space. Hence, the query raised.

**Comment by DannyDainton** [comment]
Like I mentioned - The report is deterministic based on the sized of the Collection and the number of iterations. If it's a large collection with lots of tests, the report will be large.

Come's back to who is reading the report, who is interested in flicking through 106 iterations and ~6500 test cases on a semi-static HTML report. In that occasion, you just need the highlights. Maybe the choice of a rich HTML report isn't what you need here.

**Comment by vhrsh** [comment]
> Like I mentioned - The report is deterministic based on the sized of the Collection and the number of iterations. If it's a large collection with lots of tests, the report will be large.
> 
> Come's back to who is reading the report, who is interested in flicking through 106 iterations and ~6500 test cases on a semi-static HTML report. In that occasion, you just need the highlights. Maybe the choice of a rich HTML report isn't what you need here.

Done. Thanks for indulging. :)
