### ISSUE TITLE
[Question] pm.expect is not validating all the assertions.

### ISSUE THREAD

**Issue by svarshney2311** [DannyDainton/newman-reporter-htmlextra#245]
Hi,

I have below Tests in my scripts. There are 4 validation in my Tests. 
My requirement is, I wanted to test all 4 validation before sending any result. example if paymentMethod_Type fails: I still want to test paymentMethod_Last4digits  and send the results for all 4.

Currently, if any of the validation is failing , it is stopped there and sending report, its not testing any further validation after failure one.

Could you please suggest the solution as it is highly required.

Note: I dont want to use  pm.test for each validation as it will increase my result count.

```javascript
var jsondata = pm.response.json();

pm.test("Verify the Status  and Payment Method : " + (pm.response.status) , function () {
    pm.response.to.have.status(200);
    pm.expect(jsondata.autoPay.paymentMethod.brand).to.equal(pm.environment.get("paymentMethod_Brand"));
     pm.expect(jsondata.autoPay.paymentMethod.type).to.equal(pm.environment.get("paymentMethod_Type"));
     pm.expect(jsondata.autoPay.paymentMethod.lastFourDigits).to.equal(pm.environment.get("paymentMethod_Last4digits"));
});
```

**Comment by DannyDainton** [comment]
I'm not sure what you want me to do about this.

All the assertions are in one test, if one fails, the test fails. It sounds like it's doing what it's supposed to do. Or am I missing something?

You would see the same using the CLI reporter or any other reporter, this isn't specific to htmlextra.

Why is the test failing? Have you looked into that?

You could wrap tests in `try/catch` block I guess but ultimately if your test are failing for a _reason_, you should probably be investigating that first.

**Comment by svarshney2311** [comment]
I have purposefully failed one assertion .

so here what I am looking is if say 2nd assertion is failing , its not looking for 3 rd assertion and throwing error.

I want to test all the assertion before its failed. Hope you understood what I am looking.

trying again, if some reason 2 nd 3rd failed, I should get details for both the assertion but I am getting the details only for first one.

**Comment by DannyDainton** [comment]
This is not a specific htmlextra issue it's a test design problem that you would encounter in the Postman app.

Closing this as it's not something that I can change in the reporter to make work for you.
