### ISSUE TITLE
Failed Request count is always zero - even if an Request had assertion errors

### ISSUE THREAD

**Issue by svarshney2311** [DannyDainton/newman-reporter-htmlextra#246]
When assertions within an Request fail, I expect the Request fail count to increase. Instead, it remains at 0.
This way, I cannot count successful Requests, only "run" Requests. 

![image](https://user-images.githubusercontent.com/66395814/86502074-3c5c7a80-bd6d-11ea-95d5-4a3822af131c.png)

![image](https://user-images.githubusercontent.com/66395814/86502083-4bdbc380-bd6d-11ea-9399-d2a23a556dea.png)

**Comment by DannyDainton** [comment]
That number relates to the number of assertions that have failed - As you can see from your image, the number on the failed assertions, matches the total in the tab.

**Comment by svarshney2311** [comment]
But the requirement is If any assertion fails, Test Requests should be failed as assertion link to the Test Request.
Here in the example, even the assertion is failed but still Test Requests showing as passed,that looks something odd and this issue had raised by Client also.

**Comment by DannyDainton** [comment]
Who's requirement? 🤔

I'm telling you, from the person who created the reporter and the logic behind why things show up in different parts of the app - Also from someone who knows a few things about the way Postman works...it's doing what I expect it too 😁

How many assertions failed? It looks like 1 and 1 was placed in the label at the top. 

A test failing doesn't equal a request failing, a request can fail without a it even having a test within it.
