### ISSUE TITLE
Using handlebars-helpers function in template

### ISSUE THREAD

**Issue by wonboyn** [DannyDainton/newman-reporter-htmlextra#25]
Hi,

Newbie question. I want to use the math minus function provided by handlebars-helpers but am struggling to understand how to do so.

I tried {{#minus stats.items.total stats.items.failed}} but this results in an exception that "minus doesn't match..."

Could you please explain what I need to do to use the functions provide by handlebars-helpers?

Thanks

Tim

**Comment by DannyDainton** [comment]
Hey,

Handlebars is tricky to get used to so I know where you're coming from Tim. 

So because it's a `block` helper, you need to close it out again. You can do this by using `{{/minus}}` at the end of the `{{#minus stats.items.total stats.items.failed}}`

Hope that makes sense.

**Comment by DannyDainton** [comment]
Closing this out as its not really an issue with the reporter.
