### ISSUE TITLE
[Bug] The theme toggle does not display the report in Dark mode on IE Edge

### ISSUE THREAD

**Issue by srinivasskc** [DannyDainton/newman-reporter-htmlextra#250]
**Describe The Problem**
When i open the report on IE Edge and Click on Dark Mode toggle, It does display the report in dark mode.

**Steps To Reproduce**
1. Run the collection 'newman run APITesting.postman_collection.json -r htmlextra'
2. Open the report 'file:///C:/development/postman-api-testing-collection-1/newman/API%20Testing-2020-07-21-03-38-36-833-0.html'
3. Select the `Request` view 'Dark Mode'

**What Are You Seeing**
It displays the same report when Light Mode or Dark Mode is selected. No Background color changed.

**Screenshots and Gifs**
![image](https://user-images.githubusercontent.com/26836928/88010639-fb1ce680-cb32-11ea-8798-9267ae1ce341.png)

**Collection and Environment Files**
Environment: Windows 10
Browser: IE Edge latest version
Collection: Any Collection

**Version and Platform Information:**
 - `newman` Version [6.14.6]
 - `newman-reporter-htmlextra` Version [1.17.3]
 - OS [Windows 10]

**Additional Context**
- Are you using the reporter from the command line or with a script?  Command Line.

- Are you using the default template or a custom version?  Default Template

**Comment by DannyDainton** [comment]
Thanks for writing in! 🏆

Could you confirm the Newman version please @srinivasskc, that doesn't look quite right.

If you could share the node version too that would be great.

**Comment by srinivasskc** [comment]
Below are details @DannyDainton .

Node Version: 12.18.2
![image](https://user-images.githubusercontent.com/26836928/88019109-a5523980-cb46-11ea-84f5-cd4079cc88d2.png)

NPM Version: 6.14.6
![image](https://user-images.githubusercontent.com/26836928/88019134-b69b4600-cb46-11ea-94f2-6002e5efefed.png)

Newman Version: 5.1.0
![image](https://user-images.githubusercontent.com/26836928/88019211-e9ddd500-cb46-11ea-99e5-ea7c76626fdb.png)

There is an error while executing this function while launching the report (either in light or dark mode).
`(function () {
            if (localStorage.getItem('theme') === 'theme-light') {
                setTheme('theme-light');
                document.getElementById('slider').checked = false;
            } else {
                setTheme('theme-dark');
                document.getElementById('slider').checked = true;
            }
        })();`

Console Log Screenshot:
![image](https://user-images.githubusercontent.com/26836928/88018751-f7df2600-cb45-11ea-95d6-a04466e733fa.png)

![image](https://user-images.githubusercontent.com/26836928/88018809-104f4080-cb46-11ea-8732-9c3a8857bd74.png)


No data is stored in Storage
![image](https://user-images.githubusercontent.com/26836928/88019299-1560bf80-cb47-11ea-8b82-a255dd4e1db3.png)

**Comment by DannyDainton** [comment]
There seems to be a lot of issues over the years with local storage and Edge. Even the latest update here was from last month :/ 

https://stackoverflow.com/questions/34798285/how-can-i-open-a-local-html-file-in-microsoft-edge-browser

**Comment by DannyDainton** [comment]
Just to confirm @srinivasskc - Apart from the report not flipping over to the Dark theme, is the rest of it functional? 

Just want to ensure there isn't any other quirks of Edge that I haven't accounted for/seen yet. :(

**Comment by srinivasskc** [comment]
Thanks for asking.
I found a functionality issue.

Response Information is not displaying on IE Edge, whereas it displays information on Chrome.
![image](https://user-images.githubusercontent.com/26836928/88124642-3a0e7300-cbeb-11ea-84eb-3bdcfbbb55f0.png)

**Comment by DannyDainton** [comment]
Interesting 🤔

Might need a little bit more info that a static image of something that you can see on your machine though 😁

Any errors? Could you check the elements in the dev tools to see if it's just a CCS thing? 

Could you share the collection files with me please?

**Comment by srinivasskc** [comment]
I have checked further, its more of CSS. 

![image](https://user-images.githubusercontent.com/26836928/88135971-e6f5e980-cc05-11ea-8b24-2e1551bdf641.png)

class .badge-success
{ color: #fff } which is strike off. 

When i unchecked the property, Now values are displaying.

![image](https://user-images.githubusercontent.com/26836928/88136066-20c6f000-cc06-11ea-9e5c-cbdf52e4bc69.png)

The same css property when strike off, it is displaying values on chrome. @DannyDainton

**Comment by DannyDainton** [comment]
Yeah I thought it all might be wrapped up with the CSS issues from the toggle changes.

I'm sure there will be more on Edge and to save you posting each one I would recommend not using that browser with the reporter. 😢

**Comment by srinivasskc** [comment]
You can close this ticket :) And also it would be good to see if you can add "Browser Compatability" in Readme file.

**Comment by DannyDainton** [comment]
Sounds like a great way to contribute to the project and get your name on it too.

If you makes the changes to the readme and send me a PR I will get it merged 😁

**Comment by DannyDainton** [comment]
@srinivasskc I'm going to close this for now but please do raise a PR for changes to the README, I would appreciate your contributions.
