### ISSUE TITLE
[Feature Request] Extra info when calling one or more folders, instead of a whole collection?

### ISSUE THREAD

**Issue by BubuFS** [DannyDainton/newman-reporter-htmlextra#251]
In "FILE INFORMATION" box, perhaps we can add "Folders: f1, f2" under Collection, when one or more test-run folders are specified. Should be easy!

Likewise, in such cases, "COLLECTION DESCRIPTION" section could be replaced or supplemented with the relevant text from the Folders descriptions, as in general, the collection description text is redundant when folders are used.

**Comment by DannyDainton** [comment]
> In "FILE INFORMATION" box, perhaps we can add "Folders: f1, f2" under Collection, when one or more test-run folders are specified. Should be easy!

PRs are always welcome - should be easy :D

> the collection description text is redundant when folders are used.

Even if you're running a single/multiple folders, you're still running those from a Collection so it seems quite relevant :D

**Comment by BubuFS** [comment]
Hi Danny. Yes, redundant is relative, depends on what is in one's descriptions; what I meant was, for our use-case, the collection-level description is not as relevant as the folder-level description. You might need to use some judgement for that last part...

**Comment by DannyDainton** [comment]
The key part to that is _for our use-case_ - It's a generic report and it's also a template which can be modified and used in any way you like, for specific use cases.

If you don't want something to be there, remove it, create a new template and use that with `--reporter-htmlextra-template <path to template>`- simple :D

**Comment by DannyDainton** [comment]
I'm thinking of adding this so it shows the folder descriptions if the folder has any:

<img width="1088" alt="Screenshot 2020-07-22 at 18 52 41" src="https://user-images.githubusercontent.com/17089546/88210767-9786dc00-cc4c-11ea-873a-d7079ba2090f.png">

**Comment by DannyDainton** [comment]
Potentially something like this for when the `folder` option is used:

<img width="1203" alt="Screenshot 2020-07-22 at 20 12 02" src="https://user-images.githubusercontent.com/17089546/88218222-a6bf5700-cc57-11ea-8251-f336868618c1.png">

**Comment by DannyDainton** [comment]
Added to the 1.17.4 version
