### ISSUE TITLE
Very slow to navigate from one request to another on large reports

### ISSUE THREAD

**Issue by svarshney2311** [DannyDainton/newman-reporter-htmlextra#254]
I have more than 1500 request. When I opened HTMLEXTRA report, it is very slow to navigate from one request to another.
Is there any way , we can work on the performance of report if has large number of test rquests.

Its really frustrating to me when I investigate any issue in the report because of slowness.

![image](https://user-images.githubusercontent.com/66395814/90193679-702ab700-dd93-11ea-9ef7-a31d711573f8.png)

**Comment by DannyDainton** [comment]
The output report is a dynamically created static file, the more data your using, the bigger the report will be. 

Thousands of iterations, requests, tests etc will cause the report to be huge - that's not going to change. 

I get this a lot and I ask who the report is for and does is that person interested in looking through a detailed report, containing 1600+ requests. Do they need that level of detail or do they just want the big number information? 

The reporter has several different flags to cut down the information, if it's really not needed. Try experimenting with these. 

This one will help with the performance and its not doing syntax highlighting on all the response bodies. 

`--reporter-htmlextra-noSyntaxHighlighting`

**Comment by DannyDainton** [comment]
This isn't something that I'm going to be actively working on right now, all PRs are very welcome though, if you have an idea about how to deal with this.

I'm going to close this on out now and add a ticket in my backlog.
