### ISSUE TITLE
[BUG] "Cannot read property 'length' of undefined" while generating htmlextra report

### ISSUE THREAD

**Issue by ionutapostol** [DannyDainton/newman-reporter-htmlextra#262]
**Describe The Problem**
Getting an error while attempting to generate an htmlextra report.

**Steps To Reproduce**

1. Go to your project folder and run the following command in a terminal of your choice:
newman run "./test_collection.postman_collection" -e "./test_env.Postman.postman_environment" -r "cli,json,htmlextra" --reporter-htmlextra-template "./dashboard-template.hbs" --reporter-htmlextra-export "./test-report.html" --reporter-json-export "./test-report.json" --insecure
2. Check the command line report.

**Result:**
C:\Users\...\AppData\Roaming\npm\node_modules\newman-reporter-htmlextra\lib\index.js:124
        else if (list.length !== undefined) {
TypeError: Cannot read property 'length' of undefined

![Annotation 2020-08-25 162350](https://user-images.githubusercontent.com/46417725/91179696-629bf800-e6d6-11ea-82f3-a45b436d5d8e.png)

[test_env.Postman.postman_environment.json.txt](https://github.com/DannyDainton/newman-reporter-htmlextra/files/5123967/test_env.Postman.postman_environment.json.txt)
[test_collection.postman_collection.json.txt](https://github.com/DannyDainton/newman-reporter-htmlextra/files/5123968/test_collection.postman_collection.json.txt)

[dashboard-template.hbs.txt](https://github.com/DannyDainton/newman-reporter-htmlextra/files/5123972/dashboard-template.hbs.txt)

**Screenshots and Gifs**
Please see attached

**Collection and Environment Files**
Check the samples please.

**Version and Platform Information:**
 - `newman` Version 5.1.2
 - `newman-reporter-htmlextra` Package Version 1.19.0
 - OS [Windows 10]

**Additional Context**
It seems to be a regression. It worked fine with newman-reporter-htmlextra v.1.17.4

- Are you using the reporter from the command line or with a script?
Yes 
- Are you using the default template or a custom version?
A custom version.
- If you are using a custom `.hbs` file, please include this on the report.
See attached.
- Have you made any local changes to the `index.js` file?
No

**Comment by DannyDainton** [comment]
Hey @ionutapostol 

I've added some more features and updated the templates used by the reporter - If you remove the ` --reporter-htmlextra-template "./dashboard-template.hbs"` is it working?

**Comment by ionutapostol** [comment]
Hi, @DannyDainton 

Yes, it's working and I cannot see my report numbers there as the template is excluded (as expected).

As a side note, I'm not using the stock template, I did minor changes to it before running it in the command line (please check attachment).

So, should I get the latest template and add my changes and give it another try? That's something I can do.

Thanks!

**Comment by DannyDainton** [comment]
Yeah I saw that - I would give it a different name, just to save confusion next time 😄 

I took a look at your template and I _think_ you should just be able to change line `1026` to this:

```
{{#isNotIn item.name @root.hideResponseBody}}
```

![Screenshot 2020-08-25 at 15 55 04](https://user-images.githubusercontent.com/17089546/91190351-65551800-e6eb-11ea-9878-562afb59a700.png)

**Comment by ionutapostol** [comment]
I did the change and now it's working just fine. Thanks for all your support and sorry for the bad file naming. :)

I guess we can close the issue. Thanks again! 👍

**Comment by DannyDainton** [comment]
That's cool - Glad to get you unblocked. 

I'm really interested in what you're doing with the reporter - would you be able to share an image of what the full run looks like? Always nice to see different use cases.

I'm going to take a better look at things are see if I can mitigate against the error happening again :(
