### ISSUE TITLE
Console Log Issue -newman-reporter-htmlextra v1.17.3

### ISSUE THREAD

**Issue by josephthanaraja** [DannyDainton/newman-reporter-htmlextra#263]
We recently upgraded the newman-reporter-htmlextra version to 1.17.3 and console logs not coming into the report. Previous report had a separate tab to show the logs and understand we moved that as part of each request now. But that is not happening with this version. Can you please help.

Newman version : 1.5.2
newman-reporter-htmlextra Version : 1.17.3

**Comment by DannyDainton** [comment]
Hey @josephthanaraja 

What's the command that you're running?

To see the logs you would need to use `--reporter-htmlextra-logs` as these are now _off_ by default.

**Comment by josephthanaraja** [comment]
Thank you for your quick response, I am using this --reporter-htmlextra-logs in my newman command using 1.17.3 version but no luck. Still do I need to upgrade to 1.19.0 version to see the console log?

newman run dataCollection.json -d collection.json -x  -r cli,htmlextra --reporter-htmlextra-export report.html --reporter-htmlextra-logs --reporter-htmlextra-title 'MyDashboard' --reporter-htmlextra-browserTitle 'Workflow Dashboard' --reporter-htmlextra-template /newman/package/sre-dashboard-template.hbs

**Comment by DannyDainton** [comment]
You're using a custom template so unless you. have amended that since the logs changes were made, it's not going to show. 

All changes would be reflected in the standard default report template.

Custom templates could contain literally anything so I can't really assure that it's going to be showing the features that's I've added into the reporter 😄

**Comment by josephthanaraja** [comment]
Ok thanks for the findings, I will try with the above option and update here.

**Comment by DannyDainton** [comment]
Can you share the template file with me, that would be an easier way of me seeing where the issue is 😁

**Comment by josephthanaraja** [comment]
Thank you so much for you immediate help, It worked after integrating the latest changes in my custom template. WE are good to close this issue.

**Comment by josephthanaraja** [comment]
Much Appreciate it!.
