### ISSUE TITLE
[BUG] Console Log tab is not coming into the report when using Newman as a NodeJs library

### ISSUE THREAD

**Issue by BeingRitam** [DannyDainton/newman-reporter-htmlextra#266]
**Console tab is not coming into the report when using Newman as a Node Js library**

I am using Newman in my Nodejs project along with newman-reporter-HTML extra and reporter. Till v `1.9.2 (html-extra reporter), newman 4.5.7`, I was able to see the console logs in the report while passing logs flag as true in the NewmanRunOption.
after upgrading `^1.19.0  (html-extra reporter) and newman (4.6.1)`, Console logs are not showing in the report but in CLI, I can still see the console logs are getting printed.

**Steps To Reproduce The Issue**
```
//Set Newman run option
const newmanOption: NewmanRunOptions={
	collection: 'some_collection.json',
	environment: 'JSON_represneting_key_value_for_env.json',
	folder: ['Folder1', 'Folder2'],
	reporters: ['cli','htmlextra'],
	reporter: {
		htmlextra: {
			skipHeaders: [array_of_strings_to_ommit],
			logs: true,
                        export: './Report.html'
		}
	}
}

//Trigger Newman
newman.run(newmanOption, (err)=> {
			if (err) { throw err; }
	})
	.on('start', (err, summary)=> { // on start of run, log to console
			progressStreamingService('start', summary);
	}).on('done', (err, summary)=> {
			if (err || summary.error) {
					console.error('collection run encountered an error.');
			}
			else {
					progressStreamingService('done', summary);
			}
	}).on('beforeItem', (err, summary)=>{
			progressStreamingService('beforeItem', summary);
	}).on('beforeIteration', (err, summary)=>{
			progressStreamingService('beforeIteration', summary);
	}).on('console', (err, summary)=>{
			progressStreamingService('console', summary);
	}).on('assertion', (err, summary)=>{
			progressStreamingService('assertion', summary);
	});
}
```
**Screenshots and Gifs**
![Console Logs printing in CLI](https://user-images.githubusercontent.com/26964099/92258285-37927f00-eef4-11ea-8333-1420b216b02f.png)

**Collection and Environment Files**
[Final Report with no console tab](https://github.com/DannyDainton/newman-reporter-htmlextra/files/5175812/Report_1599234696757.zip)

**Version and Platform Information:**
 - `newman` ^4.6.1
 - `newman-reporter-htmlextra` version ^1.19.0
 - OS Windows 10 x64
 - The CLI command you've used to start Newman Node Js trigger

**Additional Context**

Any contextual information that might relate to the problem?

**Comment by DannyDainton** [comment]
The logs have been moved inside the requests that they are associated with now. This has been there since (v1.14.0)

![Screenshot 2020-09-04 at 17 07 26](https://user-images.githubusercontent.com/17089546/92261364-3734bc80-eed1-11ea-80ec-3b202813448d.png)

https://github.com/DannyDainton/newman-reporter-htmlextra/blob/master/CHANGELOG.md#added-11

**Comment by DannyDainton** [comment]
I'm going to close this out as it's working exactly it should and is should the console log statements in the file you provided.
