### ISSUE TITLE
Iteration tab size should be flexible.

### ISSUE THREAD

**Issue by laxmadendi** [DannyDainton/newman-reporter-htmlextra#268]
I am trying to add test case name to the iteration tab, due to fixed tab size of the iteration, the test case name is not showing properly. We can fix the height but the width of the iteration tab should be flexible based on the text. How can we achieve this? I tried changing "single-line-tabs" css by adding width as 100% and other variations but no change, width is always fixed.

**Comment by laxmadendi** [comment]
Found the way to fix the issue, modified custom-tab and removed width parameter

**Comment by DannyDainton** [comment]
This can all be handled by a custom template and you're able to make these changes locally, it's not something that I'm likely to change in the reporter, to handle a very contextual request.

If you're after help for a certain thing that's fine but you're going to need to provide more information about what your usecase is, what have you changed so far, what's not working. Show me with images, a collection showing the issue, a template that you've changed to try and achieve this, etc.
