### ISSUE TITLE
[Feature Request] Show were you are in Newman run

### ISSUE THREAD

**Issue by NewmanUser123** [DannyDainton/newman-reporter-htmlextra#269]
Sorry to bother you. Great reporter!  Is there a way to verbose log what newman is doing rather than leave the user unaware of what is going on?

For example, when you run a collection through newman, then you will see the collection name, and the requests with a Green or Red outcome.

When i run with this reporter, i am left pondering where newman is in the tests, have there been any fails, has it stalled etc.

**Comment by DannyDainton** [comment]
This is a guess but do you run the reporter with only `-r htmlextra`? 

By default, Newman uses the `cli` reporter when you don't specify one. When you do add a reporter to the run command (`-r htmlextra`) you would also need to add the `cli` reporter to the list as it now needs to _know_ that you _also_ want that reporter output.

```
newman run collection.json -r cli,htmlextra
```
If you just wanted some form of feedback about the progress, you could use `-r progress,htmlextra`.

**Comment by NewmanUser123** [comment]
Thanks @DannyDainton 

The progress : progress [----------------------------------------] 0% | ETA: 2259s | 1/103

is great. But is there a way to see:

![image](https://user-images.githubusercontent.com/70748517/92396361-d13c7500-f11c-11ea-95cb-5de81db1df8c.png)

So you know exactly where you are.

**Comment by NewmanUser123** [comment]
Thanks @DannyDainton !
