### ISSUE TITLE
Getting error while running newman with htmlextra

### ISSUE THREAD

**Issue by svarshney2311** [DannyDainton/newman-reporter-htmlextra#272]
I am getting below error after running my Test:

Newman command: newman run Collection/QA_Regression.json -r htmlextra,cli --reporter-htmlextra-title "Digital API Automation report" --folder Authentication_Authenticate -d TestData/QA_Regression_TestData.json

C:\Users\SVarshney\AppData\Roaming\npm\node_modules\newman-reporter-htmlextra\lib\index.js:124
        else if (list.length !== undefined) {
                      ^

TypeError: Cannot read property 'length' of undefined

**Comment by DannyDainton** [comment]
Are you using the latest version?

**Comment by DannyDainton** [comment]
Can you do:

```
npm uninstall -g newman-reporter-htmlextra
```

Followed by:

```
npm install -g newman-reporter-htmlextra
```

Run your command again and show me the full console output please.

**Comment by DannyDainton** [comment]
As there's no current updates, I'm going to close this out.

If you can provide details and clear steps to reproduce the problem, I will open it up again.

**Comment by svarshney2311** [comment]
Sorry for very Late response. I have re installed and it worked fine. Thanks
