### ISSUE TITLE
[Feature Request] Additional language support

### ISSUE THREAD

**Issue by isabellegly** [DannyDainton/newman-reporter-htmlextra#273]
**Is your feature request related to a problem? Please describe.**
I would like to use the reporter in a different language i.e Japanese.

**Describe the solution you'd like**
Using the reporter in a different language.

**Describe alternatives you've considered**
I have installed a plug-in in my browser that translates the page into Japanese.
.
**Additional context**
We'd like to use the reporter that outputs the file directly in Japanese.

**Comment by DannyDainton** [comment]
Hey @isabellegly

Thanks for raising this, it's not something that I'm looking to do for the reporter, at this point.

If I even tried and support a couple of different languages it's going to be a tricky task to implement, I could use some 3rd party library to handle that but the accuracy would be an issue. 

The reporter offers the ability to use custom templates so there is an option to copy the default template, makes the language changes and then use that in the Newman command.

`--reporter-htmlextra-template <path to template file>`

**Comment by DannyDainton** [comment]
I'm going to close this as it's not something that I'm going to be working on bringing into the reporter - I would look at using a custom template to create the report in the language of your choice.

Catering for all the individual languages that folks might want is going to be a huge task for me but if you want to give it a go and submit a PR for this, I would very much welcome it!! 🏆
