### ISSUE TITLE
How do I see Total No of Test cases passed and failed when I am trying to get the html report.

### ISSUE THREAD

**Issue by bhargavi1716** [DannyDainton/newman-reporter-htmlextra#274]
<!--
Hello,

Good to connect with you. And I must say that your report is amazing.

I have a requirement wherein I need to get both Console Log information (which I get from CLI when I dont use html extra tag , attached screenshot for reference) and the report at the same time **but not as the extra tab in the report**

![JenkinsCosoleOutput](https://user-images.githubusercontent.com/49748794/93751116-306cb000-fc1a-11ea-9041-898469e961c4.png)

Below is the command I am using:

newman run xx.postman_collection.json -g xx.postman_globals.json -e xx.postman_environment.json --disable-unicode --disable-unicode -r htmlextra --reporter-htmlextra-title "xx" --reporter-htmlextra-export "newman\xx.html"

FYI... I am using Jenkins to run my collection using newman.

**Comment by bhargavi1716** [comment]
Good to connect with you. And I must say that your report is amazing.

I have a requirement wherein I need to get both Console Log information (which I get from CLI when I dont use html extra tag , attached screenshot for reference) and the report at the same time **but not as the extra tab in the report**

![JenkinsCosoleOutput](https://user-images.githubusercontent.com/49748794/93751116-306cb000-fc1a-11ea-9041-898469e961c4.png)

Below is the command I am using:

newman run xx.postman_collection.json -g xx.postman_globals.json -e xx.postman_environment.json --disable-unicode --disable-unicode -r htmlextra --reporter-htmlextra-title "xx" --reporter-htmlextra-export "newman\xx.html"

FYI... I am using Jenkins to run my collection using newman.

**Comment by DannyDainton** [comment]
Hey @bhargavi1716 

Which version of the reporter are you using?

If it's the latest version, you should be able to use `newman-reporter-htmlextra -v`. If this doesn't work can you update using `npm i -g newman-reporter-htmlextra`

The console log statements in the latest versions are part of the individual requests. You would see these by using `--reporter-htmlextra-logs`

You can see all the available flags but doing `newman-reporter-htmlextra -h` from the terminal.

**Comment by bhargavi1716** [comment]
Hi ,

I have the below versions installed on my machine and I am sure they are up-to-date.

newman - 5.2.0
newman reporter 1.19.2

I just tried "newman run xx -g xx.postman_globals.json -e xx.postman_environment.json -r htmlextra --reporter-htmlextra-logs"

With the above command, Will I get both the console log information and the Html report created in the location?

As of now only the report being generated and I cant see a new tab.

My requirement is to have the console log printed in the cmd and the report should be generated. Is it possible?

**Comment by bhargavi1716** [comment]
![image](https://user-images.githubusercontent.com/49748794/93755725-65303580-fc21-11ea-829c-103b5594c989.png). Cant see new tab.  Again My requirement is to have the console log printed in the cmd and the report should be generated.

**Comment by DannyDainton** [comment]
> The console log statements in the latest versions are part of the individual requests. 

Have you checked those requests?

**Comment by bhargavi1716** [comment]
I can see the console log and the report now.

And to your question, yes I checked the individual request and can't find it anywhere.

**Comment by DannyDainton** [comment]
Not really sure what to suggest - That puts the logs into the requests. 

Can you ensure that the collection that you're running has those `console.log()` statements? You can check this in the raw JSON file.

**Comment by bhargavi1716** [comment]
Oh yeah, now I got what you are saying. Thanks for the quick reply mate! You made my day.

**Comment by DannyDainton** [comment]
Closing this one out now - Let me know if you need anything else.
