### ISSUE TITLE
[Feature Request] Generate curl into each test on HTML EXTRA REPORT

### ISSUE THREAD

**Issue by Rogatto** [DannyDainton/newman-reporter-htmlextra#276]
**Is your feature request related to a problem? Please describe.**
If we have all curl into all request on the HTML EXTRA REPORT is very fast to import on Postman

**Describe the solution you'd like**
A new param or default came all curl in each requests.

**Comment by DannyDainton** [comment]
Hey @Rogatto 

This isn't something I'm likely to add to the report - The report is generated from a Postman Collection which has all that information anyway. Doesn't really seem to be the thing to add to a report.
