### ISSUE TITLE
Add option to print current iteration to console

### ISSUE THREAD

**Issue by nickeeromo** [DannyDainton/newman-reporter-htmlextra#277]
So we are currently running 98 iterations on SEVERAL tests, and the job just runs forever. When running this reporter I only see a loading symbol and statement of what version I am using.

It be useful to see where I stand in the progress in the form of an:
iteration: 17

kind of line that updates on the next iteration. Maybe with a switch like:
--reporter-htmlextra-showProgress

For example, our current process takes about 19 minutes to run, and seeing the progress would be helpful. Thank you!

**Comment by DannyDainton** [comment]
Hey @nickeeromo

Newman gives you that functionality out of the box, you just simply need to add those reporters (cli or progress) to the run command. 

You can mix and match several of them at the same time.

Just add:

```
-r htmlextra,cli,progess
```

The way I have added the htmlextra output might be a little messed up in terms on the rendering, I've got a task to look at that.

**Comment by nickeeromo** [comment]
Ah I see - I missed that because was following newman's npm package page, and looks like they neglected to go into the details of the progress and emojitrain reporters.  Will give it a shot, thank you!

**Comment by DannyDainton** [comment]
I have something locally that I will be adding in the next version which will show the same thing as the `progress` reporter.

I just need to add a test and push the change to NPM so it won't be long, just don't have time at the moment.

**Comment by nickeeromo** [comment]
Hmm well, the behavior is now mostly this line:
 ⠇ Using htmlextra version 1.19.2

every once in a while getting replaced with a flash of this line:
 progress [===========-----------------------------] 28% | ETA: 127s | 774/2744

and then immediately gets replaced with the first line again.

From here I think it may just be better to either replace the first line with the second or have a readout of the first line and then display the second as progress. Is there a way to do that?

**Comment by DannyDainton** [comment]
Yeah that's totally me not thinking about how that would work with the other reporters. 🤦‍♂️

I've fixed that now and if you want to use that progress reporter it will use that, else it will use my version. 

The flickering thing has gone too - that was just annoying and I was the one that added it 😬...I was trying to be fancy and use a different library but that's gone now.

I'll hopefully get some time later to finish up and push the change.

**Comment by DannyDainton** [comment]
Hey @nickeeromo 

I've pushed a new version - I was having issues with my GH Action workflow but semi solved now. 

If you just use `htmlextra` and not the `progress` reporter you should see something like this now.

![image](https://user-images.githubusercontent.com/17089546/95894658-513fa580-0d81-11eb-9db4-b14573601c12.png)

**Comment by DannyDainton** [comment]
Hey @nickeeromo 

Would love to close this out so if you get the chance to check out the change on the new version that would be awesome.

**Comment by nickeeromo** [comment]
Yes sorry I was unavailable yesterday to do this. I intend to test this out a little later this evening, thank you!

**Comment by nickeeromo** [comment]
OK so I'm running it from Concourse V5, using a bash .sh to run, and the console looks like this:

![image](https://user-images.githubusercontent.com/25245721/96078831-63a10880-0e81-11eb-8a35-51db74514a79.png)

So it is working but the colors are not. ALTHOUGH this maybe be something on our end - we are told to turn all colors off where we have the option to, and I wonder if it is because of quirks such as this.

In any case, _I'm_ OK with this being closed as it is clearly functional, so up to you if you feel it is complete :D Thank you!

**Comment by DannyDainton** [comment]
Yeah, not really anything I can really do about that and it's also doing something strange with the encoded characters being used for the progress bar. 

I might add a flag to disable the console output so you have the choice to see this or not 🤔

Going to close this for now but let me know if you see any other issues.
