### ISSUE TITLE
[BUG] Terminal constantly shows : "Using htmlextra version 1.19.2"

### ISSUE THREAD

**Issue by NewmanUser123** [DannyDainton/newman-reporter-htmlextra#278]
When i run newman with this reporter, i now see the following constalty flashing in the console log.  

Is this a bug, or can it be turned off?

`└ 1- Access Menu > Maintain (Window Navigation)
| Using htmlextra version 1.19.[200 OK, 83.63KB, 779ms]
/ Using htmlextra version 1.19.2
└ 2 - Access Sub Menu > Documents (Windows Navigation)
- Using htmlextra version 1.19.[200 OK, 83.63KB, 676ms]

└ 3. Select Document Requests 
/ Using htmlextra version 1.19.2`

**Comment by DannyDainton** [comment]
I've fixed this issue locally, it was just the way the that the library interacts with the CLI reporter.

What's the full Newman command you're using?

**Comment by DannyDainton** [comment]
@NewmanUser123 I've just pushed a new version, are you able to update and check that, please.

If that's not quite right I can have a look closer at your specific issue.

**Comment by NewmanUser123** [comment]
Morning Danny, 

Updated to 1.19.4

CLI command:

newman run ./debug/debug.postman_collection -e ./debug/debug.postman_environment --insecure -r cli,htmlextra --reporter-htmlextra-export ./results/debug_report.html

Can advise that this issue is now fixed in this version. Thanks again
