### ISSUE TITLE
[Feature Request] Add an option to set report name based on timestamp

### ISSUE THREAD

**Issue by ffcasteele** [DannyDainton/newman-reporter-htmlextra#282]
**Is your feature request related to a problem? Please describe.**
Being able to specify the name and location with a flag is great, but there are situations where it would be useful to have everything saved using a timestamp as a name for the report output. This would allow for old reports to be saved and easily distinguished from each other based on the date and time they ran.

**Describe the solution you'd like**
Ideally, a new option flag would be set that is similar to the current custom naming solution, but it would automatically assign a name based on the time and date of the server. Instead of specifying a folder and name, users could specify a folder and the name would be assigned automatically as a timestamp.

**Describe alternatives you've considered**
For the most part, users could come up with a solution on their end that would solve this issue. There's nothing wrong with users who have need of timestamps/older reports figuring out a solution for themselves, but as a "nice to have" it would be convenient for a out-of-the-box solution to exist within the reporter itself.

**Additional context**
This is a relatively minor issue and it certainly doesn't detract from the usefulness of the reporter. I was just kind of surprised that I didn't see an option for this in the existing reporter option flags since it seemed like something that a lot of users might find handy as a way to organize old reports.

**Comment by DannyDainton** [comment]
Thanks for submitting the feature request - This isn't really something that I'm going to be working on anytime soon. If other users state that this would be useful to them, I can look at added something in but until that point, this might hang around for a while.

Can you provide a visual example of what you would like to see, things are always better when you can see what the person means :D 

All PRs are welcome if you wanted to give this a go yourself and push this forward quicker :D

**Comment by praveendvd** [comment]
`""./node_modules/.bin/newman" run 1.json -r htmlextra --reporter-htmlextra-title %DATE%%TIME% --reporter-htmlextra-export "newman/newman_%DATE:~6,2%-%DATE:~3,2%-%DATE:~6,4%_%TIME:~0,2%%TIME:~3,2%%TIME:~6,2%.html"`

this code can be used for cmd , similar approach can adopted for powershell or terminal

**Comment by DannyDainton** [comment]
Hey @ffcasteele - Is something like what @praveendvd mentioned, what you're after here?

**Comment by DannyDainton** [comment]
Closing this as there hasn't been a response in >28 days
