### ISSUE TITLE
Report Hangs when there is data of 2.7 MB in HTML File

### ISSUE THREAD

**Issue by ganeshsirsi** [DannyDainton/newman-reporter-htmlextra#283]
HTML Report Hangs when I open in the browser if there is data of 2.7 MB

**Comment by DannyDainton** [comment]
Closing as it relates to this - https://github.com/DannyDainton/newman-reporter-htmlextra/issues/259

Also - please use the template I provided, deleting it is just going to make to ask you for the basic information again.
