### ISSUE TITLE
htmlextra report looks clumsy

### ISSUE THREAD

**Issue by svarshney2311** [DannyDainton/newman-reporter-htmlextra#286]
Hi,

from past two days my htmlextra report looks like below:
![image](https://user-images.githubusercontent.com/66395814/99887111-80162a80-2c0f-11eb-9d35-a8a609c84d39.png)

**Comment by DannyDainton** [comment]
I don't even know what that's means. 

I see an image with the CSS not rendered correctly....whatbwould you like me to do with that?

I added a bug template to the repo, to capture the most basic details I require to be able to understand what the issues are - you choose to delete all that and post this.

I'm going to close this and allow you to create a new issue using the templete.

**Comment by DannyDainton** [comment]
https://github.com/DannyDainton/newman-reporter-htmlextra/issues/199

Is showing the same so it's more than likely a Jenkins issue or everyone using the reporter would be raising this issue.

**Comment by svarshney2311** [comment]
This is happening directly running newman command and opening in Chrome Browser. In my case nothing to do with Jenkins.I am still facing this issue.

**Comment by DannyDainton** [comment]
You're telling me more information now about the context than when you raised the issue, this isn't the way it should be be.

Please raise another issue, with the full details and I will look into it more. 

Think about all the different things you're using and note them down:

- Newman and Reporter versions? 
- Which Browser? 
- Is this in Private or Incognito mode? 
- What's the full Newman command? 
- Are you using a custom template?
- What error are you seeing in the Browser Console? 
- Are any of the CDN calls failing or showing a 404? 
Where was the last time you say this not happening? 

I'm not a mind reader and I'm also not sat  next to you to see/know all these things. I can't help you if you're not putting in the effort to help me.
