### ISSUE TITLE
[BUG] Setting a Title does not show correctly

### ISSUE THREAD

**Issue by NewmanUser123** [DannyDainton/newman-reporter-htmlextra#288]
I have the following set in the package.json.

        `"newman-debug": "newman run ./debug/debug.postman_collection.json -e ./debug/debug.postman_environment.json --insecure -r cli,htmlextra --reporter-htmlextra-export ./results/debug_report.html --reporter-htmlextra-title test one two three",`

As you can see i have set the title to "test one two three"

Once the report has run, the title has update, however, only shows the first 4 letters:

![image](https://user-images.githubusercontent.com/70748517/100764727-929e1a00-33ee-11eb-9a3f-545733d12573.png)

**Comment by DannyDainton** [comment]
@NewmanUser123 

```
--reporter-htmlextra-title test one two three"
```

This should be:

```
--reporter-htmlextra-title "test one two three"
```

**Comment by NewmanUser123** [comment]
Hey @DannyDainton i tried with 'test one two three'

And the report title showed 'tes

You are correct, i couldn't do ""
Due to the cli command being wrapped in ""

**Comment by DannyDainton** [comment]
Wrapping it in single quotes works fine - I just tested that on the actual reporter project.

![image](https://user-images.githubusercontent.com/17089546/100770799-93867a00-33f5-11eb-8118-48edb9036f0c.png)

I have no idea what you're doing - I don't think there is anything that I can do here. I'm going to close this now.

**Comment by NewmanUser123** [comment]
That's a shame you have closed this, as i have literally done what you have, and it doesn't work!

`        "newman-debug": "newman run ./debug/debug.postman_collection.json -e ./debug/debug.postman_environment.json --insecure -r cli,htmlextra --reporter-htmlextra-title 'test one two three' --reporter-htmlextra-export ./results/debug_report.html",`

![image](https://user-images.githubusercontent.com/70748517/100845503-41853900-3475-11eb-9a4c-c9b4eac60b5f.png)

**Comment by DannyDainton** [comment]
What is it that you would like me to do here? 

I have literally showed the same thing working.

Is it _only_ not working as part as that package json script? 

Have you tried it out in any other context? 

You're not really telling me anything about what's actually happening here apart from copy and pasting a command into a github issue with a cropped tiny image of the top of a report. 

You haven't told me what versions of anything that you're running, given me a collection that I can locally reproduce the issue, a copy of the report so I can see what's added to the html element, if your running that as part of a pipeline or just from the command line as a local script, etc etc.

By not telling or showing me anything about what's happening on your side, I literally cannot do anything about this problem. I'm not a mind reader.

**Comment by NewmanUser123** [comment]
There is literally no reason to have your attitude towards me as a supporter of this software.

Given it's a CLI command line, i would have thought it was obvious that this would be running in a terminal or a build server.

I have tried other context, for example, 

- without specifying the place to store the HTML
- without specifying ,cli
- with ""
- without ""
- with ''
- without ''
- with words with no spaces
- checking there are no special characters from a copy and paste
- Browser version just encase it is a rendering issue
- upgrading to the latest version from 1.19.4 > 1.19.6 (which btw now has deprecation warnings)
- i've looked at a race condition is teh test finsihing and the html not having enough time to build.

If i could send you the Collection i would, but i cannot.

 I can appreciate that i may have not provided all the details you wanted, How about making a template like others so when you create a bug, it asks for Mandatory information!

I'll look elsewhere for a reporter!

@DannyDainton

**Comment by DannyDainton** [comment]
This is the bug template I created to capture those details - You choose to delete this and add those initial details to open the issue. 

```
<!--
This is the _basic_ information that I require, in order to help with the issue - If you either delete this template or fail to fill in the sections...I'm just going to end up asking you for it anyway... 
-->

**What Are You Seeing**

A high-level description explaining the issue that you're facing. 

**Steps To Reproduce The Issue**

**Screenshots and Gifs**
I'm a visual person so it would be a HUGE help if you shared a screenshot of what you're seeing....
_A picture paints a thousand words..._

**Collection and Environment Files**

Any files that would allow me to reproduce the issue locally...

**Version and Platform Information:**
 - `newman` version 
 - `newman-reporter-htmlextra` version
 - OS 
 - The CLI command you've used to start Newman

**Additional Context**

Any contextual information that might relate to the problem?
```

You're now providing more information and context _after_ I asked for it - which would have saved a back and forth conversation in the first placed, trying to establish what's going on.

**Comment by NewmanUser123** [comment]
@DannyDainton 

Don't worry i have now resolved the issue. I needed Escape Characters and an =

`--reporter-htmlextra-title=\"One Two Three\"`

The issue was with me as you have stated in more than one way personally and with my code!.

Take care,

**Comment by DannyDainton** [comment]
I understand why it could be escaping the quotes but not sure why the `=` would be needed - The reporter or Newman doesn't require that.

Glad to see you have your code working.
