### ISSUE TITLE
[BUG]  Error: Cannot find module '/root/.npm-global/lib/node_modules/newman-reporter-htmlextra/node_modules/helper-markdown/node_modules/highlight.js/deprecated.js'

### ISSUE THREAD

**Issue by Luciferzhangyi** [DannyDainton/newman-reporter-htmlextra#290]
My Jenkins job failed recently in npm install step.

![image](https://user-images.githubusercontent.com/8464003/101275973-ea6cc480-37e4-11eb-9cc3-10b66bd2df2d.png)

Related to https://github.com/DannyDainton/newman-reporter-htmlextra/pull/285/files ?
![image](https://user-images.githubusercontent.com/8464003/101276083-84347180-37e5-11eb-901c-07e3e90316d2.png)

**Comment by DannyDainton** [comment]
Could you be more specific about when that started to fail?

When was the last time that it passed?

Is this only failing when run with Jenkins or from the command line too? 

The highlight.js module has been a pain the backside for me recently as they have deprecated v9 but other dependencies use the other version. The huge error that they have placed on the install which has nothing to do with my reporter doesn't help either.

**Comment by Luciferzhangyi** [comment]
I'm not able to tell when it started to fail, because my github account had some issue. The last success was on Nov 9th.
I resolved my github account issue 2 days ago. And found Jenkins job failed due to this highlight.js.

It only fails in Jenkins.

**Comment by mgutierrez-gmd** [comment]
@Luciferzhangyi although this is not failing for me, I do get a warning about highlight.js being deprecated. Worth updating the dependency or changing it altogether.

```
 Verion 9 of Highlight.js has reached EOL.  It will no longer
  be supported or receive security updates in the future.
  Please upgrade to version 10 or encourage your indirect
  dependencies to do so.

  For more info:
  [34m
  https://github.com/highlightjs/highlight.js/issues/2877
  https://github.com/highlightjs/highlight.js/blob/master/VERSION_10_UPGRADE.md
 [41m[37m
```

**Comment by DannyDainton** [comment]
There is currently an open issue on that repo (https://github.com/helpers/helper-markdown/issues/14) as they would need to update that package - The areas that I have control over and can change the versions I have done but that's a dependency of something else that I use and there isn't a great deal I can do about it.

The way that highlight.js presents that message in the console isn't ideal and there have been many discussions about that but it's a major version change that could break users integration so that wanted them to know about it.

**Comment by DannyDainton** [comment]
I'm going to close this out as there isn't really anything that I can currently do to help with this - I've pinged the repo moderators on the helper-markdown project again but it's out of my hands at the moment.
