### ISSUE TITLE
[BUG] Cannot use htmlextra when using newman as a library

### ISSUE THREAD

**Issue by praveendvd** [DannyDainton/newman-reporter-htmlextra#292]
getting error message saying htmlextra cannot be loaded

**What Are You Seeing**

A high-level description explaining the issue that you're facing. 
![image](https://user-images.githubusercontent.com/45095911/102705710-7801e700-42b0-11eb-8252-91137b79cbc0.png)

**Steps To Reproduce The Issue**

```
newman.run({
    collection: require('./1.json'),
    reporters: ['htmlextra','cli'],
    iterationCount: 1,
  }, function (err) {
    if (err) { throw err; }
    console.log('collection run complete!');
});
```

**Collection and Environment Files**

[1.zip](https://github.com/DannyDainton/newman-reporter-htmlextra/files/5720575/1.zip)

**Version and Platform Information:**

    "newman": "^5.2.1",
    "newman-reporter-htmlextra": "^1.19.6"
 - OS  : Windows 10

**Comment by DannyDainton** [comment]
I'll take a look at this tomorrow, not sure what's happening there.

That line is about adding the progress information to the CLI 🤔

**Comment by DannyDainton** [comment]
@praveendvd is this still causing you an issue?

What version of node do you use?

**Comment by praveendvd** [comment]
its still showing same message i am using node v14.15.0 @DannyDainton

**Comment by DannyDainton** [comment]
I think I can see the issue - For some reason, the way that it knows which reporters are used is different when using it from the CLI and using in a library. That's why it works as expected when using the CLI :( 

I'll take a look at this at try and sort it out.

**Comment by DannyDainton** [comment]
@praveendvd I pushed a new version, would you mind checking to see if that solves it for you? :D

**Comment by praveendvd** [comment]
- Worked <3

**Comment by DannyDainton** [comment]
Awesome - It's a temporary hacky fix to be honest but I wanted to get you / everyone unblocked.

Apologies and thanks for raising that one mate!! 🏆
