### ISSUE TITLE
Help Required: HTMLEXTRA report does not look good or not in correct format

### ISSUE THREAD

**Issue by svarshney2311** [DannyDainton/newman-reporter-htmlextra#296]
HTMLEXTRA report does not look good or not in correct format. It works fine in other system. Just want to know any idea why it is showing wrongly. installed htmlextra lates version..
npm version: 6.14.6
htmlextra version: 1.19.7
windows10
![image](https://user-images.githubusercontent.com/66395814/104111890-d3266880-52b5-11eb-9b4b-950cd32fba8f.png)

**Comment by DannyDainton** [comment]
- Where are you running Newman? 
- Are you using some form of VPN?
- What errors are you seeing in the Browser Dev Tools console?

This is all down to the CSS and the way it's rendering the page - The styles are from CDNs which could possibly be failing depending on where you are and what network you're on.

**Comment by svarshney2311** [comment]
I am running Newman through command line in windows. I tried opening HTML with VPN and without VPN, but has same issue.
Below error logged in console
![image](https://user-images.githubusercontent.com/66395814/104139001-4e4f5380-5376-11eb-9260-3463867f0e3a.png)

**Comment by DannyDainton** [comment]
It failed to load the bootstrap css...that's why it's rendering the page that way.

Are you able to go directly to the URL mentioned in that error message.

**Comment by svarshney2311** [comment]
it shows me 404 not found page;
![image](https://user-images.githubusercontent.com/66395814/104202422-eb52d080-53f8-11eb-98b4-1daf3c8091fd.png)

**Comment by DannyDainton** [comment]
I don't really want to state the obvious but....that's the reason the report looks like that. All the bootstrap styles come from that CDN. 

This is what I see...

![image](https://user-images.githubusercontent.com/17089546/104209555-cb87d080-5429-11eb-893e-d7e324d070c6.png)

**Comment by DannyDainton** [comment]
You could try this in the template if you can load this page https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css

**Comment by svarshney2311** [comment]
excellent!!!

I am able to load  https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css and with this my report looks good.

Thank you for helping me out of this.

**Comment by DannyDainton** [comment]
Cool, going to close this issue.
