### ISSUE TITLE
Minor typo in dashboard-template.hbs (gloabl instead of global)

### ISSUE THREAD

**Issue by sweetnoods** [DannyDainton/newman-reporter-htmlextra#298]
https://github.com/DannyDainton/newman-reporter-htmlextra/blob/1a9edb1c4025cbe6a38456d87c8cc70bb4e7b367/lib/dashboard-template.hbs#L525

Should be a quick fix but just wanted to be sure it wasn't referenced anywhere else. 

It caused some confusion today when looking for our global variables in the raw .html

**Comment by DannyDainton** [comment]
🤦‍♂️ Well caught... 🤣

You could create a branch/PR and fix that if you wanted to contribute to the project ❤️

**Comment by sweetnoods** [comment]
I tried last night but got a permission error when trying to push to a new branch 

```
git push --set-upstream origin typo_fix
ERROR: Permission to DannyDainton/newman-reporter-htmlextra.git denied to sweetnoods.
fatal: Could not read from remote repository.
```

Should I set the upstream branch to a different one?

**Comment by DannyDainton** [comment]
You would need to clone the repo, create a new branch and then submit a PR - Unless I'm not getting what you're doing there :D

**Comment by sweetnoods** [comment]
- [x] repo cloned
- [x] branch created locally with changes committed
- [ ] push branch to open PR is where I'm stuck with permission issues. 

Could well be something on my side - but from this error message it makes it sound like users cannot create branches remotely: 

```ERROR: Permission to DannyDainton/newman-reporter-htmlextra.git denied to sweetnoods.```

**Comment by DannyDainton** [comment]
That's weird - Other people have been able to contribute and raise a PRs 🤔 

That message looks like you're trying to push that directly to my repo (hence the permission denied to that user...because you're not me :D ) rather than committing the changes to your forked repo and then raising a PR 🤷‍♂️
