### ISSUE TITLE
Iteration colour

### ISSUE THREAD

**Issue by RuggeriLuca** [DannyDainton/newman-reporter-htmlextra#3]
It will be nice if the box that contain the iteration number will be colored :
Greed if is all passed
Red if there is Failed Tests

**Comment by DannyDainton** [comment]
This is something that I can't easily change without a hacky fix on the template. 

A change is needed in Newman to show that an iteration has failed, it doesn't currently do this and the value will always just show the total number of iterations.

This has been raised as a issue in the Newman project so once that's been fixed, I can added functionality to the default template.

**Comment by DannyDainton** [comment]
I've been thinking about this a little bit more - I'm going to change the `Total Iteration` panel colour based on the Test Failures. Is still don't have a way to know how many iterations failed but this is a good first step. 

Some examples:

![iterations_passed](https://user-images.githubusercontent.com/17089546/52914454-50125880-32c0-11e9-8ea9-a0d9b918e959.png)


![iteration_failed](https://user-images.githubusercontent.com/17089546/52914458-57d1fd00-32c0-11e9-9408-a37ceb21645d.png)


![with_skipped](https://user-images.githubusercontent.com/17089546/52914461-5dc7de00-32c0-11e9-8bb2-00ec5525e1ce.png)

**Comment by DannyDainton** [comment]
Hey @RuggeriLuca 

In the latest reporter (v1.11.0) - I have changed the report to show the Pass/Fail colour on the iteration tabs. Hope this helps!
