### ISSUE TITLE
Count of failed requests

### ISSUE THREAD

**Issue by wonboyn** [DannyDainton/newman-reporter-htmlextra#30]
Hi Danny,

I'm trying to get a count of failed requests as opposed for failed assertions.

When I run newman with the JSON reporter it shows:

...
  "run": {
    "stats": {
      "iterations": {
        "total": 1,
        "pending": 0,
        "failed": 0
      },
      "items": {
        "total": 66,
        "pending": 0,
        "failed": 0
      },
 ...
      "assertions": {
        "total": 155,
        "pending": 0,
        "failed": 20
      },

I would have expected that a failed assertion means that the associated request/item is also failed. 

Is that not the case?

I had a quick look at your aggregator function & it doesn't appear as though you keep a counter of executed / failed / passed at the request level - only the assertion level.

Is this something you'd contemplate adding?

Thanks

**Comment by DannyDainton** [comment]
If you wanted to submit a PR, I can take a look?

**Comment by wonboyn** [comment]
Hi Danny,

I would have expected that a failed assertion means that the associated request/item is also failed.
Is that not the case?

Tim

**Comment by DannyDainton** [comment]
So a request can have no tests/assertions and still `fail` so a number of reasons.

**Comment by wonboyn** [comment]
>>So a request can have no tests/assertions and still fail for so a number of reasons.

Ok. But a failed assertion does not mean a failed request/item?

**Comment by DannyDainton** [comment]
Nope, the request could return a `200` and be all good. 

You could have a test in that Request, which checks for a `201`, that would `fail` the test but the request would still be good.

**Comment by DannyDainton** [comment]
@wonboyn not really sure where you like to go with this?

It's not an issue with the reporter so I'm going to close this issue. If you would like me to reopen it based on more information or if you wanted to create a PR for a new feature/change in behaviour, that's cool with me.
