### ISSUE TITLE
[Feature Request] Enhance the folder/sub-folder in the Total Requests

### ISSUE THREAD

**Issue by mudrohvar** [DannyDainton/newman-reporter-htmlextra#301]
I have sub-folders in my postman collection but when the report is being generated I am only getting only 1 layer of folders
Ex.
**Postman collection:** 
CollectionName -> Folder1 -> Sub-Folder1 -> API Request
CollectionName -> Folder1 -> Sub-Folder2 -> API Request

**Report:**
Under Total Requests:
Folder1/Sub-Folder1 - x Requests in the folder
Folder1/Sub-Folder2 - y Requests in the Folder

**Desired:**
Under Total Requests:
Folder1 -> Sub-Folder1 - x Requests in the folder, Sub-Folder2  - y Requests in the folder (All the sub-folders for Folder1 should be grouped together)
Folder2 -> Sub-Folder1 - z Requests in the folder

I tried to edit the template to achieve this but was not able to do it (mainly because of lack of technical ability).

**Comment by DannyDainton** [comment]
Can you edit your question and provide some images about what you see now and what you would like to see happening, please.

This isn't something that I'm going to be even looking at soon so it's going to be an open feature request for a while. Just need to make other things (my actual job :D ) the priority right now.

**Comment by mudrohvar** [comment]
Hello @DannyDainton, I discovered that this feature was already requested and commented on (#297). I think we can close this request, sorry not not doing this before opening the ticket. I will not be able to provide any screenshots because I am currently working with my organization's data.

Just a side note: Love your work, I am a Business Analyst and this is something that will drastically improve my quality of work.

**Comment by mudrohvar** [comment]
Let me know if you want me to close the issue. Again, sorry for the inconvenience.

**Comment by DannyDainton** [comment]
I thought I had seen something similar raised before :D 

You can create a mocked out Collection with the same folder structure and run it with Newman to produce the report, for example purposes. 

I'm 100% not interested in the data of your actual collection :D
