### ISSUE TITLE
[Feature Request] Possibility to skip certain requests from the report

### ISSUE THREAD

**Issue by vali-craciun** [DannyDainton/newman-reporter-htmlextra#308]
We have build a logic workflow and around each request/request group we have a _pre and a _post requests with their additional logic.
If would be great if it can be a possibility to skip that requests in the reports (also in the counts):

![image](https://user-images.githubusercontent.com/77937953/108843950-16c5ff00-75e4-11eb-9c91-8934f6fd0b9b.png)

**Comment by DannyDainton** [comment]
Hey @vali-craciun

What you're using is the default template that show 1 view of the data depending on certain flags.

You have full control about how the final report looks and feels, the underlying data will always be the same but you can create custom templates to suit any usecase you have.

Once you have a template, you can just reference that in the Newman command:

```
--reporter-htmlextra-template template.hbs
```

**Comment by DannyDainton** [comment]
Always grateful for the help @praveendvd ❤️

**Comment by praveendvd** [comment]
@DannyDainton  i see the npm publish workflow is initiated but couldn't see new version in npm repo

**Comment by DannyDainton** [comment]
The `skipRequests` flag has been added to version `1.22.0`

**Comment by vali-craciun** [comment]
> The `skipRequests` flag has been added to version `1.22.0`

thank you very much
