### ISSUE TITLE
highlight.js@9.18.5: Support has ended for 9.x series. Upgrade to @latest 

### ISSUE THREAD

**Issue by krgoyal** [DannyDainton/newman-reporter-htmlextra#309]
npm WARN deprecated highlight.js@9.18.5: Support has ended for 9.x series. Upgrade to @latest
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     undefined,
npm WARN cleanup     AssertionError [ERR_ASSERTION]: rimraf: missing path
npm WARN cleanup         at rimraf (/root/.nvm/versions/node/v15.11.0/lib/node_modules/npm/node_modules/rimraf/rimraf.js:54:3)
npm WARN cleanup         at node:internal/util:325:7
npm WARN cleanup         at new Promise (<anonymous>)
npm WARN cleanup         at rimraf (node:internal/util:311:12)
npm WARN cleanup         at /root/.nvm/versions/node/v15.11.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:397:20
npm WARN cleanup         at Array.map (<anonymous>)
npm WARN cleanup         at Arborist.[rollbackCreateSparseTree] (/root/.nvm/versions/node/v15.11.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:397:8)
npm WARN cleanup         at /root/.nvm/versions/node/v15.11.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:825:50
npm WARN cleanup         at async Arborist.[reifyPackages] (/root/.nvm/versions/node/v15.11.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:204:11)
npm WARN cleanup         at async Arborist.reify (/root/.nvm/versions/node/v15.11.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:130:5) {
npm WARN cleanup       generatedMessage: false,
npm WARN cleanup       code: 'ERR_ASSERTION',
npm WARN cleanup       actual: undefined,
npm WARN cleanup       expected: true,
npm WARN cleanup       operator: '=='
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 127
npm ERR! path /root/.nvm/versions/node/v15.11.0/lib/node_modules/newman-reporter-htmlextra/node_modules/highlight.js
npm ERR! command failed
npm ERR! command sh -c node deprecated.js
npm ERR! sh: node: command not found

**Comment by krgoyal** [comment]
Installed nvm/npm/newman using following commands in linux box-
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
nvm --version
nvm install node
npm install -g newman
npm install -g newman-reporter-htmlextra

![image](https://user-images.githubusercontent.com/48672034/110512090-e9706980-812a-11eb-997d-5613de624f30.png)

**Comment by DannyDainton** [comment]
See here for more details 

https://github.com/DannyDainton/newman-reporter-htmlextra/issues/290

There nothing that I can do to make 3rd parties update their dependant modules. I've raised an issue on the repo.

**Comment by DannyDainton** [comment]
The deprecated package would prevent you from using the htmlextra reporter. 

The error is cause by some thing else that's removing files. As a standalone download using node v15 I can get and use the reporter package.

I don't know the full context here and you maybe doing other things.

You could try using the Docker image?

`dannydainton/htmlextra`

**Comment by DannyDainton** [comment]
@krgoyal did you have any luck with the Docker image?

**Comment by DannyDainton** [comment]
@krgoyal I'm going to close this issue, there isn't really anything that I can do here as I'm also still waiting for a change in a different package.

All the warnings wouldn't impact the reporter from working and the error you see doesn't really have anything specific to do with the reporter code or is something that I can 'fix'.
