### ISSUE TITLE
[Bug] First digit moves to the next line if report has over a 1000 iteration

### ISSUE THREAD

**Issue by allnvrgs** [DannyDainton/newman-reporter-htmlextra#311]
**What Are You Seeing**
First digit moves to the next line if report has over a 1000 iteration

**Steps To Reproduce The Issue**
A collection and a data file that has over a 1000 iteration. 

**Screenshots and Gifs**
![image](https://user-images.githubusercontent.com/15529723/112265545-9e6b6000-8cad-11eb-9c87-62f28470b489.png)

**Collection and Environment Files**

Any files that would allow me to reproduce the issue locally...

**Version and Platform Information:**
 - `newman` version 5.2.0
 - `newman-reporter-htmlextra` version 1.19.4
 - OS win10
 - The CLI command you've used to start Newman
newman run <postman collection> -e <env variable> -d <data file> -r htmlextra,cli --reporter-htmlextra-showOnlyFails

**Additional Context**

Any contextual information that might relate to the problem?

**Comment by DannyDainton** [comment]
Nice catch @allnvrgs - I'm not going to lie, as this is something that happens for 1000+ iterations only, I'm not going to be looking to fix this for a while.

The template is there for you to change and use though, I'm sure something could be done to reduce the font size of those numbers, as a quick fix.

**Comment by DannyDainton** [comment]
@allnvrgs 

I've pushed a change in the latest version to fix this issue - It should look like this now:

![Screenshot 2021-03-24 at 11 07 11](https://user-images.githubusercontent.com/17089546/112307183-8b01ca00-8c98-11eb-9318-cf9cff08c441.png)

**Comment by allnvrgs** [comment]
Hi @DannyDainton ,

It works great. Thanks for the quick fix.

![image](https://user-images.githubusercontent.com/15529723/112411139-602a7b00-8d57-11eb-9710-6e3fed4f716c.png)

Regards,
Allen
