### ISSUE TITLE
[Feature Request ] Exclude specific folder from report

### ISSUE THREAD

**Issue by 4nif** [DannyDainton/newman-reporter-htmlextra#313]
Hi @DannyDainton 

Is it possible to exclude a specific folder from the report?
I have a use case where we need to execute the setup script folder before we can execute the real test

For now, HTML report generates all folder, I would like to know if possible to exclude the folder from the report?

Thanks

**Comment by DannyDainton** [comment]
Not at the moment - I think I did experiment with excluding folders a while back but never got the time to fully get into it.

**Comment by praveendvd** [comment]
This looks like an interesting feature we can get rid of setup steps from report @DannyDainton  i could have a look into this

**Comment by DannyDainton** [comment]
The `skipFolders` flag has been to version `1.22.0`
