### ISSUE TITLE
[Feature Request] Join multiple reports into one

### ISSUE THREAD

**Issue by lucielavickova-tesena** [DannyDainton/newman-reporter-htmlextra#317]
When running Postman tests in parallel, I end up having multiple reports to go through. 
I would like to aggregate these into one report, would it be possible to implement such feature?

I've tried the allure reporter as an alternative, but it did not provide me with complete info about the requests (missing request parameters, request and response headers, encoding issues...), therefore I prefer the htmlextra reporter.

Thanks

**Comment by DannyDainton** [comment]
Hey @lucielavickova-tesena 

Thanks for the question.

It's not something that I'm looking to do in the reporter and I'm not really sure if it would be possible. Newman is a 1 collection at a time tool, as much as those are running in parallel, I think Newman is still just running 1 collection per instance.

Joining them together would be tricky and I'm not even sure what the final output would look like 🤔

**Comment by DannyDainton** [comment]
I'm going to close this out as its really not something I'm likely to do so I didn't want to give anyone false hope :(
