### ISSUE TITLE
[BUG] Package size and unused dependencies

### ISSUE THREAD

**Issue by b-pagis** [DannyDainton/newman-reporter-htmlextra#318]
## Problem
There are some unused dependencies and files that bloats final package size to 14 MB.
![image](https://user-images.githubusercontent.com/55126320/119714804-f2402400-be6b-11eb-9792-565da2e870eb.png)

Running `npm-check` suggest following dependencies are not used:
* autolinker
* highlight.js
* remarkable
* snyk

`depcheck` suggests following dependencies are not used
* autolinker
* gulp-header
* highlight.js
* remarkable
* snyk
Unused devDependencies
* eslint-plugin-import

Few other examples where versions in the `package.json` mismatch and are not used in the code:
* https://github.com/DannyDainton/newman-reporter-htmlextra/search?q=remarkable
* https://github.com/DannyDainton/newman-reporter-htmlextra/search?q=highlight

## Suggested solution
1) Removing unused dependencies from `package.json`;
2) Including `test/*`, `examples/*` and other not required files into `.npmignore`

This should reduce package size to ~46KB (~300 times):
```
npm notice === Tarball Details === 
npm notice name:          newman-reporter-htmlextra               
npm notice version:       1.20.4                                  
npm notice filename:      newman-reporter-htmlextra-1.20.4.tgz    
npm notice package size:  46.0 kB                                 
npm notice unpacked size: 236.1 kB                                
npm notice shasum:        a35696258573a7a810209890d5e67bb6a2cb75f4
npm notice integrity:     sha512-7TTlDWJQ2WyZe[...]gywiyhNmWwuHw==
npm notice total files:   23                                      
npm notice 
```
and `npm install` should produce following results

|Before|After|
|---|---|
|![image](https://user-images.githubusercontent.com/55126320/119716080-63340b80-be6d-11eb-98ff-1376d5ba0069.png)|![image](https://user-images.githubusercontent.com/55126320/119716090-67f8bf80-be6d-11eb-8f3b-1a85ccbdc768.png)|

**Comment by DannyDainton** [comment]
Definitely something that I'd like to change and streamline everything. If we can reduce the waste I'm up for that 🏆

If you wanted to create a PR for those changes, that would be awesome. 😍

**Comment by b-pagis** [comment]
Added, but I am not sure about the `snyk` configuration that is being used. Please double check it, if it was not removed with the [PR](https://github.com/DannyDainton/newman-reporter-htmlextra/pull/319) and the intended protection still works.

P.S.
Seems that github actions uses outdated node version. As per [Node Releases]( https://nodejs.org/en/about/releases/), version 10 is no longer maintained.

**Comment by DannyDainton** [comment]
Another thing on my list of things to do 😢

Getting time to do all the things in the very little spare time I have is the tricky thing.

Appreciate you doing all this. ❤️

Are those things you mentioned about the `.npmignore` still required?

**Comment by b-pagis** [comment]
No, `.npmignore` is not required anymore, because it [can't ignore](https://docs.npmjs.com/cli/v7/using-npm/developers#keeping-files-out-of-your-package) specific files. Because of this, I've used other method, which gives more control over files that needs to be included into the package via `package.json` [files](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#files).

**Comment by DannyDainton** [comment]
Pushed a new package to npm with these changes! Thank you so much! 

Sometimes you just can't see what's in front of you!! :D  

If there are any other project improvements or any of the open issues that you wanted to take up, that would be awesome!! I need all the help I can get :D
