### ISSUE TITLE
Add extra helper for setting variables

### ISSUE THREAD

**Issue by wonboyn** [DannyDainton/newman-reporter-htmlextra#32]
Hey Danny,

It would be helpful to be able to save values during template process for later use in the template. 

Can you add an extra helper something like the following:

```
handlebars.registerHelper('assign', function (varName, varValue, options) {
    if (!options.data.root) {
        options.data.root = {};
    }
    options.data.root[varName] = varValue;
});
```

Thanks

Tim

**Comment by DannyDainton** [comment]
Hi @wonboyn 

Would you be able to elaborate more or provide an example of what you hope this would look like in the template?

Do you have this helper running locally?

Danny

**Comment by wonboyn** [comment]
Hey Danny,

>>Do you have this helper running locally?
Yes.

>>Would you be able to elaborate more or provide an example of what you hope this would look like in the template?

I need to provide a count of requests that have failed assertions (as opposed to failures.length). 

Rather than modifying your existing aggregator functionality, I thought it would be easier to modify the template to iterate through the executions array & increment a variable if cumulativeTests.failed is true.

To do this I needed to be able to set/change a variable.

I had a look through the handlebars-helpers library you've included but they only seem to have a getter function.

Cheers,

Tim

**Comment by DannyDainton** [comment]
If you want to send me a PR, I can take a look. :)

**Comment by DannyDainton** [comment]
I'm going to close this issue for now, I'm personally not planning to add any changes like this but I'm happy to have a look at a PR and consider merging something in to the reporter.
