### ISSUE TITLE
[BUG] Markdown tables rendered incorrectly in report file

### ISSUE THREAD

**Issue by solomon2530** [DannyDainton/newman-reporter-htmlextra#322]
**What Are You Seeing**

Table written in markdown language on Postman is not rendered properly on htmlextra report

**Steps To Reproduce The Issue**

- Create a postman collection using tables inside the Documentation section. Since Postman allows only Markdown in the Documentation section, the tables would be in Markdown as well, something like this :

| CODE | STATUS        | RESULT                                                       |
| ---- | ------------- | ------------------------------------------------------------ |
| 200  | success       |                                                              |
| 404  | no_data_found | No saved  report found for the logged-in user                |

- Run the collection using newman and htmlextra to generate an html report
- Open the html report and open the Request Description section

**Screenshots and Gifs**

View in Postman :
![image](https://user-images.githubusercontent.com/24715190/122042066-5022b480-cdf7-11eb-8edd-b6d1b940c3f9.png)

View in htmlextra report : 
![image](https://user-images.githubusercontent.com/24715190/122042150-6892cf00-cdf7-11eb-9aa8-3ad9fc5c56e4.png)

**Collection and Environment Files**
JSON file type not supported here

**Version and Platform Information:**
 - `newman` version - 5.2.3
 - `newman-reporter-htmlextra` version - 1.21.0
 - OS - Windows 10 Enterprise v1909
 - The CLI command you've used to start Newman - newman run File.postman_collection.json --globals Globals.postman_globals.json --iteration-data Variables.csv -r htmlextra --reporter-htmlextra-export ./results/report.html

**Additional Context**

None

**Comment by praveendvd** [comment]
you can create a zip file with the collection and environment file , or just share the a public link to a demo collection

**Comment by solomon2530** [comment]
Attaching sample Postman collection (.zip file)
[Query.postman_collection.zip](https://github.com/DannyDainton/newman-reporter-htmlextra/files/6659496/Query.postman_collection.zip)

**Comment by praveendvd** [comment]
@DannyDainton  i tried adding pre tag and it looks clean instead of code , does it sound liek a good fix

**Comment by DannyDainton** [comment]
@praveendvd Do you have an example of what that would look like?

**Comment by DannyDainton** [comment]
Umm...that doesn't really look any better to me and this issue is purely for markdown tables and I'm not sure if changing the whole description view just for that is really worth it right now.

**Comment by praveendvd** [comment]
will see if something else could be done , but will concentrate on other two issues as of now then ❤️

**Comment by DannyDainton** [comment]
Cheers mate, that other ones do seem like something that needs more attention.

**Comment by praveendvd** [comment]
@DannyDainton :

![image](https://user-images.githubusercontent.com/45095911/125766835-81a0be24-8d9b-4061-b5d7-14e3083a8ce4.png)


```
code table, code th, code td {
    border: 1px solid black;
    width: max-content;
    padding: .75rem;
    text-align: center;
}
```

**Comment by DannyDainton** [comment]
How does this look with the rest of the description and for the different themes?

I think it's better with the text-align removed but if they are using the center markdown syntax, how does that look?

Just need to think about the wider uses rather than just solving this specific issue :D

**Comment by praveendvd** [comment]
> How does this look with the rest of the description and for the different themes?
> 
> I think it's better with the text-align removed but if they are using the center markdown syntax, how does that look?
> 
> Just need to think about the wider uses rather than just solving this specific issue :D

Wanted to see what looks good , once that decided i could check the effect on other fields , 😆

**Comment by praveendvd** [comment]
@DannyDainton 

it looks good 👍 

[examplereport.zip](https://github.com/DannyDainton/newman-reporter-htmlextra/files/6822396/examplereport.zip)

**Comment by DannyDainton** [comment]
@solomon2530 This fix will go out with the next release of the reporter - You have @praveendvd to thank for this 🏆

**Comment by solomon2530** [comment]
@DannyDainton I sure do. Looking forward to the next release.
@praveendvd  Thanks a ton! This will help a lot with proper documentation for my project. Kudos!
