### ISSUE TITLE
[BUG]  Filter field is occasionally not getting populated

### ISSUE THREAD

**Issue by praveendvd** [DannyDainton/newman-reporter-htmlextra#329]
**What Are You Seeing**

filter field missing and show only failures button doesn'e work

![image](https://user-images.githubusercontent.com/45095911/126009342-e6f3ce5e-eb0d-4933-9034-cd98987f0fb6.png)

console error:

![image](https://user-images.githubusercontent.com/45095911/126009415-4bcab43c-d07b-422a-9e00-4a65a04c273b.png)

**Steps To Reproduce The Issue**

can be reproduced only with below collection , no clue why :

Just click run.bat

[zip.zip](https://github.com/DannyDainton/newman-reporter-htmlextra/files/6833422/zip.zip)

**Version and Platform Information:**
 - `newman` version :  5.2.4 
 - `newman-reporter-htmlextra` version :  1.21.0
 - OS : win 10
 - The CLI command you've used to start Newman : 
 
 `newman run simple-skipped-folder.json -r htmlextra -d a.csv --reporter-htmlextra-export new.html`

**Additional Context**

only happens with this command and data file , don't know why

Any contextual information that might relate to the problem?

**Comment by DannyDainton** [comment]
I'm not sure I know what you mean by filter, can you attach a short recording of the behaviour?

**Comment by praveendvd** [comment]
@DannyDainton expected : 

![image](https://user-images.githubusercontent.com/45095911/126011392-7f17e700-3c81-4636-8c1b-d0e5f7d669dd.png)

**Comment by DannyDainton** [comment]
It's based on the number of iterations, I didn't really see the need to have a filter for say 5 iterations 😂

Seemed to be quite redundant. 😂

**Comment by praveendvd** [comment]
> It's based on the number of iterations, I didn't really see the need to have a filter for say 5 iterations 😂
> 
> Seemed to be quite redundant. 😂

ho i was banging my head to understand whats happening there

**Comment by praveendvd** [comment]
but the show failure is failing because of that , i wil lahve a look at it

**Comment by DannyDainton** [comment]
It's based on greater that 18 iterations, I think that's when there's a second row on tabs 🤔 - It's been a long time since I did that.

That part is controlled directly in the template.
