### ISSUE TITLE
The report shows requests that include sendRequest incorrectly

### ISSUE THREAD

**Issue by quangdang1** [DannyDainton/newman-reporter-htmlextra#331]
**Version and Platform Information:**
 - `newman` version: 5.2.3
 - `newman-reporter-htmlextra` version: 1.21.0
 - OS: win 10

Hi @DannyDainton,

In Postman, I called a POST request to verify the response and then in the Test tab, I called GET request as the image below:

![image](https://user-images.githubusercontent.com/39018630/127138883-ee298af9-12b5-46a8-9a01-b68f49b03d8c.png)

After that, I export to a collection file. Then I used newman and newman-reporter-htmlextra to run the collection and got a report as below: 
![image](https://user-images.githubusercontent.com/39018630/127139290-086d8e84-f7ae-46d4-9d6e-893d1fbcd29a.png)

As you can see in my report, it shows the GET request in Tests tab instead of the POST request as I expected. How can I make it show the request correctly?

Thanks

**Comment by DannyDainton** [comment]
Similar issue here - This a Newman related problem that impacts a lot of the reporters.

https://github.com/DannyDainton/newman-reporter-htmlextra/issues/241

**Comment by quangdang1** [comment]
Thanks @DannyDainton, I looked into #241, and noticed that the issue is not fixed yet, does it correct? So do have any suggestion for me?

**Comment by DannyDainton** [comment]
Not fixed by me, I don't own that project :D 

Unfortunately, I would suggest that if you're using `sendRequest` in your Collections, this reporter has the potential to show you incorrect information. 

I can only show what is sent from Newman, there isn't any real magic going on in this reporter, it's just displaying the information in a different way.

**Comment by quangdang1** [comment]
.Thanks you :)

**Comment by quangdang1** [comment]
Hi @DannyDainton, is there any way that we can send request in Postman instead of using pm.sendRequest()?

**Comment by DannyDainton** [comment]
You just open another request tab, fill in the details and hit send... 😁

Is there a reason why you can't do this?
