### ISSUE TITLE
html in report title

### ISSUE THREAD

**Issue by mims92** [DannyDainton/newman-reporter-htmlextra#332]
I am trying to use html tags (links) in the report title but they ends up being escaped/written in plain text.

Is it possible or something that would need to be implemented? 

Thank you

**Comment by DannyDainton** [comment]
Can you give me an example? 

I could try and guess but it would probably be better if you told me. 😂

**Comment by mims92** [comment]
Sure, here is a dummy example:
```
newman.run({
        collection: POSTMAN_COLLECTION_URL,
        environment: POSTMAN_ENVIRONMENT_URL,
        reporters: ['cli', 'htmlextra'],
        reporter: {
            htmlextra: {
                export: `newman-report.html`,
                browserTitle: `Newman report`,
                title: `<a href="https://google.com">Google</a>`,
                showFolderDescription: true,
                timezone: "Europe/Berlin"
            }
        }
    }, function (err) {
        if (err) {
            throw err;
        }
        console.log('[INFO] Collection run complete!');
    })

```

**Comment by DannyDainton** [comment]
That's just resolving that string value here in the template. It's just a string and I'm not going to changing the report template to anything else. 

```
<h1 class="display-{{titleSize}} text-center">{{title}}</h1>
```

The best thing about the report is that all of the control is with you, what you see is just a template the comes out of the box. 

You can make changes to a custom template and run it with htmlextra using adding the `template` property in that Newman run object.

**Comment by DannyDainton** [comment]
Closing as this isn't something that I'm going to be changing in the default report.

This can be handled in a custom template.
