### ISSUE TITLE
[BUG] Summary info is incorrect - Pre-requisite scripts and Test scripts count is incorrect

### ISSUE THREAD

**Issue by reachTushar** [DannyDainton/newman-reporter-htmlextra#333]
**What Are You Seeing**
![image](https://user-images.githubusercontent.com/70003241/128339658-2c424be2-4583-4134-9277-3daaa127f722.png)

A high-level description explaining the issue that you're facing. 
Pre-requisite scripts and Test scripts count is incorrect. 
1. In my collection I have not used Pre-requisite scripts anywhere, still the count shows up as 649.
2. What I understand is  the Test script count is same as Requests count in summary info. (when I ran a small collection I see request count and test script count are same).

**Steps To Reproduce The Issue**

**Screenshots and Gifs**
![image](https://user-images.githubusercontent.com/70003241/128340233-c62dae14-cbb6-4d15-8e50-794c905e350f.png)

**Collection and Environment Files**

Any files that would allow me to reproduce the issue locally...

**Version and Platform Information:**
 - `newman` version  - 5.2.2
 - `newman-reporter-htmlextra` version - 1.20.1
 - OS  - Windows 10
 - The CLI command you've used to start Newman  -newman run "account.postman_collection.json" -e "Staging.postman_environment.json" --reporters=cli,htmlextra

**Additional Context**

Any contextual information that might relate to the problem?

**Comment by DannyDainton** [comment]
That information is coming from Newman, I haven't got in the reporter that does anything with that data. It's just showing what's reported from Newman. 

Do you see the same in the CLI reporter summary table?

**Comment by reachTushar** [comment]
Yes Danny, same info can be seen in the CLI reporter table- please let know whom to contact in this case or what can be done
![image](https://user-images.githubusercontent.com/70003241/128470580-cde0f750-ad9a-4315-80bb-87231206b699.png)

**Comment by DannyDainton** [comment]
The Newman project owns all that code, it's one of the built in reporters.

I'm going to close this issue out as it's not related to anything that I can fix here.
