### ISSUE TITLE
[Feature Request] any way in a day if I have 10 reports, if we can create consolitated report for all of them

### ISSUE THREAD

**Issue by kalemayur8** [DannyDainton/newman-reporter-htmlextra#338]
If in a single day let's say I have generated 10 reports. If those are present in a single folder & If we can append each run's abstract summary to the one consolidated HTML and give a link of each run's report to it.

In this way, we can have one consolidated report page of all runs that happened in a day or week

**Comment by DannyDainton** [comment]
That would take some other service or database storing the data for each run, then at the end of the week displaying that in a meaningful way. This reporter wouldn't ever do that.

You can take a look at creating a new reporter that could push the Newman data somewhere for you to read it at a later date?

**Comment by DannyDainton** [comment]
I'm going to close this as an issue, as it's not something that's going to happen in this project.

More than happy to continue a conversation about it though. :D

**Comment by kalemayur8** [comment]
@DannyDainton appreciate your response.

**Comment by DannyDainton** [comment]
Sorry it's not something I can say 'yep, let's do it' but it's actually quite a big change to make and something that would probably be done better away from this reporter.
