### ISSUE TITLE
Option to get console.warn included in the report.

### ISSUE THREAD

**Issue by frille70** [DannyDainton/newman-reporter-htmlextra#341]
Just like the option to include console log (--reporter-htmlextra-logs) it would be great if you can choose to include warnings from console.warn statements, like --reporter-htmlextra-warn

**Comment by DannyDainton** [comment]
Do these not come through with that flag?

Do you have an example image of what that looks like? 

The event where it gets that data from is 'console' so if its not within that array from Newman, I wouldn't be able to add it into the report.

https://github.com/postmanlabs/newman#newmanrunevents

**Comment by frille70** [comment]
Hi
Yes, the option to show console logs are also showing the console.warn. I did not realize that. Ticket can be closed
