### ISSUE TITLE
[Feature Request] Support Inline HTML Rendering under test information

### ISSUE THREAD

**Issue by SamuelVinay91** [DannyDainton/newman-reporter-htmlextra#342]
When user wants to display data tables this should able to accept the HTML format and display accordingly

**Comment by SamuelVinay91** [comment]
![image](https://user-images.githubusercontent.com/19383833/136998113-30b43e66-b1ab-4167-81db-2adf75d460a6.png)


Initial screenshot was from different reporter for reference.

Steps:

1. we will be doing some logical comparison of jsons and display as an HTML format of that result 
![image](https://user-images.githubusercontent.com/19383833/136998608-058565cd-a1a5-4fcb-88aa-111030baf8ef.png)
2.Once this data table is generated, our expectation is our reporter is able to render this HTML code and display as a table with comparisons

**Comment by DannyDainton** [comment]
Like I said, I personally wouldn't be adding this into the reporter. If you wanted to add it and create a PR I'm happy to review it. 

It's also something that could probably be handled in a custom template, depending on how you want to achieve that.

The reporter uses a template to create the final report but you can use your own and present the data in a way that suits your context.

**Comment by DannyDainton** [comment]
This isn't something that I'm going to be doing.

Closing the issue.
