### ISSUE TITLE
Store html report in github actions

### ISSUE THREAD

**Issue by quesadap** [DannyDainton/newman-reporter-htmlextra#348]
Hi Danny, 

My manager ask me if there is a way to store the html report in github actions. He want to open the html report directly, and not save in his local. I did some research and I didn't find anything useful. Do you know if it something possible to do? 

Btw, we are using the next code for generate the report:

# Archive test report
    - name: Archive report
      # Always run (even on failures)
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: results/report.html

Thanks in advance

**Comment by DannyDainton** [comment]
Storing things in Github Actions isn't really anything that I can help with as it's not really htmlextra specific. :( 

- Is it just not working (failing to store)?
- What's your Newman run command? 
- Are you using the `--reporter-htmlextra-export` flag?

Anything in there docs that can help you:

https://docs.github.com/en/actions/advanced-guides/storing-workflow-data-as-artifacts

**Comment by DannyDainton** [comment]
Hey @quesadap 

Did you get any further with this? I'm going to close the issue as there isn't really anything I can do here in terms of the reporter but happy to continue the conversation in the thread.

**Comment by quesadap** [comment]
Thanks Danny! sorry for the delay in my answer

**Is it just not working (failing to store)?**

The idea is to open the html report directly from github, now an artefact is generated and you have to download to your local and then open it. My manager wants to open directly in a new tab.

**What's your Newman run command?**


newman run "collection_name.json" -e environment_name.json -d data.json -r cli,htmlextra --reporter-htmlextra-browserTitle	"Title Tests" --reporter-htmlextra-title	"Title test" --reporter-htmlextra-export results/report.html

I'm checking the doc that you shared with me. 

thanks again!

**Comment by DannyDainton** [comment]
That's all on the GitHub side I'm afraid, my reporter just creates the report that's stored. 

One of the only tools that I've seen it open the report in the same place was using Jenkins 😬

**Comment by quesadap** [comment]
good to know, thanks again Danny!
