### ISSUE TITLE
Log pollution and job failures created by the colors.js dependency

### ISSUE THREAD

**Issue by floppyrom** [DannyDainton/newman-reporter-htmlextra#350]
I am using the latest version of the reporter (installed with npm install -g newman-reporter-htmlextra).

When I run my newman builds with the htmlextra reporter I get this error and all my builds are failing. I think it's related to the colors.js issue (https://www.bleepingcomputer.com/news/security/dev-corrupts-npm-libs-colors-and-faker-breaking-thousands-of-apps/)

and I get this in the logs of my builds:
LIBERTY LIBERTY LIBERTY
LIBERTY LIBERTY LIBERTY
LIBERTY LIBERTY LIBERTY
                                   !             H|H|H|H|H           H__________________________________             H|��|��|��|H           H|* * * * * *|---------------------|             H|��|���|��|H           H| * * * * * |---------------------|             H|��|��|��|H           H|* * * * * *|---------------------|             H|H|H|H|H           H| * * * * * |---------------------|             H|H|H|H|H           H|---------------------------------|          ===============        H|---------------------------------|            /| _   _ |          H|---------------------------------|            (| O   O |)          H|---------------------------------|            /|   U   |          H-----------------------------------             |  =/  |           H              _..._/            H              _|I/|_            H      _______/| H |/_______    H     /           / /          H    |          | | /         |  H    |          ||o||          |  H    |    |     ||o||     |    |  H    |    |     ||o||     |    |  H   Carl Pilcher  
t��������������������������������������e����������������������������������������������������������������������������������������������s��������������������������������������t������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������i������������������������������������������������������n����������������������������������������������������������������������������������������������������������������������������������������������������������g���������������������������������� ���������������������������������������������������� ���������������������������������� ����������������������t��������������������������������������������������������������������������������������������������������e������������������������������������������������������������������������������������������������������������������������s����������������������������������������������������������������������������������������������������������������������t������������������

**Comment by DannyDainton** [comment]
My bad, I did make that change on the repo last week but didn't publish a new version 😢 

I've published 1.22.4 with the changes, you're probably going to need to do a full uninstall/install of the reporter or potentially drop the node_modules and install again.

Completely my fault, apologies for any inconvenience this has caused.

**Comment by DannyDainton** [comment]
Let me know if that's solved your issue, if not we can work together to get you going again.

**Comment by floppyrom** [comment]
Hi Danny

Apologies for the late reply (I had some other technical issues which prevented me to rerun my tests). It's working right now, so I can confirm your fix. Thanks again.

**Comment by DannyDainton** [comment]
Glad it's all sorted. Closing this out now.
