### ISSUE TITLE
[Feature Request] Disable console output

### ISSUE THREAD

**Issue by Lorkenpeist** [DannyDainton/newman-reporter-htmlextra#351]
**Is your feature request related to a problem? Please describe.**
The console output that htmlextra produces (version, progress bar, created report) is cluttering my CLI.

**Describe the solution you'd like**
An option to disable said console output.

**Describe alternatives you've considered**
I was able to suppress the progress bar and the end message by enabling newman's built-in progress bar with option `{silent: true}`, and suppress the start message by setting `console.log = function () {}` in my own script.  But I had to dig in the htmlextra source code to figure that out, and it's still a hackish solution.  (Incidentally, the start message logs even when the htmlextra progress bar is suppressed, but the end message only logs when the htmlextra progress bar is also enabled, which is inconsistent and seems like it might be unintentional.)

**Additional context**
I am using a custom script to run many collections in parallel, which outputs a 1-line summary to console when each collection finishes.  I just tried using htmlextra instead of html and now I am getting 4 lines per collection, 3 of which are from htmlextra.

**Comment by DannyDainton** [comment]
Hey @Lorkenpeist 👋🏻 

Your use case would cause multiple outputs as your running collections in parallel, Newman would still remain a 1 for 1 running of the collection and each run would be a separate report. I can see why having that polluting the logs wouldn't be a great experience when run in parallel.

Sounds like you've been having a look at it already - Would you like to make that change and submit a PR?

**Comment by DannyDainton** [comment]
I went ahead and removed the option to display the progress bar by default, you would now need to supply the flag to see this in the CLI.

![image](https://user-images.githubusercontent.com/17089546/151358413-117637c9-a29d-49a7-824c-7ccce3f538d1.png)

**Comment by Lorkenpeist** [comment]
Awesome, thanks for the quick turnaround! I'm already loving the improved HTML reports :)
