### ISSUE TITLE
Htmlextra-darktheme not showing red or green on total requests. 

### ISSUE THREAD

**Issue by lucas937** [DannyDainton/newman-reporter-htmlextra#36]
Hello Danny, 

the htmlextra-darktheme is not showing green or red on the total requests page. If i remember correctly it did some time ago. Also if i remeber correctly you implemented pagination, i have onver 5000 iterations and sometimes its a bit hard to keep track of where i have clicked. 

Thanks! 

Ill attach a printscreen.

![image](https://user-images.githubusercontent.com/48093059/56193126-36775e00-6030-11e9-8c25-091552a6066b.png)

**Comment by lucas937** [comment]
Update,

The htmlextra reporter does not show this either. (the "default" reporter") 
![image](https://user-images.githubusercontent.com/48093059/56196019-5578ee80-6036-11e9-8b45-02a3eee5e59f.png)

**Comment by lucas937** [comment]
Sorry, my bad. I checked previous issues i had opened and we only discussed that option of having green and red. Thats why i had a memory of it. Ill close this issue. 

But it would be nice to have :)

**Comment by DannyDainton** [comment]
This has _never_ been there :) - You sent a message and an image a while ago about adding this to the reporter but I never got round to completing it. A combination of no time and the lack of knowledge around the best way to do this prevented me from doing the work. 

https://github.com/DannyDainton/newman-reporter-htmlextra/issues/16#issue-416670153

It's on my list of things to, like a cleaner way to handle the pagination. It will continue to do this in the UI if you have more than 21 iterations. 

If you want to change this on your side and send me a pull request, I can look to add it to the reporter. 

The only other option is to create a custom template on your side, to show the data in the way that you want to see it. The underlying data from newman is the same, the template just changes what you see.

**Comment by lucas937** [comment]
Yeah i noticed that haha.. 

Im guessing you could just use the same code you are using for the iteration information under each tab.  Because that is showing red or green. Unfortunately i have never coded in html, css, handlebars and bootstrap. But ill see if i can hide som help

**Comment by DannyDainton** [comment]
I had something _like_ that but I found it tough to simulate a failed iteration, in a group of successful ones.  

All the runs were Green and I wasn't happy that It was doing what I wanted it to do. Visually it looked correct but I didn't have the confidence to commit the change.

**Comment by lucas937** [comment]
Could you provide me with a code snippet of what you implemented? i could have a look at it. 

You are doing a great job :)

**Comment by DannyDainton** [comment]
I'll grab it later and send it across. Appreciate the support! :)

**Comment by DannyDainton** [comment]
I've looked and I can't find/remember how I did it now. I know it was looking at the fails in the iterations and then added the class according to the result, to change the `background` colour on the tab.

If I get some time I'll have a look at it again and try and remember. Should have committed it back then :(
