### ISSUE TITLE
Report missing content-type

### ISSUE THREAD

**Issue by vbisbest** [DannyDainton/newman-reporter-htmlextra#366]
### Is There An Existing Issue

- [X] I have searched the [issue tracker](https://github.com/DannyDainton/newman-reporter-htmlextra/issues) for similar problems.

### What Are You Seeing

In the requests view of the report, the content-type header is missing.   I know newman is sending the header by using a proxy, however it does not show up in the report.

### Steps To Reproduce The Issue

1. Run any postman collection and look for content-type in the html report.

### Full Newman Command Or Node Script

```bash
NA
```

### HTMLEXTRA Version

1.22.5

### Newman Version

5.3.1

### Additional Context

NA

**Comment by DannyDainton** [comment]
As the reporter has flags to omit certain pieces of data from the report, the command you use is very applicable.

Can you provide a visual example of the header not being there, at the moment the information that you have provided isn't enough for me to investigate the issue.

**Comment by vbisbest** [comment]
Thank you for your response.   Here is the request from postman (confirmed it works the same with newman).  Notice the content-type header
![Screen Shot 2022-02-23 at 4 53 31 AM](https://user-images.githubusercontent.com/3143293/155297981-f1aac725-c04d-4426-87b9-f51b4d97acd7.png)

And here is the report (notice content-type is missing)
![Screen Shot 2022-02-23 at 5 03 28 AM](https://user-images.githubusercontent.com/3143293/155298063-e28fcb7d-e01e-4430-bf17-ef76f0bc81e5.png)

**Comment by vbisbest** [comment]
Also, I think the issue is in newman.  I logged the same issue over there.  Basically their "request" hook is not including the content-type header.  Its like it gets added after that function.
https://github.com/postmanlabs/newman/issues/2935

**Comment by DannyDainton** [comment]
The reporter will only display what's coming from the Newman Summary Object - If that's not in that output, then it wouldn't be shown on the final report. 

There's not a great deal that I can do here, to be honest. 😢

**Comment by vbisbest** [comment]
It was a shot in the dark.  I appreciate you taking a look.  Thanks.
