### ISSUE TITLE
Newman run with the htmlextra reporter is stuck and not running the collection

### ISSUE THREAD

**Issue by bheemreddy181** [DannyDainton/newman-reporter-htmlextra#374]
### Is There An Existing Issue

- [X] I have searched the [issue tracker](https://github.com/DannyDainton/newman-reporter-htmlextra/issues) for similar problems.

### What Are You Seeing

newman run stuck with -r htmlextra 
<img width="1884" alt="Screen Shot 2022-03-25 at 9 55 31 AM" src="https://user-images.githubusercontent.com/101338506/160145905-8e596f9e-00d9-417f-9b7a-21d57e6ae53f.png">

### Steps To Reproduce The Issue

1. newman run with -r htmlextra

### Full Newman Command Or Node Script

```bash
newman run <PATH> -e <PATH> -k true -r htmlextra
```

### HTMLEXTRA Version

1.22.7

### Newman Version

5.3.2q

### Additional Context

with node V17.8.0 on mac Monterey without html extra newman jobs runs perfectly 
<img width="852" alt="Screen Shot 2022-03-25 at 10 03 32 AM" src="https://user-images.githubusercontent.com/101338506/160146709-3b0dddfa-f295-49ae-9aff-61eceb99d701.png">

**Comment by DannyDainton** [comment]
Hey @bheemreddy181 

With the details that you have provided, there's very little I can do, I wouldn't be able to recreate that. Help me to help you by providing more context and expand on any debugging steps that you have done, for example:

- Is this happening for all reporters?
- Have you tried with a different collection?
- Have you tried uninstalling and installing the reporter?
- Have you tried running it in a different terminal? 

Also `-k true` isn't valid so it would probably fail (in silent by the looks of it) as it's looking for something called `true` in that command.

Try this instead - `newman run <PATH> -e <PATH> -k -r htmlextra`

**Comment by bheemreddy181** [comment]
I will try to add as much as information i can Danny. I agree there is very little info out there. 

- Is this happening for all reporters?
    _No Other reports work fine_ 
<img width="1728" alt="Screen Shot 2022-03-26 at 7 28 21 AM" src="https://user-images.githubusercontent.com/101338506/160239974-71d5c624-65e6-4b49-8f54-f82f6e9993bd.png">

- Have you tried with a different collection?
   _Yes, i did try different collections - same issue_ 
<img width="1728" alt="Screen Shot 2022-03-26 at 7 42 43 AM" src="https://user-images.githubusercontent.com/101338506/160239981-d1b1a191-2d1f-4f78-a736-49d36ad7a47b.png">

- Have you tried uninstalling and installing the reporter?
  _Yes, I did try that, I was facing a similar issue. I did full uninstall and install._
- Have you tried running it in a different terminal?
 _Yes did try that. same issue_

I updated the command -k. are there any log files I should look at?

**Comment by DannyDainton** [comment]
Do you use `nvm`? Have you tried a different version of node?

**Comment by bheemreddy181** [comment]
I tried switching from v17 to v10 for node 
<img width="1728" alt="Screen Shot 2022-03-26 at 7 58 29 AM" src="https://user-images.githubusercontent.com/101338506/160240507-f0fc1545-deed-4f93-8691-263fa1b0f82a.png">

**Comment by DannyDainton** [comment]
I have absolutely no idea what's happening then. 🤔

To be honest, the weekly downloads are at about 80k and I haven't seen a report about it doing this for them.

I suspect it's some kind of environmental issue with your set up - it's the only thing I can think of. 😞

You can do a full global uninstall of Newman and the reporter and reinstall again.

```
npm uninstall -g newman newman-reporter-htmlextra
```

Then do

```
npm install -g newman newman-reporter-htmlextra
```

I'm just suggesting anything now as I honestly don't know what's happening.

**Comment by bheemreddy181** [comment]
I feel the same could be my setup that is causing the issue, I will try this over a different VM and will let you know.

**Comment by DannyDainton** [comment]
Any luck with this issue? Were you able to try this in a different environment?

**Comment by bheemreddy181-zz** [comment]
Not yet Danny.I will close this for now as we have not seen others reporting it. I will figure out about it on a VM or CI env this week.

**Comment by bheemreddy181** [comment]
Working fine on a different VM. Thanks for the insights and help, Danny.
