### ISSUE TITLE
[Bug] Default template, theme switch error

### ISSUE THREAD

**Issue by IceBjerg** [DannyDainton/newman-reporter-htmlextra#383]
### Is There An Existing Issue

- [x] I have searched the [issue tracker](https://github.com/DannyDainton/newman-reporter-htmlextra/issues) for similar problems.

### What Are You Seeing

When loading a report, generated by the htmlextra reporter, the default switch is always showing OFF, however the site loads correctly, with the last used theme. (tested on Chrome 101) 

The error I get is the following (in console:)
```
Uncaught ReferenceError: $ is not defined
```
From this line of code: 
```
$(document).ready( function () {
     document.getElementById('slider').checked = sliderChecked
});
```

What I think is happening is that the script wants to use JQuery, but is not yet loaded. 

One of a solution I can think of, is to move the highlighted code after jQuery has already been loaded. 

### Steps To Reproduce The Issue

1. Run Newman using the command in the terminal
2. Host the new htmlextra report in a server
3. Open the report in the browser
4. Change the theme
5. Reload the page

### Full Newman Command Or Node Script

```bash
newman run postman_collection.json -r htmlextra,cli --reporter-htmlextra-export ./results/report.html
```

### HTMLEXTRA Version

latest

### Newman Version

latest docker image

**Comment by DannyDainton** [comment]
Thanks @IceBjerg

I'm 99% sure I introduced this issue recently 😢 - I'll take a look tomorrow and see what's happening.

PRs are always welcome too ❤️

**Comment by IceBjerg** [comment]
Hi! 

I fixed the issue locally, and I tried to commit to a newly created branch: bugfix/default_output_theme_switch, but I was not able to. I have no permission to do that. How can I make a pull request with my changes?

**Comment by IceBjerg** [comment]
I created a PR. :)

**Comment by DannyDainton** [comment]
Looks good, this could have also been fixed by adding jquery in the template above the function. :D 

I've merged it now, I'll sort out the package stuff later and add your name to the readme 😄

**Comment by IceBjerg** [comment]
Thanks :) 
Yeah, it could have been solved with the fix you mentioned as well :)

**Comment by DannyDainton** [comment]
I've pushed out a new version and updated the project to include your name 🏆
