### ISSUE TITLE
newman: could not find "htmlextra --reporter-htmlextra-title "ABC " --reporter-htmlextra-export ABC.html" reporter 

### ISSUE THREAD

**Issue by ShilpaSachdeva** [DannyDainton/newman-reporter-htmlextra#385]
### Is There An Existing Issue

- [X] I have searched the [issue tracker](https://github.com/DannyDainton/newman-reporter-htmlextra/issues) for similar problems.

### What Are You Seeing

I am trying to run my collections in parallel using https://github.com/postmanlabs/newman/blob/develop/examples/parallel-collection-runs.js.
In options, i give reporter as htmlextra
reporters: ('htmlextra --reporter-htmlextra-title "ABC_Test " --reporter-htmlextra-export abc.html')
In gitlab-ci.yml, i have 
image: 
  name: dannydainton/htmlextra
  entrypoint: [""]

stages:
    - build
    - test

install_dependencies:
  stage: build
  script:
    - npm install

  artifacts:
    paths:
      - node_modules/
      
cache:
  paths:
    - node_modules/

api_testing:
  stage: test
  script: npm test (this runs parallel.js file)
  artifacts:
        paths:
          - abc.html
 package.json looks like:

{
  "name": "parallelrun",
  "version": "1.0.0",
  "description": "",
  "main": "parallel.js",
  "scripts": {
    "test": "node parallel.js"
  },
  "dependencies": {
    "async": "3.2.3",
    "newman": "^5.3.2",
    "newman-reporter-htmlextra": "^1.22.8"
  }
}

  

### Steps To Reproduce The Issue

Running locally or in pipeline gives same error 
newman: could not find "cli, htmlextra --reporter-htmlextra-title "ABC " --reporter-htmlextra-export abc.html" reporter
  ensure that the reporter is installed in the same directory as newman
  please install reporter using npm

### Full Newman Command Or Node Script

```bash
Locally in terminal
npm init (will install dependency from package.json)
node parallel.js (will execute similar file https://github.com/postmanlabs/newman/blob/develop/examples/parallel-collection-runs.js
but with reports in option as mentioned above )
```

### HTMLEXTRA Version

1.22.8

### Newman Version

5.3.2

**Comment by DannyDainton** [comment]
What's this doing?

```
reporters: ('htmlextra --reporter-htmlextra-title "ABC_Test " --reporter-htmlextra-export abc.html')
```

That property is for adding reporters, not the flags for the reporters.
```
reporters: ('htmlextra')
```
