### ISSUE TITLE
Missing license file

### ISSUE THREAD

**Issue by joeyphant** [DannyDainton/newman-reporter-htmlextra#40]
Sadly there seems to be no license file included in the repository.
While there is the Apache license mentioned in the readme (https://github.com/DannyDainton/newman-reporter-htmlextra/blob/master/LICENSE.md), the file is not there and shows a 404.

**Comment by DannyDainton** [comment]
Good spot @joeyphant 

I've added the file in there now. Appreciate you posting the issue. 👍
