### ISSUE TITLE
Unable to skip specific request (folder) to generate htmlextra report

### ISSUE THREAD

**Issue by Escape147** [DannyDainton/newman-reporter-htmlextra#403]
### Is There An Existing Issue

- [X] I have searched the [issue tracker](https://github.com/DannyDainton/newman-reporter-htmlextra/issues) for similar problems.

### What Are You Seeing

When the --reporter-htmlextra-skipRequests (--reporter-htmlextra-skipFolders) parameter is used to run the command, the number of Skipped Tests in the generated report is 0

### Steps To Reproduce The Issue

1. Run Newman using the command in the terminal
2. Open the new htmlextra report in a browser window
3. Click on the 'Skipped Tests' tab
4. No statistics requested

### Full Newman Command Or Node Script

```bash
Command1：newman run Test-skip.postman_collection.json -e Test.postman_environment.json -r htmlextra --reporter-htmlextra-skipRequests "request name with InvalidParameterException"
Command2：newman run Test-skip.postman_collection.json -e Test.postman_environment.json -r htmlextra --reporter-htmlextra-skipFolders "folder name with Error code"
```

### HTMLEXTRA Version

1.22.11

### Newman Version

5.3.2

### Additional Context

![image](https://user-images.githubusercontent.com/86993268/216497216-51ff2424-173c-4fa5-9850-83050bf5b9c3.png)

**Comment by DannyDainton** [comment]
Hey @Escape147,

That flag only relates to what is displayed in the final report:

<img width="966" alt="image" src="https://user-images.githubusercontent.com/17089546/216588530-4370f2ce-1dad-43f1-96e7-bf34fef414ec.png">

The `Skipped Tests` section relates to any tests that you have within your Collection file that use the `pm.test.skip` option.

```
pm.test.skip("Status code is 200", function () {
    pm.response.to.have.status(200);
});
```

**Comment by Escape147** [comment]
@DannyDainton 
- Thank you very much for your reply, I have solved the problem. Want to know what the final report in your description refers to?
![image](https://user-images.githubusercontent.com/86993268/216863969-b318a33d-5363-444a-a481-638d80ad9f65.png)

**Comment by DannyDainton** [comment]
The final report that's created. There's only 1 report that gets created but that could be displaying anything based on flags that might be used.

**Comment by DannyDainton** [comment]
If you solved the problem and you no longer have an issue - Can we close this out?

There isn't anything that I'll be changing on my side for this.

**Comment by Escape147** [comment]
Mmm Good

**Comment by Escape147** [comment]
Mmm Good
