### ISSUE TITLE
Remove request headers from HTML output

### ISSUE THREAD

**Issue by bassie1995** [DannyDainton/newman-reporter-htmlextra#41]
Would it be possible to not show certain elements in each request?
I'd like to, for example, remove Authorization request headers.

I'm thinking inside the options, we could do some kind of array or object with values to edit/remove?
I thought about changing the template, but having it in by default is always better than having to update my 'local' one all the time :)

Would you like me to try and take a look at it, then submit a PR?

**Comment by DannyDainton** [comment]
Sure, create a PR and I'll have a look.

**Comment by DannyDainton** [comment]
Hey @bassie1995

I'm going to close this for now, it's not something I'm working on personally. 

If you get a PR together I can review and bring into the reporter.

**Comment by bassie1995** [comment]
Yep, no problem! I didn't manage to get this pulled into the current sprint, so I have to hold off on this one for now :(

Once I get it up and running, I'll drop a PR!
