### ISSUE TITLE
Not able to run postman tests with report generation 

### ISSUE THREAD

**Issue by ShravanNeelaiahgari** [DannyDainton/newman-reporter-htmlextra#411]
### Is There An Existing Issue

- [X] I have searched the [issue tracker](https://github.com/DannyDainton/newman-reporter-htmlextra/issues) for similar problems.

### What Are You Seeing

I see below error on github action and does not run tests: 

Run newman run ./PostmanPOCRest.postman_collection.json -r htmlextra
  newman run ./PostmanPOCRest.postman_collection.json -r htmlextra
  shell: /usr/bin/bash -e {0}

### Steps To Reproduce The Issue

Run sample postman collection on github action 

### Full Newman Command Or Node Script

```bash
# INstall Node on the runner
    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"
          
    # Install the newman command line utility and also install the html extra reporter
    - name: Install newman
      run: |
        npm install -g newman
        npm install -g newman-reporter-htmlextra
        npm install -S newman-reporter-htmlextra

    # Make directory to upload the test results
    - name: Make Directory for results
      run: mkdir -p testResults

    # Run the POSTMAN collection
    - name: Run POSTMAN collection
      run: |
        newman run ./PostmanPOCRest.postman_collection.json -r htmlextra
```

### HTMLEXTRA Version

latest

### Newman Version

latest

**Comment by DannyDainton** [comment]
Hey @ShravanNeelaiahgari

Have you tried using the `--reporter-htmlextra-export <filepath>` in the Newman command?

By default, it created a `/newman` directory and adds the reports in there but it looks like you're specifing that results go somewhere else, without actually telling Newman.

**Comment by DannyDainton** [comment]
Closing this issue. No response after 1 month.
