### ISSUE TITLE
htmlextra-extended is not working with junit reporter

### ISSUE THREAD

**Issue by gurdeeppruthi** [DannyDainton/newman-reporter-htmlextra#414]
### Is There An Existing Issue

- [X] I have searched the [issue tracker](https://github.com/DannyDainton/newman-reporter-htmlextra/issues) for similar problems.

### What Are You Seeing

When I use htmlextra-extended report alongwith junit report, newman is only generating html and not generating the junit report.

This working fine when I use htmlextra along with junit report, then both reports are getting generated.

The issue is only when i use junit with htmlextra-extended

Please could you fix this issue?

I have to use htmlextra-extended report only because it provides the features of provided iteration names instead of iteration numbers in the report and I need that feature.

Thanks in advance.

htmlextra-extended version: 2.1.4

### Steps To Reproduce The Issue

This generate both the reports:

newman run "myCollection.json" --environment "myEnvironment.json" -d "myDataFile.csv" --reporters cli,junit,htmlextra

This only generates html report:

newman run "myCollection.json" --environment "myEnvironment.json" -d "myDataFile.csv" --reporters cli,junit,htmlextra-extended

### Full Newman Command Or Node Script

```bash
newman run "myCollection.json" --environment "myEnvironment.json" -d "myDataFile.csv" --reporters cli,junit,htmlextra-extended
```

### HTMLEXTRA Version

1.22.11

### Newman Version

5.3.2

### Additional Context

Please could you look into it and advise?

**Comment by DannyDainton** [comment]
Hey @gurdeeppruthi 

It's not something that I'm going to be doing on my reporter - Feel free to add that feature behind a flag and I'll review a PR.

**Comment by gurdeeppruthi** [comment]
Unfortunately, I don't know how to do it as I am new to this. Hoping someone else could pick it up as it is a useful feature. Thanks.
