### ISSUE TITLE
Timestamp different than my local time

### ISSUE THREAD

**Issue by keremcankabadayi** [DannyDainton/newman-reporter-htmlextra#42]
Hi there, I'm using this great template to produce fancy reports from newman but creating time of report is different than my local time. For example, report time is 18:29 but my local pc time is 21:29. Any idea how to fix this?

**Comment by DannyDainton** [comment]
Hey, 

I'm away from home at the moment so I can take a look when I'm back if that's cool? 

It's using the `helper-moment` module to create that timestamp using the following syntax:

`{{moment date format="dddd, DD MMMM YYYY HH:mm:ss"}}`

The Newman summary object does have a timestamp, which is in a different format, this _might_ help but at the moment I have no way to test it 😔

**Comment by keremcankabadayi** [comment]
I found out this helper info inside docs but there is no sign about timezone. I think my issue is about timezone.

**Comment by DannyDainton** [comment]
If swap the moment syntax in the template for this `{{timestamp}}` - it might change it to be timezone specific but the format with be different.

Easiest way to check this is to create a template and use that handlebars variable in there. You can point to another template using the `--reporter-htmlextra-template <path>` cli argument.

**Comment by DannyDainton** [comment]
Are you running Newman on a remote machine or something? I'm sure it just using the system time of the machine it's running from?

I'm not really sure what else it could be...

**Comment by bassie1995** [comment]
There's an issue for that in the moment-helper repo: https://github.com/helpers/helper-moment/issues/6.

Maybe fork it, or you could add an option to manually specify an 'offset' off CEST?

**Comment by DannyDainton** [comment]
Hey @keremcankabadayi,

I don't think this is a specific issue with the reporter - Feels more like either an environment or `helper-moment` problem. 

I'm going to close this for now but can reopen if you provide more information around the problem.

**Comment by keremcankabadayi** [comment]
I fixed the problem. I'm using Docker to run tests. Inside my Dockerfile, I added next lines to solve this problem.

```
ENV TZ=Europe/Istanbul

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
```

**Comment by Crustacean** [comment]
thanks, @keremcankabadayi this worked like a charm
