### ISSUE TITLE
newman-reporter-htmlextra 'not found' when running in kubernetes cluster

### ISSUE THREAD

**Issue by mastafadhil** [DannyDainton/newman-reporter-htmlextra#433]
### Is There An Existing Issue

- [X] I have searched the [issue tracker](https://github.com/DannyDainton/newman-reporter-htmlextra/issues) for similar problems.

### What Are You Seeing

I am running my pipeline by using kubernetes cluster with docker image that installs :
node - v20.11.1
npm - v9.4.0
newman - v6.1.2
newman-reporter-htmlextra - v1.23.1

the issue appears that the pipeline is not able to detect newman-reporter-htmlextra after successfully installed it, thus unable to generate reports from the run. Would really appreciate if anyone could help me on this. Thank you so much in advance.

### Steps To Reproduce The Issue

stage('Run Postman Tests') {
            steps {
                script {
                    try {
                        container('python') {
                            sh '''
                                cd Postman
                                
                                npm install -g newman-reporter-htmlextra --cache=".htmlextra_global"
                                newman-reporter-htmlextra -v
                                newman run https://api.postman.com/collections/abc' -e "env.postman_environment" -r cli,htmlextra --reporter-htmlextra-export "/home/jenkins/agent/workspace/QA Pipeline/Postman/Reports/Test-Server_IT-Manager_$(date +'%Y%m%d_%H%M%S').html"
                                
                            '''
                        }
                    } catch (Exception e) {
                        // Handle the error here if needed
                        echo "An error occurred: ${e.message}"
                    }
                }
            }

### Full Newman Command Or Node Script

```bash
+ npm install -g newman-reporter-htmlextra '--cache=.htmlextra_global'
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

added 165 packages in 8s

13 packages are looking for funding
  run `npm fund` for details
+ newman-reporter-htmlextra -v
1.23.1
+ date '+%Y%m%d_%H%M%S'
+ newman run 'https://api.postman.com/collections/abc' -e env.postman_environment -r cli,htmlextra --reporter-htmlextra-export '/home/jenkins/agent/workspace/QA Pipeline/Postman/Reports/Test-Server_IT-Manager_20240404_062218.html'
**newman: could not find "htmlextra" reporter
  ensure that the reporter is installed in the same directory as newman
  please install reporter using npm**
```

### HTMLEXTRA Version

1.23.1

### Newman Version

6.1.2

**Comment by DannyDainton** [comment]
Hey @mastafadhil

Newman and the reporter need to be installed in the same directory. 

Are you able to do a `which` command or the equivalent on that OS to see where they are both getting installed?

**Comment by mastafadhil** [comment]
hey Danny,

Sorry for the late response. I tried to do 'which' for both newman and newman-reporter-htmlextra and apparently theyre not installed on the same directory, but even when i tried to do a 'cp' to transfer newman-reporter-htmlextra into the same directory in the script it still couldnt be found.

However, i finally managed to make it work by installing it directly in the pipeline, instead of having it pre-installed in the Dockerfile, now the pipeline is able to run the postman scripts and generate reports into the correct directory declared in the script. Here's a snippet of a working pipeline script :

stage('Run Postman Tests') {
            steps {
                script {
                    try {
                        container('python') {
                            sh '''
                                cd Postman
                                
                                npm install -g newman-reporter-htmlextra --cache=".htmlextra_global"
                                newman-reporter-htmlextra -v
                                newman run https://api.postman.com/collections/abc?access_key=abc -e "env.postman_environment" -r cli,htmlextra --reporter-htmlextra-export "/home/jenkins/agent/workspace/QA Pipeline/Postman/Reports/Test-Server_IT-Manager_$(date +'%Y%m%d_%H%M%S').html"
                            '''
                        }
                    } catch (Exception e) {
                        // Handle the error here if needed
                        echo "An error occurred: ${e.message}"
                    }
                }
            }

**Comment by DannyDainton** [comment]
It seems like you have solved the issue. That's great.

That error message doesn't come from my reporter, it's from the Newman code and happens for any reporter that's been mentioned in the command but not in the same directory.

I'm going to close this issue now.

Thanks for using the reporter!! ❤️
