### ISSUE TITLE
What is the expected behaviour of helpers to calculate the `totalFolders` and `totalFailedFolders`in the templates

### ISSUE THREAD

**Issue by ragnarok66** [DannyDainton/newman-reporter-htmlextra#434]
### Is There An Existing Issue

- [X] I have searched the [issue tracker](https://github.com/DannyDainton/newman-reporter-htmlextra/issues) for similar problems.

### What Are You Seeing

Hi, 

I am trying to use in my template the handlebar helpers 'totalFolders' and the 'totalFailedFolders' in order to see the data in the summary section.

The way I am using the helpers in my template is:

```
<h1 class="display-{{#gt stats.assertions.total 999 }}4{{else}}1{{/gt}}">{{totalFolders aggregations}}</h1>
<h1 class="display-{{#gt stats.assertions.total 999 }}4{{else}}1{{/gt}}">{{totalFailedFolders aggregations}}</h1>
```

For both of them it returns same error:

```
return aggregations.length;
                            ^
TypeError: Cannot read properties of undefined (reading 'length')
```

I wonder what I am doing wrong ? Any help about this is more then welcome.

Thank you in advance.

### Steps To Reproduce The Issue

It can be generated with the command from "Full Newman Command Or Node Script" section.

The handlebar helpers totalFolders and totalFailedFolders must be used in the custom template.

In my custom template I only added the two lines in the summary section:
```
<h1 class="display-{{#gt stats.assertions.total 999 }}4{{else}}1{{/gt}}">{{totalFolders aggregations}}</h1>
<h1 class="display-{{#gt stats.assertions.total 999 }}4{{else}}1{{/gt}}">{{totalFailedFolders aggregations}}</h1>
```

Works with any collection where you pass the folder to be executed. The delay, custom title, browser title, logs, noSyntaxHighlighting and showGlobalData are not mandatory.

### Full Newman Command Or Node Script

```bash
npx newman run sweet/collections/Sweet.postman_collection.json --folder "Verify the sweets" --delay-request 1000 --environment sweet/environments/QAB.postman_environment.json --insecure -r cli,htmlextra --reporter-htmlextra-template sweet/template/batman.hbs --reporter-htmlextra-export testArtifacts/sweet.html --reporter-htmlextra-title "Regression-Tests-sweets" --reporter-htmlextra-browserTitle "Sweet" --reporter-htmlextra-logs --reporter-htmlextra-noSyntaxHighlighting --reporter-htmlextra-showGlobalData
```

### HTMLEXTRA Version

1.23.0

### Newman Version

6.1.0

### Additional Context

In the summary section I would like to show the number of the test cases, which in my cases are the executed sub-foders
![image](https://github.com/DannyDainton/newman-reporter-htmlextra/assets/20386118/ca09601c-32c1-40ba-96de-ae7ce436a494)

In the image above I use in the template:
<h1 class="display-{{#gt stats.assertions.total 999 }}4{{else}}1{{/gt}}">{{stats.iterations.total}}</h1>
which is not correct, because it is the iterations count.

In my structure each sub-folder is a scenario. I want to count those scenarios.

In the Total Requests section is visible:
![image](https://github.com/DannyDainton/newman-reporter-htmlextra/assets/20386118/8b4dd1b1-0b93-4ba9-a849-bdc2691c62fc)

**Comment by DannyDainton** [comment]
Hey @ragnarok66,

Just to be clear here, this isn't actually an issue with the reporter and the general report output seen by everyone - This is an issue with your custom template which is outside of anything that I have created. 

I don't actually use those helpers in my templates, there were added to the reporter for a specific users context:

https://github.com/DannyDainton/newman-reporter-htmlextra/issues/191 

This was about 4 years, I didn't fully understand what the user was doing back then and I still don't know.

**Comment by ragnarok66** [comment]
Hey @DannyDainton  thank you for the fast replay. You are correct, this is not an issue with the original template. I want to accomplish the same this as @DannyDainton. I need to show the total folders that were executed and the total failed folders.
I used his draft template, but cannot accomplish the same results. :(

**Comment by DannyDainton** [comment]
I can't say what they were trying to do at that point in time - I tried to run the same thing back then and I still wasn't quite understanding what those helpers were needed for.

There's not a great deal I can do here I'm afraid, I'm not going to spending time investigating those helpers and getting them running for a custom template. I just simply don't have time to do that.

**Comment by ragnarok66** [comment]
Closing the issue. 
It is not an issue in the report. 
Resolved my problem by following an old issue.

[[Old Issue Link](url)](https://github.com/DannyDainton/newman-reporter-htmlextra/issues/191)

**Comment by ragnarok66** [comment]
Not an issue
