### ISSUE TITLE
How can I filter failed requests in my custom report?

### ISSUE THREAD

**Issue by ragnarok66** [DannyDainton/newman-reporter-htmlextra#435]
### Is There An Existing Issue

- [X] I have searched the [issue tracker](https://github.com/DannyDainton/newman-reporter-htmlextra/issues) for similar problems.

### What Are You Seeing

Hi,

I am using custom report and I am trying to filter and show only failed requests. In my case, the tests are the requests, because in the structure each folder is a test case.

In the screenshot bellow is visible that in the nav bar the "Total Tests" and "Failed Tests" shows correct number.
![image](https://github.com/DannyDainton/newman-reporter-htmlextra/assets/20386118/48338f32-17a2-41b6-9756-216f33091d10)
![image](https://github.com/DannyDainton/newman-reporter-htmlextra/assets/20386118/374afb21-03fe-4b8f-8186-0d49da2b63a1)

My problem is that I have no idea how to filter only the failed requests in "Failed Tests". 

I am using this code to show the failed tests (requests):
`{{#each aggregations}}
        {{#if parent.name}}
        <div class="alert alert-dark text-uppercase text-center iteration-{{parent.iteration}}">
        <a data-toggle="collapse" href="#" data-target="#folder-collapse-{{parent.id}}-iteration-{{parent.iteration}}" aria-expanded="false" aria-controls="collapse" id="folder-{{parent.id}}-iteration-{{parent.iteration}}" class="collapsed text-dark z-block">
        <i class="fas fa-info-circle float-left resultsInfoPass" {{#each executions}}{{#if cumulativeTests.failed}} style="color: var(--failure2); padding-top: 4px;"{{/if}}{{/each}}></i>
            {{parent.name}} - {{executions.length}} {{#gt executions.length 1}}Requests{{else}}Request{{/gt}} in the folder <i class="float-lg-right fa fa-chevron-down" style="padding-top: 4px;"></i>
        </a>
        </div>
        <div id="folder-collapse-{{parent.id}}-iteration-{{parent.iteration}}" class="collapse" aria-labelledby="folder-{{parent.id}}">
        {{> aggregations}}
        </div>
        {{else}}
        {{> aggregations}}
        {{/if}}
{{/each}} `

Any help and advice is more then welcome.

Note: This is not a bug in the original report.

### Steps To Reproduce The Issue

It can be generated with the command from "Full Newman Command Or Node Script" section.

### Full Newman Command Or Node Script

```bash
npx newman run sweet/collections/Sweet.postman_collection.json --folder "Verify the sweets" --delay-request 1000 --environment sweet/environments/QAB.postman_environment.json --insecure -r cli,htmlextra --reporter-htmlextra-template sweet/template/batman.hbs --reporter-htmlextra-export testArtifacts/sweet.html --reporter-htmlextra-title "Regression-Tests-sweets" --reporter-htmlextra-browserTitle "Sweet" --reporter-htmlextra-logs --reporter-htmlextra-noSyntaxHighlighting --reporter-htmlextra-showGlobalData
```

### HTMLEXTRA Version

1.23.0

### Newman Version

6.1.0

### Additional Context

I cannot find any information about how to iterate between aggregations.
What aggregation contains and how to filter information from it ?

**Comment by DannyDainton** [comment]
Hey @ragnarok66 

As your custom template is different, you need to share the full file rather than a some section from it. 

This is not steps to reproduce the behaviour:

```
npx newman run sweet/collections/Sweet.postman_collection.json --folder "Verify the sweets" --delay-request 1000 --environment sweet/environments/QAB.postman_environment.json --insecure -r cli,htmlextra --reporter-htmlextra-template sweet/template/batman.hbs --reporter-htmlextra-export testArtifacts/sweet.html --reporter-htmlextra-title "Regression-Tests-sweets" --reporter-htmlextra-browserTitle "Sweet" --reporter-htmlextra-logs --reporter-htmlextra-noSyntaxHighlighting --reporter-htmlextra-showGlobalData
```

I don't have access to any of that.

**Comment by ragnarok66** [comment]
[template.zip](https://github.com/DannyDainton/newman-reporter-htmlextra/files/15113011/template.zip)
Hi @DannyDainton thank you for the fast replay. Here is the custom template I use. The snipped code start at line 780. It should work with any collection. The steps to reproduce was just an example. Ignore the commented lines and the comments, it is still a draft. The goal is to show only the failed requests.
Thank you in advance.
