### ISSUE TITLE
Open File After Collection Run

### ISSUE THREAD

**Issue by jgsinn** [DannyDainton/newman-reporter-htmlextra#44]
Is there a way to automatically open the html file from the 'newman' directory after the file is generated?

**Comment by DannyDainton** [comment]
Hey @jgsinn 

I honestly don't know, it's not something that I've ever tried to do 😁

I'm sure there is some cli magic that can be done to open the latest file in the directory in a specific browser or something 🤔

Anything in here helpful? 

https://stackoverflow.com/questions/18472464/how-do-i-open-a-file-with-chrome-from-the-command-line

This isn't really a _reporter_ issue so I'm going to close this for now. Happy to open again if you feel differently. 😁
