### ISSUE TITLE
How do I disable console display feature?

### ISSUE THREAD

**Issue by angmas** [DannyDainton/newman-reporter-htmlextra#46]
Hi Danny,

This htmlextra is exactly what I am looking for. Thanks for creating this!

Is there an option to disable test scripts console.log output-- An equivalent to the newman cli
```--reporter-cli-no-console``` option?

Thanks,
Angela

**Comment by DannyDainton** [comment]
Hey,

Thank you for your kind words - there isn't anything at the moment, they kinda come through (In a way that I want to change) in you have them In the collection.

I'm going to close this issue and add a feature request for this, to the project board I have. Makes sense to surpress them and not see them on the reports.

Not sure when I'll get round to doing this but if you want to get it a go in the meantime, I'll take a PR 😁

**Comment by DannyDainton** [comment]
Hey @angmas 

I've added a `--reporter-htmlextra-logs` flag to show the `console.log()` statements in the final report. It's `false` by default. Hope that's what you had in mind. :)

This has been added to version 1.7.0.

**Comment by angmas** [comment]
Yes! Thank you!!!
