### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by flashcsgroups** [DannyDainton/newman-reporter-htmlextra#5]
Good day. I'm new. Tell us how you can use the code CLI ?
const newman = require('newman'); // require newman in your project

// call newman.run to pass `options` object and wait for callback
newman.run({
    collection: require('./sample-collection.json'),
    reporters: 'cli'
}, function (err) {
	if (err) { throw err; }
    console.log('collection run complete!');
});

Perhaps this code should be placed in a file index.js . And call something like this: node index.js ?
I not found in Internet resources on this topic. Thanks in advance for any reply.

**Comment by DannyDainton** [comment]
I'm not sure what you are asking?

Is this just to know how to use the CLI reporter of Newman, from within a node script?

https://github.com/postmanlabs/newman

That's its own project, this is an additional reporter that you can use with Newman.
