### ISSUE TITLE
jquery.min.js在线引用地址是谷歌的，能否换成官网的，中国大陆无法访问

### ISSUE THREAD

**Issue by qianchilang** [DannyDainton/newman-reporter-htmlextra#64]
jquery.min.js在线引用地址是谷歌的，能否换成官网的，中国大陆无法访问，导致生成的报告内链接无法跳转

**Comment by qianchilang** [comment]
> jquery.min.js在线引用地址是谷歌的，能否换成官网的，中国大陆无法访问，导致生成的报告内链接无法跳转

https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js

**Comment by DannyDainton** [comment]
I'll take a look at that - I'm on vacation at the moment but will change that once I'm back home.

In the meantime, you could create a new template a swap out that Google link for the official one to unblock this for you.

**Comment by DannyDainton** [comment]
Updated the link in v1.7.5
