### ISSUE TITLE
newman-reporter-htmlextra\node_modules\highlight.js\tools\build.js

### ISSUE THREAD

**Issue by RuggeriLuca** [DannyDainton/newman-reporter-htmlextra#7]
**Describe the bug**
Installing the new version of the report i take the error 

npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated hoek@0.9.1: The major version is no longer supported. Please update to 4.x or newer
npm WARN newman-reporter-htmlextra@1.5.5 requires a peer of newman@>=4 but none is installed. You must install peer dependencies yourself.

npm ERR! path C:\Users\l.ruggeri\AppData\Roaming\npm\node_modules\newman-reporter-htmlextra\node_modules\highlight.js\tools\build.js
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\Users\l.ruggeri\AppData\Roaming\npm\node_modules\newman-reporter-htmlextra\node_modules\highlight.js\tools\build.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\l.ruggeri\AppData\Roaming\npm-cache\_logs\2019-02-25T08_16_41_837Z-debug.log

**To Reproduce Steps to reproduce the behavior:**
npm uninstall -g newman-reporter-htmlextra
npm cache clean --force
npm install -g newman-reporter-htmlextra

**Version Information:**
Newman Version [newman@4.4.0]
NPM Package Version [6.8.0]

**Comment by DannyDainton** [comment]
Are you able to fully uninstall `npm uninstall -g newman-reporter-htmlextra` from your machine and then reinstall please.

Sending a very specific error, from your machine, doesn't really give me a lot of information to work with, if I'm being honest. 

Please follow the Issue template to capture more relevant and usable details.

**Comment by RuggeriLuca** [comment]
i have update the issues based on template . How i can load log files?

**Comment by DannyDainton** [comment]
That should be enough for me to have a look now - The collection files are not needed for this type of issue, I will take a look and get back to you once I have a fix in place.

Thank you for raising this issue.

**Comment by DannyDainton** [comment]
There was an issue with the `highlight.js` project that was causing an install failure in the package - I haven't been about the solve the issue yet but I wanted to add this here for context.

https://github.com/highlightjs/highlight.js/commit/58b0dd0cf033ffb6506734c8abfb7e059a8c6fe8

**Comment by DannyDainton** [comment]
Update - This is still an issue and is being looked at by the `highlight.js` team, this is a hobby project like this one so it really can't take any amount of time to fix. We just need to be patient.

**Comment by DannyDainton** [comment]
@RuggeriLuca This has now been resolved and you should be able to install the package from NPM.
