### ISSUE TITLE
Display Form Data from Request in the report

### ISSUE THREAD

**Issue by Prachi481992** [DannyDainton/newman-reporter-htmlextra#78]
**Is your feature request related to a problem? Please describe.**
I'm working with requests which have Input in terms of Formdata which also includes file type input. I am sending the generated report to business stakeholders who would like to see the input passed to the request in the report. But it is not getting displayed currently.
![Request in collection](https://user-images.githubusercontent.com/29755881/60106884-3c8f6680-9766-11e9-8dcd-2598ec095de0.jpg)
![Information shown in report](https://user-images.githubusercontent.com/29755881/60106891-3ef1c080-9766-11e9-93be-c95283013cfc.jpg)

**Describe the solution you'd like**
The request input should be displayed in the HTML report even when the request body is not raw.

**Describe alternatives you've considered**
An alternative will be mentioning the request input in the request description which is acceptable but little misleading.

**Additional context**
I am working with the latest versions of Newman and htmlextra reporter. and running the collection on Windows 10.

**Comment by DannyDainton** [comment]
Hey,

Just to get my head around what you need to display in the report, are you about to mock something out for me.

Apologies, I don't work with requests sending files and I don't want to get it wrong :)

**Comment by Prachi481992** [comment]
What I need is if my request body is being shown in the collection, it should just be shown in the report as well.
I don't need the file in the report, file name would suffice.
so like in the report, along with the Response Body div, a Request Body div should be shown which just   shows the request body details.
I checked the default template and for request body a condition is present which says` if body.raw`
I tried removing that condition in my custom template but it is not working.
example :  for the request details in the collection screenshot I've attached above, the Request body div should look like the attached image
![expected request body in report](https://user-images.githubusercontent.com/29755881/60109242-4d41db80-976a-11e9-9689-5e2908057cc5.jpg)

**Comment by DannyDainton** [comment]
Ok cool - Let me take a look and I will let you know how I get on :)

**Comment by DannyDainton** [comment]
@Prachi481992 

Would something along the line of this work? Just messing about at the moment.

<img width="1268" alt="Screenshot 2019-06-25 at 18 25 33" src="https://user-images.githubusercontent.com/17089546/60119617-ccd5a780-9776-11e9-9d1f-0cf1cab019b8.png">

**Comment by Prachi481992** [comment]
@DannyDainton , This seems good...
But actually It will be better if we can get something like the example I gave cause it is more in sync with the way the response body is displayed.

**Comment by DannyDainton** [comment]
The why that the form data and the raw json data are returned are different so it's not going to be the same as that example. 

Think about in terms of the way you input the form data in the Postman app.

I'm going to do something to cater for a wider audience rather than a single use case - If that's not what you require, you can change this on your side in a template 😁

**Comment by Prachi481992** [comment]
I’ll make the changes the template on my side form now..
But I look forward to the new version..
Thanks.. :)

**Comment by DannyDainton** [comment]
Ok, you're looking for something like `body.formdata.members` I think that's what contains the form data for the request.

If you change it and get something working, feel free to send a PR.

**Comment by DannyDainton** [comment]
@Prachi481992 

I added something like this to the template but I'm not happy with the way the report opens, just seems all laggy to me. 

```
                {{#if body.formdata}}
                <div class="row">
                <div class="col-sm-12 mb-3">
                    <div class="card-deck">
                    <div class="card border-info" style="width: 50rem;">
                        <div class="card-body">
                            <h5 class="card-title text-uppercase text-white text-center bg-info">Request Form Body</h5>
                            <table class="table table-bordered">
                                <thead class="thead-light text-center"><tr><th>Key</th><th>Value</th></tr></thead>
                                    <tbody>
                                        {{#each body.formdata.members}}
                                        <tr>
                                            <td class="text-nowrap">{{key}}</td>
                                            {{#if src}}
                                            <td class="text-nowrap">{{src}}</td>
                                            {{else}}
                                            <td class="text-nowrap">{{value}}</td>
                                            {{/if}}
                                        </tr>
                                        {{/each}}
                                    </tbody>
                            </table>
                        </div>
                    </div>
                    </div>
                </div>
                </div>
                {{/if}}
```

I'm going to leave this request open for now and park it but let me know if you get something better working.

**Comment by Prachi481992** [comment]
@DannyDainton 
I was trying on the other end
I tried something like

```{{#if body.formdata.members}}
                <div class="row">
                <div class="col-sm-12 mb-3">
                    <div class="card-deck">
                    <div class="card border-info" style="width: 50rem;">
                        <div class="card-body">
                            <h5 class="card-title text-uppercase text-white text-center bg-info">Request Body</h5>
							<div class="dyn-height">
								<pre><code id="copyText-{{item.id}}" class="prettyPrintFormData">{{body.formdata.members}}</code></pre>
							</div>
                        </div>
                    </div>
                    </div>
                </div>
                </div>
				{{/if}}```

And I added something into the script for the class "prettyPrintFormData"
```$(".prettyPrintFormData").each(function () {        
        var data = $(this).text();
        var object = {};
		var props = data.split(',')
		props.forEach(function(value,key) {
			var keyValuePair = value.split('=');
            object[keyValuePair[0]] = keyValuePair[1];
		})
        $(this).text(JSON.stringify(object, null, 2));
});```

But this is giving me the file value as  [object Object]. which is obviously understandable.
So now I'm looking at how I can access the file src attribute into this function.

**Comment by DannyDainton** [comment]
How was the report page loading when you're opening the requests? Was it laggy as you were scrolling down the page?

**Comment by Prachi481992** [comment]
Nope. It is opening up pretty fine. No Lag.
But for that matter, even with the code changes you suggested, I didn't see any additional lag when the page is loaded.

**Comment by Prachi481992** [comment]
@DannyDainton, I was playing around with the code a little bit.
I cloned your repository and added an extra reporter in index.js
```
//helper for converting the object to JSON
    handlebars.registerHelper('formdata', function(context) {
        var object = {};
        context.forEach(function(value,key) {
            if(value.src) {
                object[value.key] = value.src;
            } else {
                object[value.key] = value.value;
            }
        });
        return JSON.stringify(object);
    });
```

After this my request body can be easily parsed with
```
{{#if body.formdata.members}}
                        <div class="row">
                            <div class="col-sm-12 mb-3">
                                <div class="card-deck">
                                    <div class="card border-info" style="width: 50rem;">
                                        <div class="card-body">
                                            <h5 class="card-title text-uppercase text-white text-center bg-info">Request Body</h5>
                                                <div class="dyn-height">
                                                    <pre><code id="copyText-{{item.id}}" class="prettyPrint">{{{formdata body.formdata.members}}}</code></pre>
                                                </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {{/if}}
```

And it shows my request body in the report as shown in the attached image
![Request body - trial](https://user-images.githubusercontent.com/29755881/60277124-426b8000-98fd-11e9-87a9-0b894e47aea3.jpg)

**Comment by DannyDainton** [comment]
That's awesome. Would you like me to add that in and make a new version or do you want to submit a PR?

The HTML code will need adding to the other templates too (until I refactor all that) and you don't really need the `id` in there as that's used in the response body section to copy the data to the clipboard.

**Comment by Prachi481992** [comment]
I've created a PR.
Thanks..!!
Cheers..!!
:-)

**Comment by DannyDainton** [comment]
@Prachi481992 

The pull request was slightly wrong and caused an error when the collection was run due to the reference in the template.

I added a test and caught this, didn't even catch on the review - good job I don't push it out straight away :) I'll sort it all out and push out a new version tomorrow.

**Comment by Prachi481992** [comment]
@DannyDainton 
I figured out the error.
Problems in code merge.
I have fixed it ran it.. runs properly..
I'm raising a new PR.
Please check..
:-)

**Comment by DannyDainton** [comment]
It’s cool, I changed it already and added a test.

Just sorting the new version now, no need for the the new PR

**Comment by DannyDainton** [comment]
New changes added to V1.8.0
