### ISSUE TITLE
Error when installing the reporter from a Jenkins pipeline script

### ISSUE THREAD

**Issue by bmakamsatyaprakash** [DannyDainton/newman-reporter-htmlextra#98]
Running postman/newman on jenkins with configuration file which is :

```
pipeline {
agent { label '' }
    parameters{
        choice( name: "Environment",choices: ["test","st","SIT","PRD"], description: "Environment Selection")

    }
    stages {
        stage ('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Test'){
            steps {
                sh 'npm install'
                sh 'npm install newman-reporter-htmlextra'
                
                script{
                  
                    sh 'newman run ComponentTests/Sprint1/PostmanDemo.postman_collection.json \
                    -e ComponentTests/Sprint1/Postmandemo.postman_environment.json -g \
                    globals/${Environment}.evn.json --reporters cli,htmlextra --insecure'
                                  
                }
                archive (includes: '**.html')

            }
        }
    }
}
```

It is failing on installing   on -  sh 'npm install newman-reporter-htmlextra.

**Comment by bmakamsatyaprakash** [comment]
what should be done to fix the issue.
Attaching log file for details :


2019-07-08T06_52_48_567Z-debug.log

**Comment by bmakamsatyaprakash** [comment]
7 error   stack: 'FetchError: request to https://registry.npmjs.org/newman-reporter-htmlextra failed, reason: connect ECONNREFUSED 104.16.25.35:443\n    at ClientRequest.req.on.err (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/index.js:68:14)\n    at emitOne (events.js:116:13)\n    at ClientRequest.emit (events.js:211:7)\n    at TLSSocket.socketErrorListener (_http_client.js:387:9)\n    at emitOne (events.js:116:13)\n    at TLSSocket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)' }
18 error If you are behind a proxy, please make sure that the
18 error 'proxy' config is set properly.  See: 'npm help config'
19 verbose exit [ 1, true ]

**Comment by DannyDainton** [comment]
Hey,

Are you able to download that from the command line on it's own and not part of that Jenkins script? 

Have you checked your Jenkins setup? Does it download any other reporter package (html or csv) from NPM. 

Not really sure what you would like me to do about this as I honestly don't think it's a htmlextra specific issue.

**Comment by bmakamsatyaprakash** [comment]
Sure.. Thanks. I shall use the template .Apologies.
Issue is resolved by itself. Sorry for inconvenience and thanks for support
